### ISSUE TITLE
wrong object_class in ext_translations when using Class Table Inheritance with DiscriminatorMap

### ISSUE THREAD

**Issue by whitewhidow** [Atlantic18/DoctrineExtensions#1046]
Hi there, i have a Product, and a Wine entity

(ps: this all happened after updating several bundles including symfony itself, before this, all was working fine)

on the top of my product entity : 

```
//..
 * @ORM\DiscriminatorMap({
 *      "wine" = "Them\HeritageWineClub\HWCBoutiqueBundle\Entity\Wine",
//..
```

in my wine entity

```
//..
class Wine extends Product
//..
```

entity-wise, all is fine, and BEFORE the update, all translations where fine, they where getting saved to 'ext_translations' with object_class set to 'Them\HeritageWineClub\HWCBoutiqueBundle\Entity\Wine'

and they where retrieved also using that object_class, so all was fine,

but now AFTER the update, it is making the following query to retrieve the entity + translations : 

```
SELECT e0_.content AS content0, e0_.field AS field1 FROM ext_translations e0_ WHERE e0_.foreign_key = 75 AND e0_.locale = 'zh' AND e0_.object_class = 'Them\\HeritageWineClub\\HWCBoutiqueBundle\\Entity\\Product'
```

It is now looking for a translation with the object_class of the parent?

Can anyone point me in the right direction please, is this an issue with the library? or is it me ?  i've spent the last day looking for whats going on, but cant seem to figure it out.

Thx

EDIT: PS: the translatable field is defined on the parent entity : Product, i am assuming thats why this is happening, but how do i prevent it ?

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
