### ISSUE TITLE
Generate unique slug within a certain parent

### ISSUE THREAD

**Issue by choonge** [Atlantic18/DoctrineExtensions#1058]
I have a Category which can have multiple Question. The Question has a slug field, which I want to be unique within a Category. So, this is what currently happens:

| Category | Question.title | Question.slug |
| --- | --- | --- |
| Photo | I am so confused | i-am-so-confused |
| Photo | I am so confused | i-am-so-confused-1 |
| Video | I am so confused | i-am-so-confused-2 |

But I want this to happen:

| Category | Question.title | Question.slug |
| --- | --- | --- |
| Photo | I am so confused | i-am-so-confused |
| Photo | I am so confused | i-am-so-confused-1 |
| Video | I am so confused | i-am-so-confused |

Using the existing Handlers I have so far managed to prepend the Category.title to the Question.slug, so I have this result:

| Category | Question.title | Question.slug |
| --- | --- | --- |
| Photo | I am so confused | photo-i-am-so-confused |
| Photo | I am so confused | photo-i-am-so-confused-1 |
| Video | I am so confused | video-i-am-so-confused |

Which is almost what I want, but because I'm already using the Category.title in the URL, I would prefer not having it again in the slug.

Am I overseeing some sort of configuration option which already makes this possible? If this is currently not possible, I volunteer to implement a Handler for it.

**Comment by tristanbes** [comment]
Did this problematic has been solved ? I'm in a similar scenario and in the documentation I didn't find example to deal with this.

**Comment by tristanbes** [comment]
ping @l3pp4rd

**Comment by l3pp4rd** [comment]
@tristanbes I do not have time currently for this project

**Comment by razmo** [comment]
I have the same issue. I will work on a pull request as soon as i can !

**Comment by a-mayer** [comment]
I ran into this earlier this evening (wanting to use a parent entity as unique_base) and worked out a solution here: https://github.com/a-mayer/DoctrineExtensions/commit/603a9208c85eb93a98a916a16e4e4a779b19237e. Appreciate any feedback! I have another PR (to fix Doctrine 2.5 embeddables issue in this same class) I'm finishing tests for and would be happy to get this one on the way too if there's interest.

**Comment by l3pp4rd** [comment]
@a-mayer if you would add a test case to prevent regression and submit a pull request that would be appropriate

**Comment by rolebi** [comment]
@a-mayer I've tried to provide a PR using your code but end discovering another bug ( #1349 ) preventing it from working on several tests.

**Comment by fabiorphp** [comment]
Any news on this feature?

**Comment by rolebi** [comment]
@fabiorphp well it has been fixed and merged thanks to @a-mayer code :)

**Comment by fabiorphp** [comment]
Awesome, but, How can I use this example? It's like of the @choonge:

But I want this to happen:

Category	Question.title	Question.slug
Photo	I am so confused	i-am-so-confused
Photo	I am so confused	i-am-so-confused-1
Video	I am so confused	i-am-so-confused



| Category        | Question.title           | Question.slug  |
| ------------- |:-------------:| -----:|
| Photo      | I am so confused | i-am-so-confused |
| Photo      | I am so confused      |   i-am-so-confused-1 |
| Video | I am so confused      |    i-am-so-confused |

Do you have any example of this problem?
