### ISSUE TITLE
Second query \w TranslationWalker isn't working (second query is executed for translation)

### ISSUE THREAD

**Issue by piwi91** [Atlantic18/DoctrineExtensions#1064]
Hi,

I've created an entity which should be translated to 8 other languages. The queries with the translationwalker does generate left joins (which is good), but after the first query, the second, thirth, etc. queries do generate a second query to retrieve the languages. Since I already have the correct language this query shouldn't be executed. It this a known bug?

Update: It's going wrong because the skipOnLoad property in the TranslatableListener is set on false for the second, thirth, etc. queries. At the first query it's set on true which prevents the postLoad method to execute extra translation queries.

**Comment by kbond** [comment]
I seem to be having this problem as well. @piwi91 did you find a solution?

**Comment by l3pp4rd** [comment]
maybe something has changed in doctrine. do you add locale in hint too? version of ORM? it seems like cached query behavior has changed. does it happen with an older ORM?

**Comment by kbond** [comment]
No, didn't add locale hint. ORM: 2.5.4.

Reading through #1021 I was able to fix the issue by disabling query caching.

```php
$query->useQueryCache(false);
$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, TranslationWalker::class)
```

**Comment by l3pp4rd** [comment]
add locale hint in query. if you read the documentation carefully, it explains that if you use caching, you must specify query hints for locale, otherwise it will be the same result for any locale, which gets cached first.

**Comment by kbond** [comment]
I tried that but it didn't make a difference. The query is the same but the parameters are different. I see in the query log the query hint is working but the `postLoad` operation is still happening regardless.

**Comment by l3pp4rd** [comment]
try downgrading orm to 2.4.x and test whether that makes a change, make sure you cleaned up all caches including query

**Comment by kbond** [comment]
No difference in 2.4.8

**Comment by l3pp4rd** [comment]
I spent my 1h just for you, modified the example code. hope you can learn something from that. cheers

**Comment by piwi91** [comment]
This isn't an issue for me anymore. I don't know how (or if) I fixed it. Because this was an issue in a project at my former employer, I can't check it for you how I resolved it.

I will close this ticket now.
