### ISSUE TITLE
Please Revisit #1027

### ISSUE THREAD

**Issue by Padam87** [Atlantic18/DoctrineExtensions#1081]
https://github.com/Atlantic18/DoctrineExtensions/pull/1027#issuecomment-41812303

**Comment by TwanVermeulen** [comment]
I'm facing the same issue as @Padam87 at this moment. I can't add versioning to properties that are defined in an extended class that uses Table Inheritance. Can we have another look at #1027?

**Comment by l3pp4rd** [comment]
can someone apply the diff from https://github.com/Atlantic18/DoctrineExtensions/pull/1027 in a pull request? And change `propertyNames` to `fields`. make sure they do not duplicate in `$config['versioned'][]` array and add documentation about this option in doc/loggable.md then I can accept the change

**Comment by l3pp4rd** [comment]
and probably a test case would be necessary, to prevent later regression.

**Comment by TwanVermeulen** [comment]
I'm willing to solve the issue that @Padam87 and I are having. #1027 is about a new feature, which can be used as a workaround for the actual problem. I want to focus on the actual issue first. Why are inherited fields skipped? Can't they just be be versioned like regular fields? We only have to make sure that we don't get duplicates in `$config['versioned'][]`. Please have a look at 264b0d6b7dfb6ee0c0be077bc35f9af99b3bd94e.

**Comment by grbatinic-bogdan** [comment]
I was able to find a workaround for this issue using [attributeOverride](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#attribute-override) option. I'm using yml entity configuration.

**Comment by TwanVermeulen** [comment]
@grbatinic-bogdan Can you show me an example? Do you use inheritance mapping for your entity? The driver skips those field properties, so I don't think it will solve the issue in my case.

**Comment by grbatinic-bogdan** [comment]
Well I'm using FOSUserBundle, in this case User object. My user class extends from FOS's base user class. So in my entity config I overrode properties which i want to be loggable. 
I think [this](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Loggable/Mapping/Driver/Yaml.php#L61) part of the code takes care of updating the fields that you have overwritten in your entity config. I didn't find that in annotation driver though, so if you're using annotations for entity configuration it may not apply to your case.

**Comment by TwanVermeulen** [comment]
Thanks for the clarification. That seems to be a good solution for yml configuration. I'm using annotations, so this issue is still valid :)
