### ISSUE TITLE
Empty RelativeSlugHandler prefix

### ISSUE THREAD

**Issue by Misiur** [Atlantic18/DoctrineExtensions#1082]
Hello. I'm using RelativeSlugHandler to generate prefixed slug from other entity string field (not a slug one), and it works perfectly. However there is special case, where my prefix is empty. The handler is just like a honey badger - [it just doesn't care](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Sluggable/Handler/RelativeSlugHandler.php#L135). Would PR allowing empty prefix be accepted?

Oh, and yes - slugs are generated, but they look like "/slug" instead of desired "slug".

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
