### ISSUE TITLE
Applying TranslationWalker hint causes extra queries for one2one associations

### ISSUE THREAD

**Issue by sparrowek** [Atlantic18/DoctrineExtensions#1091]
I have a following query 
        $query = $this->_em->createQuery('
            SELECT ut, t, u, c, ds, db, au, a, d
            FROM Application\Entity\UserTrainer ut
            INNER JOIN ut.trainer t
            INNER JOIN ut.trainee u
            LEFT JOIN u.contracts c
            LEFT JOIN u.dietSettings ds
            LEFT JOIN ds.database db
            LEFT JOIN db.amountUnit au
            LEFT JOIN ds.activity a
            LEFT JOIN ds.diseases d
            WHERE ut = :id
        ');
        $query->setParameter('id', $id);

Which generates queries:
          807 Query SELECT u0_.id AS id0, u1_.id AS id1, p2_.id AS id2, p2_.blocked AS blocked3, u3_.login AS login4, u3_.password AS password5, u3_.nickname AS nickname6, u3_.status AS status7, u3_.hash AS hash8, u3_.register_date AS register_date9, c4_.id AS id10, c4_.sign_date AS sign_date11, c4_.start_date AS start_date12, c4_.end_date AS end_date13, c4_.cost AS cost14, c4_.tax_rate AS tax_rate15, c4_.checkup_length AS checkup_length16, c4_.active AS active17, c4_.accepted AS accepted18, c4_.extended AS extended19, c4_.pkwiu AS pkwiu20, c4_.discount AS discount21, d5_.id AS id22, d6_.id AS id23, d6_.name AS name24, d6_.public AS public25, d6_.attribute_per_value AS attribute_per_value26, d7_.id AS id27, d7_.name AS name28, d7_.category_id AS category_id29, d7_.`order` AS order30, d8_.id AS id31, d8_.name AS name32, d8_.category_id AS category_id33, d8_.`order` AS order34, d9_.id AS id35, d9_.name AS name36, d9_.category_id AS category_id37, d9_.`order` AS order38, u0_.user_id AS user_id39, u0_.trainer_role_id AS trainer_role_id40, u1_.user_id AS user_id41, u1_.role_id AS role_id42, p2_.discriminator AS discriminator43, c4_.product_id AS product_id44, c4_.user_id AS user_id45, d5_.activity_id AS activity_id46, d5_.lifestyle_id AS lifestyle_id47, d5_.trainee_id AS trainee_id48, d5_.database_id AS database_id49, d6_.amount_unit_id AS amount_unit_id50, d6_.owner_id AS owner_id51 FROM users_trainers u0_ INNER JOIN users_roles u1_ ON u0_.trainer_role_id = u1_.id INNER JOIN users u3_ ON u0_.user_id = u3_.id LEFT JOIN principals p2_ ON u3_.id = p2_.id LEFT JOIN contracts c4_ ON u3_.id = c4_.user_id LEFT JOIN diet_settings d5_ ON u3_.id = d5_.trainee_id LEFT JOIN diet_databases d6_ ON d5_.database_id = d6_.id LEFT JOIN dictionary d7_ ON d6_.amount_unit_id = d7_.id LEFT JOIN dictionary d8_ ON d5_.activity_id = d8_.id LEFT JOIN diet_settings_diseases d10_ ON d5_.id = d10_.diet_settings_id LEFT JOIN dictionary d9_ ON d9_.id = d10_.disease_id WHERE u0_.id = '7'
          807 Query SELECT e0_.content AS content0, e0_.field AS field1 FROM ext_translations e0_ WHERE e0_.foreign_key = 24 AND e0_.locale = 'pl_PL' AND e0_.object_class = 'Application\Entity\Dictionary'

I would like to reduce extra queries for translations so I hinted a query with:
$query->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\Translatable\Query\TreeWalker\TranslationWalker');
$query->setHint(\Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE, \Locale::getDefault());

But this generates even more queries:
          808 Query SELECT u6_.id AS id0, u7_.id AS id1, p8_.id AS id2, p8_.blocked AS blocked3, u9_.login AS login4, u9_.password AS password5, u9_.nickname AS nickname6, u9_.status AS status7, u9_.hash AS hash8, u9_.register_date AS register_date9, c10_.id AS id10, c10_.sign_date AS sign_date11, c10_.start_date AS start_date12, c10_.end_date AS end_date13, c10_.cost AS cost14, c10_.tax_rate AS tax_rate15, c10_.checkup_length AS checkup_length16, c10_.active AS active17, c10_.accepted AS accepted18, c10_.extended AS extended19, c10_.pkwiu AS pkwiu20, c10_.discount AS discount21, d11_.id AS id22, d12_.id AS id23, d12_.name AS name24, d12_.public AS public25, d12_.attribute_per_value AS attribute_per_value26, d0_.id AS id27, COALESCE(t1_.content, d0_.name) AS name28, d0_.category_id AS category_id29, d0_.`order` AS order30, d2_.id AS id31, COALESCE(t3_.content, d2_.name) AS name32, d2_.category_id AS category_id33, d2_.`order` AS order34, d4_.id AS id35, COALESCE(t5_.content, d4_.name) AS name36, d4_.category_id AS category_id37, d4_.`order` AS order38, u6_.user_id AS user_id39, u6_.trainer_role_id AS trainer_role_id40, u7_.user_id AS user_id41, u7_.role_id AS role_id42, p8_.discriminator AS discriminator43, c10_.product_id AS product_id44, c10_.user_id AS user_id45, d11_.activity_id AS activity_id46, d11_.lifestyle_id AS lifestyle_id47, d11_.trainee_id AS trainee_id48, d11_.database_id AS database_id49, d12_.amount_unit_id AS amount_unit_id50, d12_.owner_id AS owner_id51 FROM users_trainers u6_ INNER JOIN users_roles u7_ ON u6_.trainer_role_id = u7_.id INNER JOIN users u9_ ON u6_.user_id = u9_.id LEFT JOIN principals p8_ ON u9_.id = p8_.id LEFT JOIN contracts c10_ ON u9_.id = c10_.user_id LEFT JOIN diet_settings d11_ ON u9_.id = d11_.trainee_id LEFT JOIN diet_databases d12_ ON d11_.database_id = d12_.id LEFT JOIN dictionary d0_ ON d12_.amount_unit_id = d0_.id LEFT JOIN dictionary d2_ ON d11_.activity_id = d2_.id LEFT JOIN diet_settings_diseases d13_ ON d11_.id = d13_.diet_settings_id LEFT JOIN dictionary d4_ ON d4_.id = d13_.disease_id LEFT JOIN ext_translations t1_ ON t1_.locale = 'pl_PL' AND t1_.field = 'name' AND t1_.object_class = 'Application\Entity\Dictionary' AND t1_.foreign_key = d0_.id LEFT JOIN ext_translations t3_ ON t3_.locale = 'pl_PL' AND t3_.field = 'name' AND t3_.object_class = 'Application\Entity\Dictionary' AND t3_.foreign_key = d2_.id LEFT JOIN ext_translations t5_ ON t5_.locale = 'pl_PL' AND t5_.field = 'name' AND t5_.object_class = 'Application\Entity\Dictionary' AND t5_.foreign_key = d4_.id WHERE u6_.id = '7'
          808 Query SELECT t0.principal_id AS principal_id1, t0.invoice AS invoice2, t0.name AS name3, t0.nip AS nip4, t0.postal_code AS postal_code5, t0.city AS city6, t0.street AS street7, t0.street_number AS street_number8, t0.apartment_number AS apartment_number9, t0.discount AS discount10, t0.principal_id AS principal_id11 FROM invoice_settings t0 WHERE t0.principal_id = '1'
          808 Query SELECT t0.user_id AS user_id1, t0.first_name AS first_name2, t0.last_name AS last_name3, t0.pesel AS pesel4, t0.postal_code AS postal_code5, t0.city AS city6, t0.street AS street7, t0.street_number AS street_number8, t0.apartment_number AS apartment_number9, t0.phone AS phone10, t0.sex AS sex11, t0.birth_date AS birth_date12, t0.user_id AS user_id13, t0.country_id AS country_id14, t0.province_id AS province_id15 FROM user_details t0 WHERE t0.user_id = '1'
          808 Query SELECT t0.user_id AS user_id1, t0.first_name AS first_name2, t0.last_name AS last_name3, t0.postal_code AS postal_code4, t0.city AS city5, t0.street AS street6, t0.street_number AS street_number7, t0.apartment_number AS apartment_number8, t0.phone AS phone9, t0.user_id AS user_id10, t0.country_id AS country_id11, t0.province_id AS province_id12 FROM user_details_shipping t0 WHERE t0.user_id = '1'
          808 Query SELECT t0.user_id AS user_id1, t0.notifications AS notifications2, t0.avatar AS avatar3, t0.unseen_messages AS unseen_messages4, t0.unseen_news AS unseen_news5, t0.training_checkup AS training_checkup6, t0.diet_checkup AS diet_checkup7, t0.user_id AS user_id8, t0.language_id AS language_id9, t0.metric_system_id AS metric_system_id10 FROM user_settings t0 WHERE t0.user_id = '1'
          808 Query SELECT t0.user_id AS user_id1, t0.max_hr AS max_hr2, t0.lt_hr AS lt_hr3, t0.lt_watt AS lt_watt4, t0.user_id AS user_id5 FROM training_settings t0 WHERE t0.user_id = '1'
          808 Query SELECT t0.id AS id1, t0.date AS date2, t0.user_id AS user_id3 FROM diet_survey t0 WHERE t0.user_id = '1'
140604 14:30:31   808 Query SELECT t0.principal_id AS principal_id1, t0.invoice AS invoice2, t0.name AS name3, t0.nip AS nip4, t0.postal_code AS postal_code5, t0.city AS city6, t0.street AS street7, t0.street_number AS street_number8, t0.apartment_number AS apartment_number9, t0.discount AS discount10, t0.principal_id AS principal_id11 FROM invoice_settings t0 WHERE t0.principal_id = '1'
          808 Query SELECT t0.user_id AS user_id1, t0.first_name AS first_name2, t0.last_name AS last_name3, t0.pesel AS pesel4, t0.postal_code AS postal_code5, t0.city AS city6, t0.street AS street7, t0.street_number AS street_number8, t0.apartment_number AS apartment_number9, t0.phone AS phone10, t0.sex AS sex11, t0.birth_date AS birth_date12, t0.user_id AS user_id13, t0.country_id AS country_id14, t0.province_id AS province_id15 FROM user_details t0 WHERE t0.user_id = '1'
          808 Query SELECT t0.user_id AS user_id1, t0.first_name AS first_name2, t0.last_name AS last_name3, t0.postal_code AS postal_code4, t0.city AS city5, t0.street AS street6, t0.street_number AS street_number7, t0.apartment_number AS apartment_number8, t0.phone AS phone9, t0.user_id AS user_id10, t0.country_id AS country_id11, t0.province_id AS province_id12 FROM user_details_shipping t0 WHERE t0.user_id = '1'
          808 Query SELECT t0.user_id AS user_id1, t0.notifications AS notifications2, t0.avatar AS avatar3, t0.unseen_messages AS unseen_messages4, t0.unseen_news AS unseen_news5, t0.training_checkup AS training_checkup6, t0.diet_checkup AS diet_checkup7, t0.user_id AS user_id8, t0.language_id AS language_id9, t0.metric_system_id AS metric_system_id10 FROM user_settings t0 WHERE t0.user_id = '1'
          808 Query SELECT t0.user_id AS user_id1, t0.max_hr AS max_hr2, t0.lt_hr AS lt_hr3, t0.lt_watt AS lt_watt4, t0.user_id AS user_id5 FROM training_settings t0 WHERE t0.user_id = '1'
          808 Query SELECT t0.id AS id1, t0.date AS date2, t0.user_id AS user_id3 FROM diet_survey t0 WHERE t0.user_id = '1'
          808 Query SELECT d0_.id AS id0, d1_.id AS id1, d1_.checkup_date AS checkup_date2, d1_.target AS target3, d1_.notes AS notes4, d1_.protein AS protein5, d1_.fat AS fat6, d1_.carbohydrate AS carbohydrate7, d2_.id AS id8, d2_.percentage AS percentage9, d3_.id AS id10, d3_.day AS day11, d3_.protein AS protein12, d3_.fat AS fat13, d3_.carbohydrate AS carbohydrate14, d0_.activity_id AS activity_id15, d0_.lifestyle_id AS lifestyle_id16, d0_.trainee_id AS trainee_id17, d0_.database_id AS database_id18, d1_.diet_settings_id AS diet_settings_id19, d2_.checkup_id AS checkup_id20, d2_.meal_id AS meal_id21, d3_.checkup_id AS checkup_id22 FROM diet_settings d0_ LEFT JOIN diet_checkups d1_ ON d0_.id = d1_.diet_settings_id AND (d1_.checkup_date = '2014-05-14') LEFT JOIN diet_settings_meals d2_ ON d1_.id = d2_.checkup_id LEFT JOIN dictionary d4_ ON d2_.meal_id = d4_.id LEFT JOIN diet_settings_days d3_ ON d1_.id = d3_.checkup_id WHERE d0_.id = 3 ORDER BY d4_.`order` ASC, d3_.day ASC
          808 Query SELECT t7_.id AS id0, t7_.description AS description1, t7_.`order` AS order2, u8_.day AS day3, u8_.custom AS custom4, g0_.id AS id5, COALESCE(t1_.content, g0_.name) AS name6, COALESCE(t2_.content, g0_.description) AS description7, s3_.id AS id8, COALESCE(t4_.content, s3_.name) AS name9, s3_.image AS image10, s3_.activity_id AS activity_id11, s3_.sport_events_visibility AS sport_events_visibility12, t9_.id AS id13, t9_.value AS value14, t5_.id AS id15, COALESCE(t6_.content, t5_.name) AS name16, t5_.type_id AS type_id17, t5_.category_id AS category_id18, t5_.semantic_id AS semantic_id19, t5_.options AS options20, t5_.`order` AS order21, t7_.discriminator AS discriminator22, t7_.gear_id AS gear_id23, u8_.trainee_id AS trainee_id24, g0_.discipline_id AS discipline_id25, t9_.training_id AS training_id26, t9_.parameter_id AS parameter_id27 FROM users_trainings u8_ INNER JOIN trainings t7_ ON u8_.id = t7_.id INNER JOIN gear g0_ ON t7_.gear_id = g0_.id INNER JOIN sport_disciplines s3_ ON g0_.discipline_id = s3_.id LEFT JOIN training_parameters_values t9_ ON t7_.id = t9_.training_id LEFT JOIN training_parameters t5_ ON t9_.parameter_id = t5_.id LEFT JOIN ext_translations t1_ ON t1_.locale = 'pl_PL' AND t1_.field = 'name' AND t1_.object_class = 'Application\Entity\Gear' AND t1_.foreign_key = g0_.id LEFT JOIN ext_translations t2_ ON t2_.locale = 'pl_PL' AND t2_.field = 'description' AND t2_.object_class = 'Application\Entity\Gear' AND t2_.foreign_key = g0_.id LEFT JOIN ext_translations t4_ ON t4_.locale = 'pl_PL' AND t4_.field = 'name' AND t4_.object_class = 'Application\Entity\SportDiscipline' AND t4_.foreign_key = s3_.id LEFT JOIN ext_translations t6_ ON t6_.locale = 'pl_PL' AND t6_.field = 'name' AND t6_.object_class = 'Application\Entity\TrainingParameter' AND t6_.foreign_key = t5_.id WHERE u8_.trainee_id = 1 AND u8_.day BETWEEN '2014-05-14 00:00:00' AND '2014-05-20 00:00:00'

It seems that queries are repeated for every one2one associactions

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
