### ISSUE TITLE
Request for tag

### ISSUE THREAD

**Issue by antoineguigan** [Atlantic18/DoctrineExtensions#1109]
Hello,

Would it be possible to create a new tag for the de89aaec17f4bde70db675b6f6c0ed70d1e855fe commit ? 

We currently have to use the dev version for https://github.com/akeneo/pim-community-standard. The 2.3.9 version fails for us when we create our database from the schema.

Thanks.
Antoine Guigan

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
