### ISSUE TITLE
[Blameable] Integer not a valid type mapping

### ISSUE THREAD

**Issue by Maff-** [Atlantic18/DoctrineExtensions#1137]
I'm trying to use the Blameable behavior in a Symfony2 application (via Stof..Bundle). But because my User object is not an entity managed by Doctrine I'v implemented my own listener that set the user value with the current user id (int).

Now the problem occurs when `Gedmo\Blameable\Mapping\Driver\Annotation::isValidField()` is called. As `$validTypes` = `['one', 'string', 'int']`. This seems strange, as the type doctrine uses for integers is **integer** not **int** [ [1](http://doctrine-dbal.readthedocs.org/en/latest/reference/types.html#integer) ].

Should we update the Blameable mapping drivers to use `['one', 'string', 'integer']` as validTypes?

``` php
trait UserBlameableTrait
{
    /**
     * @var int
     *
     * @Gedmo\Blameable(on="create")
     * @ORM\Column(name="entered_by_user_id", type="integer", nullable=true)
     */
    private $enteredByUserId;
}
```

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
