### ISSUE TITLE
Request for tag ;)

### ISSUE THREAD

**Issue by BitOne** [Atlantic18/DoctrineExtensions#1156]
Hello guys,

Is it possible to have a new tag for the 2.3 branch ? I'm interested in some devs that have been merged since the January tag and would like to use some stable tag.

Thanks a lot !

**Comment by TomasVotruba** [comment]
This is done, horray! Thanks probably to @l3pp4rd ?

**Comment by BitOne** [comment]
Thanks a lot @l3pp4rd ;)
