### ISSUE TITLE
Persist multi-translations

### ISSUE THREAD

**Issue by demos77** [Atlantic18/DoctrineExtensions#1162]
Hi,

i have a problem (with Symfony2 and Doctrine2).
We fill a form (for a language), and with checkboxs we choose to copy this datas into others languages.

Like this:

```
$establishment->setTranslatableLocale($language);
$establishment->setHash(uniqid('', true));
$em->persist($establishment);
$em->flush();

// Copy datas to other languages
$languagesToCopy = $form->get('copylanguage')->getData();
foreach ($languagesToCopy as $languageToCopy) {
    $establishment->setTranslatableLocale($languageToCopy);
    $establishment->setHash(uniqid('', true));
    $em->persist($establishment);
    $em->flush();
}
```

I try to use a HASH to force the persist / flush. But I can't persist the 3 languages (per example), only 2/3 or 1/3 ...

I don't know why

thanks for help

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
