### ISSUE TITLE
Translatable , TranslationWalker and Postgresql

### ISSUE THREAD

**Issue by xleliberty** [Atlantic18/DoctrineExtensions#1168]
Hi, 

I've just tried to use TranslationWalker  on a join query , and i got a problem.
As long as the postgresql generated ext_translation table as a varchar foreignKey type, the generated query in translationWalker is invalid

In my cod, i've done something like that: 

        $qv = $this->getEntityManager()->createQuery($dqlValidities);
        $qv->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );
        $qv->setHint(TranslatableListener::HINT_TRANSLATABLE_LOCALE,$locale);

Here is the error i got: 

End of query: 
AND t9_.object_class = 'MyBundle\Entity\Productcategory' AND t9_.foreign_key = p7_.id LEFT JOIN ext_translations t10_ ON t10_.locale = 'en' AND t10_.field = 'shortdesc' AND t10_.object_class = 'MyBundle\Entity\Productcategory' AND t10_.foreign_key = p7_.id WHERE (p7_.id = ? AND v0_.visible = true) AND (v0_.deleted_at IS NULL) ORDER BY v0_.position ASC, v0_.value ASC, COALESCE(CAST(t1_.content AS VARCHAR(255)), v0_.name) ASC' with params [862]:

And the error is: 
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: character varying = integer
LINE 1: ...ndle\Entity\Validitycategory' AND t1_.foreign_key = v0_.id L...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.   -

If anybody have a clue.

Thanks in advance

Xavier

**Comment by edigu** [comment]
Any update on this?

**Comment by edigu** [comment]
This PR can be closed, resolved & merged with #1249

**Comment by vitalyiegorov** [comment]
POSTGRES
we have ```promo_side``` table and its translation table ```promo_slide_translation```, both have ```promo_slide_id:integer``` field, if i remove this ```::VARCHAR``` fix from 307 line in TranslationWalker than everything works fine.

With this fix our app is getting this error:
```
An exception occurred while executing 'SELECT p0_.promo_slide_id AS promo_slide_id0, p0_.image_src AS image_src1, p0_.url AS url2, p0_.sort AS sort3, COALESCE(CAST(t1_.content AS VARCHAR(255)), p0_.title) AS title4, COALESCE(CAST(t2_.content AS VARCHAR(255)), p0_.subtitle) AS subtitle5, COALESCE(CAST(t3_.content AS VARCHAR(255)), p0_.summary) AS summary6, p0_.created_at AS created_at7, v4_.video_id AS video_id8, COALESCE(CAST(t5_.content AS VARCHAR(100)), v4_.title) AS title9, v4_.slug AS slug10, COALESCE(CAST(t6_.content AS TEXT), v4_.description) AS description11, v4_.preview_src AS preview_src12, v4_.poster_src AS poster_src13, v4_.original_video_src AS original_video_src14, v4_.tags AS tags15, COALESCE(CAST(t7_.content AS VARCHAR(100)), v4_.meta_title) AS meta_title16, v4_.google_link AS google_link17, v4_.itunes_link AS itunes_link18, COALESCE(CAST(t8_.content AS VARCHAR(255)), v4_.meta_description) AS meta_description19, v4_.favorites_count AS favorites_count20, v4_.view_count AS view_count21, v4_.like_count AS like_count22, v4_.duration AS duration23, v4_.dislike_count AS dislike_count24, v4_.youtube_like_count AS youtube_like_count25, v4_.youtube_dislike_count AS youtube_dislike_count26, v4_.youtube_link AS youtube_link27, v4_.youtube_view_count AS youtube_view_count28, v4_.created_at AS created_at29, v4_.ts_youtube AS ts_youtube30, v4_.statusRegion AS statusregion31, v4_.statusCountry AS statuscountry32, v4_.source AS source33, v4_.label AS label34, v4_.personal_id AS personal_id35, v4_.api_viewcount AS api_viewcount36, v4_.pladformId AS pladformid37, v4_.isPublished AS ispublished38, p0_.video_id AS video_id39 FROM promo_slide p0_ LEFT JOIN videos v4_ ON p0_.video_id = v4_.video_id LEFT JOIN promo_slide_translations t1_ ON t1_.locale = 'ru' AND t1_.field = 'title' AND t1_.promo_slide_id = p0_.promo_slide_id::VARCHAR LEFT JOIN promo_slide_translations t2_ ON t2_.locale = 'ru' AND t2_.field = 'subtitle' AND t2_.promo_slide_id = p0_.promo_slide_id::VARCHAR LEFT JOIN promo_slide_translations t3_ ON t3_.locale = 'ru' AND t3_.field = 'summary' AND t3_.promo_slide_id = p0_.promo_slide_id::VARCHAR LEFT JOIN video_translations t5_ ON t5_.locale = 'ru' AND t5_.field = 'title' AND t5_.video_id = v4_.video_id::VARCHAR LEFT JOIN video_translations t6_ ON t6_.locale = 'ru' AND t6_.field = 'description' AND t6_.video_id = v4_.video_id::VARCHAR LEFT JOIN video_translations t7_ ON t7_.locale = 'ru' AND t7_.field = 'metaTitle' AND t7_.video_id = v4_.video_id::VARCHAR LEFT JOIN video_translations t8_ ON t8_.locale = 'ru' AND t8_.field = 'metaDescription' AND t8_.video_id = v4_.video_id::VARCHAR WHERE v4_.video_id IN (234, 513) OR v4_.video_id IS NULL ORDER BY p0_.sort ASC':

SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: integer = character varying
LINE 1: ...u' AND t1_.field = 'title' AND t1_.promo_slide_id = p0_.prom...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by l3pp4rd** [comment]
oh I see. it needs to take a different approach in that case.. thanks for the details will try to fix it as soon as possible in master
