### ISSUE TITLE
foreign_key of two column

### ISSUE THREAD

**Issue by strauss69400** [Atlantic18/DoctrineExtensions#1173]
I have an entity which consists of a primary key on two columns.
It would have to be able to translate this entity but when I use the command "doctrine: schema: update" I have an error message:
Translatable does not support composite identifiers in class.

do you know the solution to use "gemo translatable" with an entity that has a primary key of two columns?
thank you

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
