### ISSUE TITLE
[Sluggable] should try a slug without numeric postfix first.

### ISSUE THREAD

**Issue by maximium** [Atlantic18/DoctrineExtensions#1177]
Hi!
There is an issue(I believe) when you have entity with title 'Title 777' and slug 'title-777' in db then add new entity with title 'Title' and expect this new entity will have a slug 'title' but it will have a slug 'title-1'.
I hope you understand my English :)

**Comment by cmfcmf** [comment]
This is fixed in #1316 and can be closed.
