### ISSUE TITLE
[Loggable] Log Data improved with Transaction ID would be the solution of OneToMany and ManyToMany logs

### ISSUE THREAD

**Issue by szecsikecso** [Atlantic18/DoctrineExtensions#1199]
My request is an opportunity to add a new field - Transaction ID.
This information would identify a group of logs, which is caused by ONE user operation.

This would solve @OneToMany annotations log problem, which is mentioned in issue #1160.
In my appliaction I've created a manual log function to handle @ManyToMany annotation so this would solve it too.

As I imagine it, this feature would be a powerful extension for connecting every information, which related to one main entity log.
If someone has the same problem, and he/she has to find a temporary solution, than I can offer a 99%-working trick.
Identify Group of Logs by checking their username data and the duration of time when the logs have to be created (loggedAt) - this is weakness of this way. You have to set 2-6 second duration depending on created entity count (2-100 in my case).

**Comment by rvmourik** [comment]
Is this something that's still on the roadmap? Would love to see this functionality

**Comment by l3pp4rd** [comment]
there won't be backward incompatible features. if you want something more sophisticated take some [audit log](https://github.com/DATA-DOG/DataDogAuditBundle) implementation and customize it is simple and better approach
