### ISSUE TITLE
Undefined index: slugs

### ISSUE THREAD

**Issue by smilesrg** [Atlantic18/DoctrineExtensions#1200]
Hi!

My nginx log full of error messages:

```
2014/12/05 22:21:02 [error] 15963#0: *79389 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: slugs in /var/www/myhost.com/shared/vendor/gedmo/doctrine-extensions/lib/Gedmo/Sluggable/SluggableListener.php on line 268
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/myhost.com/shared/vendor/gedmo/doctrine-extensions/lib/Gedmo/Sluggable/SluggableListener.php on line 268" while reading response header from upstream, client: 188.114.99.195, server: api.myhost.com, request: "GET /flies/pink-zonker/8950 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "myhost.com"
```

**Comment by umpirsky** [comment]
@smilesrg Did you manage to find the root cause of this?

**Comment by smilesrg** [comment]
@umpirsky not really. Don't remember what was wrong. I think this issue can be closed.

**Comment by Wiatrogon** [comment]
I think I have encountered same problem,
first I get ```Doctrine\Common\ClassLoader is deprecated.``` in ```vendor/doctrine/common/lib/Doctrine/Common/ClassLoader.php```,
which leads to ```Illegal string offset 'slugs'``` in ```vendor/gedmo/doctrine-extensions/lib/Gedmo/Sluggable/SluggableListener.php```,
which results in ```ErrorException: Invalid argument supplied for foreach()```
