### ISSUE TITLE
Use doctrine extensions with Doctrine-phpcr-odm

### ISSUE THREAD

**Issue by akeemphilbert** [Atlantic18/DoctrineExtensions#1203]
It doesn't seem like the extensions can be used with phpcr-odm (though it looks close since mongo-odm is supported). Is this something planned for the future?

**Comment by ConneXNL** [comment]
+1

**Comment by l3pp4rd** [comment]
no, it is not planned, currently there is no active development and it is in maintenance mainly. I doubt that new features will be added, unless @Atlantic18/owners going to, so far there was nothing new added after the repository was transferred.
