### ISSUE TITLE
Add function DISTANCE() to find the distance between coordinates 

### ISSUE THREAD

**Issue by Nyholm** [Atlantic18/DoctrineExtensions#1220]
If there is an interest for implementing a function that calculates the distance between two coordinates I'm happy to submit a PR. 

See this gist as a reference: https://gist.github.com/Koc/3016704

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!

**Comment by Nyholm** [comment]
Yeah =) 
It was not as popular as I thought. Thank you for keeping it open so long.

**Comment by AkenRoberts** [comment]
Definitely appreciate any feature suggestions and potential contributions! Please don't hesitate to open another issue or PR in the future. :)
