### ISSUE TITLE
SoftDeleteableListener does not honour timeAware

### ISSUE THREAD

**Issue by patrickli** [Atlantic18/DoctrineExtensions#1223]
`SoftDeleteableListener` has a logic that if the `deletedAt` property has a date it will hard delete the entity. However if `timeAware` is defined on the entity then if the date is set in the future you would most likely want the date set to `now` instead of hard delete it.

**Comment by eumene** [comment]
In Gedmo\SoftDeleteable\SoftDeleteableListener at line 66

replace code 

```
                $oldValue = $reflProp->getValue($object);
                if ($oldValue instanceof \Datetime) {
                    continue; // want to hard delete
                }
```

with

```
                $oldValue = $reflProp->getValue($object);
                if ($oldValue instanceof \Datetime) {
                    if($oldValue < new \DateTime()) {
                        continue; // want to hard delete
                    }
                }
```

**Comment by eumene** [comment]
How can I contribute?

**Comment by rolebi** [comment]
@eumene you can take a look at http://symfony.com/doc/current/contributing/code/patches.html that explains it well : )

**Comment by Webonaute** [comment]
There was a patch https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/SoftDeleteable/SoftDeleteableListener.php this has been merged but than get overwrited later.

**Comment by l3pp4rd** [comment]
Hi, you can open a pull request to support it in 2.4

**Comment by Webonaute** [comment]
#1886
