### ISSUE TITLE
Release 2.3.10 - get Doctrine\ORM\ORMInvalidArgumentException when loading fixtures

### ISSUE THREAD

**Issue by hmillet** [Atlantic18/DoctrineExtensions#1226]
Since I updated my bundle from 2.3.9 to 2.3.10, I get the following error when I load some fixtures (using ```doctrine/doctrine-fixtures-bundle```) on a blameable Entity :

```
  [Doctrine\ORM\ORMInvalidArgumentException]
  EntityManager#persist() expects parameter 1 to be an entity object, NULL given.
```

**Comment by Numkil** [comment]
I'm currently experiencing the same problem, trying to persist a quite complex data structure. Adding a manual check in blameable listener to check if newvalue is not null makes everything work as expected again.

**Comment by l3pp4rd** [comment]
It should be solved I think, by current tag, can you confirm?

**Comment by Numkil** [comment]
Works like a charm, thanks.

**Comment by hmillet** [comment]
I confirm, this works with new release 2.3.12

Thanks a lot
