### ISSUE TITLE
UploadableListener. Could use SplFileInfo?

### ISSUE THREAD

**Issue by jee7** [Atlantic18/DoctrineExtensions#1227]
Currently I have to pass either an instance of FileInfoInterface or a "valid array" to the addEntityFileInfo() method in the UploadableListener. Would it be possible to also accept an object of SplFileInfo there?

Examples show, that I should pull the array directly from the $_FILES global if I want to add an uploaded file to an entity. But I am using Doctrine with Laravel Framework and here we have an \Input::files('my_file') call to fetch the file values from the request. This call will give me an object of SplFileInfo, which has all the same properties as an array you are expecting in the addEntityFileInfo() method.

Seems kind of tedious having to create an array again after a framework has went through all the trouble of creating a neat SplFileInfo object.

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
