### ISSUE TITLE
[Tree] Resolve Target Entities and Tree Parent

### ISSUE THREAD

**Issue by isometriks** [Atlantic18/DoctrineExtensions#1234]
https://github.com/Atlantic18/DoctrineExtensions/commit/5e19886a64ef7e3540bb362eacfdf7d60c5608e6

Seems to break this. When it tries to `getRelatedClassName` `$name` is the interface, and `class_exists` doesn't work with interfaces anymore. Then it tries to create another classname which ends up being something like: `SymEdit\Bundle\CoreBundle\Model\SymEdit\Bundle\CoreBundle\Model\PageInterface` which doesn't exist either. 

Had closed this which fixed it for XML the same way it was fixed for YAML a while ago: https://github.com/Atlantic18/DoctrineExtensions/pull/1232

**Comment by isometriks** [comment]
Should I try to make a PR for this? I think it can be solved by adding this to Mapping\File\Driver.php

```php
protected function getRelatedClassName($metadata, $name)
{
        if (class_exists($name)) {
            return $name;
        }

        // HERE
        $targetReflection = new \ReflectionClass($name);
        if ($targetReflection->implementsInterface($metadata->name)) {
            return $name;
        }

        $refl = $metadata->getReflectionClass();
        $ns = $refl->getNamespaceName();
        $className = $ns . '\\' . $name;
        return class_exists($className) ? $className : '';
}
```

So that if the new resolved entity implements the interface then it is valid to be used. I can make a PR if needed.

**Comment by liverbool** [comment]
@isometriks is this can solve?

```php
if (class_exists($name) || interface_exists($name)) {
   return $name;
}
```

@stof We can't use `interface` for now.

**Comment by isometriks** [comment]
@liverbool Yeah I suppose that works as well. I was just trying to follow what was done before, to check that the resolved entity was either a subclass or implemented the interface. (I left out the subclass in my comment above though)

**Comment by isometriks** [comment]
thanks @l3pp4rd

**Comment by l3pp4rd** [comment]
should be there by now ;)

**Comment by isometriks** [comment]
thank you!
