### ISSUE TITLE
Sluggable:Can I add the id field as the slug?

### ISSUE THREAD

**Issue by chiqui3d** [Atlantic18/DoctrineExtensions#1242]
Hey guys,

Well my question is simple:
Can I add the id field as the slug?

Example:
```php   
   /**
    * @Gedmo\Slug(fields={"body", "id"})
     * @ORM\Column(length=25)
     */
    private $slug;
```
I tried but it does not add my id.

Thanks.

**Comment by chiqui3d** [comment]
This project is no longer support?

**Comment by COil** [comment]
Well if your getSlug() function returns $this->id . ' ' . $this->label, it should work no ?

**Comment by l3pp4rd** [comment]
most probably it will be null, if you use mysql it is populated only after insert. add **unique** option to ensure unique slugs if that helps

**Comment by chiqui3d** [comment]
very thanks @l3pp4rd 
It has not worked to put unique to true, I think it's because in the listener I have assigned as PrePersist and not PostPersit.¿Is it possible that the cause ?.
Is there any way to change or overwrite without touching the vendor symfony folder, assign it to PostPersist

```php   
   /**
    * @Gedmo\Slug(fields={"body", "id"},unique=true)
     * @ORM\Column(length=25,required=true)
     */
    private $slug;
```

**Comment by l3pp4rd** [comment]
```php   
   /**
    * @Gedmo\Slug(fields={"body"})
     * @ORM\Column(length=25,unique=true)
     */
    private $slug;
```
Read the manual, try it, I do not want to look at these kind of questions

**Comment by iBasit** [comment]
There is no documenation on how to set listener to be "postPersist" and unique does not solve it.

http://stackoverflow.com/questions/16779862/doctrineextension-sluggable-doesnt-work-with-id-field

**Comment by l3pp4rd** [comment]
it cannot work if id is generated after the record is actually inserted. slugs in general are not meaningful if you put id in it. id is always unique. do not use ids in slug, it does not make any sense
