### ISSUE TITLE
[Sortable] Is there a way to refresh positions of all records?

### ISSUE THREAD

**Issue by liuwenchao** [Atlantic18/DoctrineExtensions#1247]
Added sortable on an existing database, and all the existing records are having 0 as value of position. It works if create or update a specific record, but Is there a command or way to refresh existing records with correct values?

**Comment by liuwenchao** [comment]
@l3pp4rd any advice? Thanks in advance.

**Comment by l3pp4rd** [comment]
No, there isn't any command, the library does not have any commands so far. The only way would be to loop around batches or make yourself a command
