### ISSUE TITLE
Compatibility with doctrine/common > 2.5

### ISSUE THREAD

**Issue by sagaraspl** [Atlantic18/DoctrineExtensions#1251]
Hi we are facing issue with gedmo/doctrine-extension when using doctrine/common > 2.5

**Comment by sagaraspl** [comment]
No one from community?

**Comment by respinoza** [comment]
I am also interested in 2.5 support as it seems the release is scheduled for the first week of April

**Comment by fabsb** [comment]
@sagaraspl what kind of issues are you experiencing?

**Comment by l3pp4rd** [comment]
have added a [2.5.0 branch](https://github.com/Atlantic18/DoctrineExtensions/tree/maintenance/common-lib-upgrade) for what I see, there are some inconsistencies with translation query hints. Otherwise I do not think that there may be a problem to use it apart query hints.
