### ISSUE TITLE
version 2.3.11 doesn't working with doctrine/common 2.4.2

### ISSUE THREAD

**Issue by sagaraspl** [Atlantic18/DoctrineExtensions#1253]
Hi we are facing issue when using version 2.3.11 with doctrine/common 2.4.2.

When calling getNodesHierarchyQuery() of NestedTreeRepository It is not able to find QueryBuilder object on line. 198 in NestedTreeRepository $qb = $this->getQueryBuilder(); $qb->select('node')

It is throwing exception that calling of select() function on non-object. This should be fixed as soon as possible.

**Comment by sagaraspl** [comment]
No one from community?

**Comment by audriussagadinas** [comment]
Works fine here. Could you maybe give a little bit more detail and/or some code examples?

**Comment by sagaraspl** [comment]
Hi audriussagadinas, As I mentioned in my original comment,

When calling getNodesHierarchyQuery() of NestedTreeRepository It is not able to find QueryBuilder object on line. 198 in NestedTreeRepository $qb = $this->getQueryBuilder(); $qb->select('node')

It is throwing exception that calling of select() function on non-object. This should be fixed as soon as possible.

**Comment by audriussagadinas** [comment]
Tried to reproduce your issue again. Very rough "standalone" attempt can be found [here](https://gist.github.com/audriussagadinas/64acc558134f4debcf0f).
```
composer update
vendor/bin/doctrine orm:schema-tool:update --force
php works.php
```
No issues.

Also tried to reproduce it in Symfony2 using https://github.com/stof/StofDoctrineExtensionsBundle. No issues either.

>Also note the combination of library: version 2.3.11 with doctrine/common 2.4.2.

What combination of libraries works for You?

What about unit tests? Does any of them fail?

**Comment by sagaraspl** [comment]
Hi audriussagadinas

Following combination is working for me.

        "php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "gedmo/doctrine-extensions": "2.3.9",

Whenever I try gedmo/doctrine-extensions 2.3.11 it fails.

**Comment by l3pp4rd** [comment]
`$this->getQueryBuilder` is a method of **AbstractTreeRepository** if you do not extend the nested tree repository, there won't be such method..
