### ISSUE TITLE
ignore entity without translatable title

### ISSUE THREAD

**Issue by joe936** [Atlantic18/DoctrineExtensions#1256]
Hello,

I currently have 2 languages in my entity, arabic which is the main locale and english. When I move to the english locale, I wish to retrieve from the database the entity only if said entity has an english version of the title attribute. 

Currently when I query with locale english, my entities are all retrieved and the title is simply set to null or empty, and so in my site I get these entities with no text or title appearing. 

I am sure this has been implemented or solved but I cannot find out where or how. Please help.

**Comment by l3pp4rd** [comment]
query [hint with inner join](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#using-inner-join-strategy) would solve that

**Comment by joe936** [comment]
I tried it with true, 1, 0, all the combos I can think of. It is not working for me. I have a translatable class, and I am using a2lix forms (not sure if those details are helpful) my query is:

   $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('p')
                ->from('BackendPageBundle:Page', 'p');
 foreach ($keys as $key) {
            $qb->andWhere($qb->expr()->in("p." . $key, ":" . $key))
                    ->setParameter($key, $data->get($key));
        }//dynamic conditions
  $qb->orderBy('p.' . $order[0], $order[1]);
  $query = $qb->getQuery();
       return $query->setHint(\Gedmo\Translatable\TranslatableListener::HINT_INNER_JOIN, TRUE)->getResult();

And yet I am still getting empty titles.

**Comment by joe936** [comment]
Ok so I should have used the translation walker hint before the translatable listener hint otherwise the latter will not work. The documentation was not very clear on it, I read the code to figure that one out. I will close this issue.
