### ISSUE TITLE
Gedmo blameable ::  Maximum time execution error in unitofwork.php

### ISSUE THREAD

**Issue by amitblues1234** [Atlantic18/DoctrineExtensions#1261]
Hi,

We are using Gedmo extension for user updatedBy and createdBy with Blameable extenion, this works fine if we have minimal association with other entities but give error "Error: Maximum execution time of 30 seconds exceeded in  /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php line 2205 " when we multple entites are interelated associations.

Please suggest how to proceed further.
Waiting for response.

Thanks

**Comment by l3pp4rd** [comment]
can you be more specific, or can you make a test case scenario for minimal use case for it to fail?
