### ISSUE TITLE
[Closure] Doctrine validation failed

### ISSUE THREAD

**Issue by soyuka** [Atlantic18/DoctrineExtensions#1264]
Hi,

I've used the Closure table as stated in the documentation, it's working just fine ([entity gist](https://gist.github.com/soyuka/cb42ea17b7218e453a2e)). 
When I try to `doctrine:schema:validate` I got this result: 
```
[Mapping]  FAIL - The entity-class '...\UserBundle\Entity\Company' mapping is invalid:
* The association ...\UserBundle\Entity\Company#parent refers to the inverse side field ...\UserBundle\Entity\Company#children which does not exist.

[Database] FAIL - The database schema is not in sync with the current mapping file.
```

Should I be worried?

Thanks!

**Comment by l3pp4rd** [comment]
no, maybe validation does not hook listeners, because metadata is updated later

**Comment by soyuka** [comment]
oh ok, so the `inversedBy="children"` is correct?

Thanks!
