### ISSUE TITLE
Timestampable onFlush should skip any objects not in MANAGED state

### ISSUE THREAD

**Issue by kitsunet** [Atlantic18/DoctrineExtensions#1266]
If you update and delete an entity that has a timestamp field to be changed on update, the onFlush listener will try to set the changed timestamp and recalculate a change set but due ot the object being scheduled for deletion it is no longer managed and the UOW will throw an exception.
This is easily fixed by checking if the object state is managed before doing any changes.

**Comment by Venzon** [comment]
its related to recent change in Timestampable listener :(

**Comment by l3pp4rd** [comment]
yes probably will need to revert it back :(

**Comment by Venzon** [comment]
prolly yes :+1:
