### ISSUE TITLE
Strange problem

### ISSUE THREAD

**Issue by cmodijk** [Atlantic18/DoctrineExtensions#1268]
From time to time we are getting exceptions in our logging server and we can't find what this is casing. After some debugging on our production server i dumped the array used by the TreeListener and this looks like this. I think it's an APCu thing but i'm wondering if someone has got the same error and now how to fix this? 

![decoding](https://cloud.githubusercontent.com/assets/771041/6712921/873b28ea-cd8f-11e4-98da-25f2522f2ad6.png)

```
Uncaught PHP Exception Gedmo\Exception\InvalidArgumentException: "ORM TreeListener does not support tree type: " at /vendor/composer/gedmo/doctrine-extensions/lib/Gedmo/Tree/TreeListener.php line 84
```

I also created an issue ad the APCu repo https://github.com/krakjoe/apcu/issues/111

**Comment by l3pp4rd** [comment]
there is a number of issues with APC and APCu avoid it as much as possible, it simply has memory leaks and I cannot help you with that in anyway. use opcache and upgrade your php version.

**Comment by cmodijk** [comment]
We are running PHP 5.6.6 but use APCu to store the Doctrine meta data. I guess we have to move that to something else or wait for any response on the apcu repo. Tnx for your response!

**Comment by l3pp4rd** [comment]
Well, it is sad you were using it for so long. Google for **apc memory leaks** and look in the issues of many php repositories.. there is no point in waiting for another production error

**Comment by cmodijk** [comment]
I have read all the stories and things about APC an APCu but never had any problems with it.
