### ISSUE TITLE
The column `field` in the ext_translations table is too short

### ISSUE THREAD

**Issue by func0der** [Atlantic18/DoctrineExtensions#1269]
Hey,

I saw that there is a limit of 32 characters for the `field` column in the `ext_translations` table.

I think that is very short.

Why not push it all the way to 255 or at least to 128?

**Comment by l3pp4rd** [comment]
Override the mapping on custom translation entity class or change it by your own event listener.

**Comment by func0der** [comment]
I know that there are possibilities to change that for my application, but don't you think it is much too short by default?

And how would I change it with an event listener?

**Comment by l3pp4rd** [comment]
hook to the metadata load event and update it for this specific class

**Comment by func0der** [comment]
Okay, thanks.

And an answer to my question? Don't you think 32 is a little bit too less for this kind of field?

**Comment by l3pp4rd** [comment]
Well, you are the first asking this question, so maybe no. Most out where do not make long field names, or they update the metadata silently. So I do not see it as a problem actually.

**Comment by func0der** [comment]
Okay.

Thank you for your help and answers :)

**Comment by l3pp4rd** [comment]
you are welcome ;)
