### ISSUE TITLE
[Sortable] (ODM) Fatal error: Class 'Doctrine\ORM\UnitOfWork' not found

### ISSUE THREAD

**Issue by Rbn3D** [Atlantic18/DoctrineExtensions#1277]
Fatal error: Class 'Doctrine\ORM\UnitOfWork' not found
in Gedmo/Sortable/SortableListener.php on line 484

if I change 
```
use Doctrine\Common\EventArgs;
use Doctrine\Common\Persistence\Mapping\ClassMetadata;
use Doctrine\Common\Util\ClassUtils;
use Doctrine\ORM\UnitOfWork;
use Gedmo\Mapping\MappedEventSubscriber;
use Doctrine\ORM\Proxy\Proxy;
use Gedmo\Sortable\Mapping\Event\SortableAdapter;
```

to 

```
use Doctrine\Common\EventArgs;
use Doctrine\Common\Persistence\Mapping\ClassMetadata;
use Doctrine\Common\Util\ClassUtils;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Gedmo\Mapping\MappedEventSubscriber;
use Doctrine\ODM\MongoDB\Proxy\Proxy;
use Gedmo\Sortable\Mapping\Event\SortableAdapter;
```

In that file, it works without problems.

I think you should consider use an adapter to handle UOW stuff

Thanks in advance.

**Comment by Rbn3D** [comment]
I'm using version v2.3.12

**Comment by l3pp4rd** [comment]
the sortable does not support odm

**Comment by rubenrua** [comment]
The sortable support ODM, this is the commit to enable it: https://github.com/Atlantic18/DoctrineExtensions/commit/3279ab7803e781f6e7ad0582b289d65e06f88325

Don't close this issue.
