### ISSUE TITLE
[question][timestampable] on change field, with exceptions

### ISSUE THREAD

**Issue by stickyhands** [Atlantic18/DoctrineExtensions#1281]
Hi,

I was wondering is there is a way to implement a timestampable field that is updated on change on my entity except for one field change.

This is my use case:

I have a Profile entity, In that entity I have several fields, but lets focus on 2 of them: 
'updatedAt' and 'lastActivity'

My lastActivity field is a datetime that I use to guess if the user is online right now (a Symfony Listener is in charge of it)

My updatedAt field is a Timestampable on update, classic, and it works great. I would like it to not update it if change happens only on a specific field (in my case lastActivity).

I know i could use a timestampable on change and list all my fields except lastActivity, but my entity is really huge :(

**Comment by l3pp4rd** [comment]
Hi, currently there isn't such option. you can extend timestampable listener and override metadata load event, to add all mapped fields except that one for the entity you need. should be really easy to do so, and use that listener instead.. your case is rarely used, so I do not want to introduce options which may not be needed in most cases, it is simple enough to extend it.

**Comment by stickyhands** [comment]
@l3pp4rd thank you for your answer,
if I make a pull request with that new feature would it be accepted? (considering clean code, tests pass, etc) or you really dont want to provide this possibility ?

**Comment by l3pp4rd** [comment]
@stickyhands no, it is a rare use case, I do not want to confuse people with a big number of options they mostly never need..

**Comment by l3pp4rd** [comment]
you could add another listener (after timestampable) and if timestamp was changed because of timestampable, you could reset the change back to previous value in your listener.
