### ISSUE TITLE
how to translate a field oneToMany

### ISSUE THREAD

**Issue by strauss69400** [Atlantic18/DoctrineExtensions#1291]
hi,

i created two entities : blog and block.
in my entities blog i add this relation : 
   /**
    * @ORM\OneToMany(targetEntity="Acme\BlogBundle\Entity\Block",mappedBy="blog", cascade={"remove"})
    * @ORM\OrderBy({"position" = "ASC"})
    * @Gedmo\Translatable
    */
   protected $blocks;

i run my page, i get this error : Unable to find translatable [blocks] as mapped property in entity.

to translate field like 'title', i dont' have proble but to translate a relation, i dont' know how to do.

thanks you very much

**Comment by l3pp4rd** [comment]
add cascade persist and persisted entity, if it is translatable, will be translated as all the others. the annotation won't even work for relations

**Comment by lukepass** [comment]
@AkenRoberts do you know how to make this work with Sonata Media Bundle and their Media entity? Thanks!

**Comment by AkenRoberts** [comment]
@lukepass I'm sorry, I'm not familiar with their media bundle or how you'd configure Extensions with it. 🙁
