### ISSUE TITLE
Sluggable + Translatable doc error

### ISSUE THREAD

**Issue by GonZOO82** [Atlantic18/DoctrineExtensions#1293]
[https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/sluggable.md#using-translationlistener-to-translate-our-slug](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/sluggable.md#using-translationlistener-to-translate-our-slug)

change this:
$translatableListener = new \Gedmo\Translatable\TranslationListener();
to:
$translatableListener = new \Gedmo\Translatable\TranslatableListener();

\Gedmo\Translatable\TranslationListener not valid

**Comment by l3pp4rd** [comment]
thanks ;)
