### ISSUE TITLE
How to configure it in Symfony2

### ISSUE THREAD

**Issue by BentCoder** [Atlantic18/DoctrineExtensions#1296]
Hi,

I'm trying to use `soft-delete` option of [gedmo/doctrine-extensions][1] but for some reason when I call `romove()`, the record in database gets removed instead of updating `deletedAt` field.

Where exactly configuration goes in config.yml?

> $config->addFilter('soft-deleteable', 'Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter');

**CONTROLLER**

    public function delete($id)
    {
        $profile = $this->profileRepository->findOneBy(['id' => $id]);

        if (!$profile instanceof Profile) {
            throw new ........
        }

        $this->entityManager->remove($profile);
        $this->entityManager->flush();

        return true;
    }

**ENTITY**

    use Gedmo\Mapping\Annotation as Gedmo;
    
    /**
     * @ORM\Entity()
     * @ORM\Table(name="profile")
     * @Gedmo\SoftDeleteable(fieldName="deletedAt")
     */
    class Profile
    {
        /**
         * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
         */
        private $deletedAt;
        ......
    }

**COMPOSER.JSON**

    "require": {
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "gedmo/doctrine-extensions": "2.3.*@dev",
        ......
    },

**CONFIG.YML**

    doctrine:
        dbal:
          default_connection: front
          connections:
            front:
              driver:   %database_driver%
              host:     %database_host%
              ........
            back:
              driver:   %database_driver%
              host:     %database_host%
              ........
    
    
        orm:
            auto_generate_proxy_classes: %kernel.debug%
            default_entity_manager:      front
    
            entity_managers:
                front:
                    connection:       front
                    mappings:
                        MyWebsiteBundle:
                            dir:      Entity
                        FOSUserBundle: ~
    
                back:
                    connection:       back

**Comment by Umair-Qadeer** [comment]
did you get your answer? I also don't know where 
"$config->addFilter('soft-deleteable', 'Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter');"
will go?
