### ISSUE TITLE
Could use Gedmo\Versioned (Loggable) without make new version at each setData() ?

### ISSUE THREAD

**Issue by FR33D0M5K135** [Atlantic18/DoctrineExtensions#1301]
Hi everyone !

I have a simple question ! Could we use Gedmo\Versioned (Loggable) without make new version at each setdata() ?

To be more expressive, I will give you an example: 
Let's imagine you have a report. You can edit it, you can Save it or Publish it. 
If you decide de save you modifications  no new version will be create and you modification will be save. But, if you publish a new version will be create  and you modification will be save.

Currently, in each case (Save, Publish) we have to use setData() function and so a new version will be create.

Do you know a solution ? Do you think is possible to use setData() without generate a new version ?
If not ! I think that could be a useful improvement. 

Thanks !

**Comment by l3pp4rd** [comment]
the only way to do so, would be to disable the listener, etc hook it of from entity manager. anyway, extensions are very generic, if you want to customize the behavior in such ways, extend it or modify it based on your needs.

**Comment by FR33D0M5K135** [comment]
Ok thanks for you response ! I got my solution thanks to you. I close is issue.
