### ISSUE TITLE
Embedded documents vs. translations

### ISSUE THREAD

**Issue by alcaeus** [Atlantic18/DoctrineExtensions#1304]
When translating fields in embedded documents in ODM, the entire handling is a bit cumbersome:

* The embedded document must have an ID - not optimal but understandable since the translation entity must somehow keep a reference to the embedded document.
* The locale must be stored at the embedded document, even if the owning document is translated and has a locale field
* To load a different translation, the embedded document must be refreshed directly.

**TL;DR**
Storing translations in embedded documents does not work reliably and will not work once the UnitOfWork refactoring in doctrine/mongodb-odm (doctrine/mongodb-odm#782) is finished. Furthermore, refreshing the parent for a specific locale does not reload embedded documents in that locale. Suggestion: allow TranslationListener to fetch locale not only from object but also from parent associations.

I'm writing this down here to make sure I'm not using this wrong (TM)

**The gory details along with some sample code:**

There is a parent document containing a EmbedMany association to a child document. Both the parent and the child are translated.

Parent:
```
/**
 * @ODM\Document(collection="translationParent")
 */
class TranslationParent
{
    /** @ODM\Id */
    public $id;

    /**
     * @ODM\String
     * @Gedmo\Translatable
     */
    public $title;

    /**
     * @ODM\String
     * @Gedmo\Translatable
     */
    public $description;

    /**
     * @Gedmo\Locale
     */
    public $locale;

    /**
     * @ODM\EmbedMany(targetDocument="TranslationChild")
     */
    public $children;

    public function __construct()
    {
        $this->children = new \Doctrine\Common\Collections\ArrayCollection();
    }
}
```

Child:
```
/**
 * @ODM\EmbeddedDocument
 */
class TranslationChild
{
    /** @ODM\Id */
    public $id;

    /**
     * @ODM\String
     * @Gedmo\Translatable
     */
    public $title;

    /**
     * @ODM\String
     * @Gedmo\Translatable
     */
    public $description;

    /**
     * @Gedmo\Locale
     */
    public $locale;
}
```

To create a new document and store translations:
```
$translationChild = new TranslationChild();
$translationChild->title = 'Child title';
$translationChild->description = 'Child description';
$translationChild->locale = 'en';

$translationParent = new TranslationParent();
$translationParent->title = 'Title';
$translationParent->description = 'Description';
$translationParent->locale = 'en';

$translationParent->children->add($translationChild);

$this->getDocumentManager()->persist($translationParent);
$this->getDocumentManager()->flush();
```

This works fine. However, let's say the English translation has been loaded and you want to load the German one:
```
$translationParent->locale = 'de';
$translationChild->locale = 'de';

$this->getDocumentManager()->refresh($translationParent);
```

This will only load the correct translation for the parent document. To actually refresh the embedded translations, you need to set the locale, then refresh each embedded document individually:
```
$translationParent->locale = 'de';
$this->getDocumentManager()->refresh($translationParent);
        
$translationChild->locale = 'de';
$this->getDocumentManager()->refresh($translationChild);
```

The reason is simple: when refreshing the parent document, the locale field of the embedded document is cleared (because the PersistentCollection holding the child is recreated), causing the postLoad handler to only find null in the locale field.

This becomes critical once doctrine/mongodb-odm#782 is merged. That PR no longer allows refreshing embedded documents, meaning that translations for embedded documents can no longer be retrieved.

**Comment by l3pp4rd** [comment]
hi, it sounds reasonable of course, odm is in overall cumbersome to use. currently I'm only maintaining extensions, haven't used it in a while. if there will be stability issues, will need to take some steps. but translatable is quite complex anyway for a better performance and handling custom solutions should be applied. for now, I'm only hoping that people, who use the extensions could contribute to prevent such issues as described

**Comment by alcaeus** [comment]
Thanks for your reply. I've created doctrine/mongodb-odm#1152 to help fixing this issue. Once that is merged we could change ```getTranslatableLocale()``` in ```TranslatableListener``` to traverse upwards for embedded documents and fetch the locale from any document above. I'll create a PR for that once I'm done playing with the changes.
