### ISSUE TITLE
Sluggable with non latin text (Arabic)

### ISSUE THREAD

**Issue by redayoub** [Atlantic18/DoctrineExtensions#1308]
Hello, I'm using the sluggable extension to generate slugs for arabic text. 

Is there any way if I enter this text for exmaple "مرحبا بالعالم" to get this "مرحبا-بالعالم" as slug instead of getting this "mrhb-bl-lm" ?

Thanks

**Comment by redayoub** [comment]
Help please

**Comment by l3pp4rd** [comment]
hi, sluggable transforms any UTF-8 text to ASCII it cannot and will not translate it to UTF-8. however, you may use custom transliterators and use whatever you wish to transform the text, but out of the box UTF-8 => ASCII

**Comment by redayoub** [comment]
It's ok, I've found a solution [here] (https://medrhamnia.wordpress.com/2014/07/04/symfony2doctrineextension-creer-des-slugs-pour-les-caracteres-non-latin-arabe-particulierement/#comment-90).

**Comment by l3pp4rd** [comment]
great, cheers
