### ISSUE TITLE
Translatable class causing errors with Doctrine2 entity generator.

### ISSUE THREAD

**Issue by GreeKatrina** [Atlantic18/DoctrineExtensions#1310]
I am trying to use the entity generator for Doctrine2. I use this command:
```
php bin/doctrine orm:generate-entities ../MyApp/Model/Entity --generate-annotations=true
```
When I run this, I get this error:
```
[Doctrine\Common\Annotations\AnnotationException]                                                                                                                               
  [Semantical Error] The annotation "@Doctrine\ORM\Mapping\MappedSuperclass" in class Gedmo\Translatable\Entity\MappedSuperclass\AbstractPersonalTranslation does not exist, or   
  could not be auto-loaded. 
```
I tried to see if my classes were not being autoloaded correctly, so in my `bootstrap.php` file I put `$x = new Doctrine\ORM\Mapping\MappedSuperclass();` just to see if it would throw an error. The weird part is that the command ran when I put that in there. However, what I found in my `/MyApp/Entity/` folder was this??
```
/
Gedmo/
    Loggable/
        Entity/
            MappedSuperclass/
                AbstractLogEntry.php
    Translatable/
        Entity/
            MappedSuperclass/
                AbstractPersonalTranslation.php
                AbstractTranslation.php
    Tree/
        Entity/
            MappedSuperclass/
                AbstractColsure.php
```
It copied Gedmo's source code for some reason? The frustrating part of this as well is that I'm only using the Timestampable class, so I'm not even sure why it's looking in the Translatable class.

Here's a folder structure (with missing folders) of my app, in case that might explain something.
```
/
MyApp/
    Controller/
    Model/
        Entity/
        Domain/
        Service/
    View/
static/
tests/
vendor/
    bin/
    composer/
    doctrine/
    Gedmo/
    symfony/
    autoload.php
    autoloader.php
    bootstrap.php
    cli-config.php
index.php
```
And finally, my `autoloader.php` file:
```php
<?php

spl_autoload_register(function ($class) {

    $vendorDir = dirname(__FILE__);

    $baseDir = dirname($vendorDir);

    $namespaces = include $vendorDir . '/composer/autoload_namespaces.php';
    $psr4 = include $vendorDir . '/composer/autoload_psr4.php';
    $classmap = include $vendorDir . '/composer/autoload_classmap.php';

    $custom_prefixes = [
        'MyApp\\' => [ $baseDir . '/MyApp/' ],
        'Gedmo\\' => [ $vendorDir . '/Gedmo/' ]
    ];

    $prefixes = array_merge($custom_prefixes, $namespaces, $psr4, $classmap);

    foreach ($prefixes as $prefix => $path) 
    {
        $len = strlen($prefix);
        if (strncmp($prefix, $class, $len) === 0) {
            // get the relative class name
            $relative_class = substr($class, $len);
            // replace the namespace prefix with the base directory, replace namespace
            // separators with directory separators in the relative class name, append
            // with .php
            foreach ($path as $p) {
                $file = $p . str_replace('\\', '/', $relative_class) . '.php';
                // if the file exists, require it
    	    	if (file_exists($file)) {
    	    	    require $file;
    	    	}
            }
	    }
    }
});
```

**Comment by l3pp4rd** [comment]
extensions cannot hook into the entity generator, you should bypass it and update some parts manually in that case..

**Comment by nueckman** [comment]
Same error for me. @l3pp4rd do you have more information ? Exception is thrown during any cli action (update, create, validate-schema, etc.).

**Comment by l3pp4rd** [comment]
Hi, so you have yml or xml mapping and attempt to generate entities?

**Comment by nueckman** [comment]
Nope, i'm using annotations and want to generate/update/validate the schema. After playing around I'm stucked with the exact same error you've already "discussed" on google groups (https://groups.google.com/forum/#!topic/symfony2/6gBqevBmPV8).

**Comment by l3pp4rd** [comment]
well, there is an [example](https://github.com/Atlantic18/DoctrineExtensions/blob/master/example/em.php) application, running schema:update does not trigger any error. What framework are you using and how doctrine is bootstrapped?

**Comment by GreeKatrina** [comment]
This was awhile ago, so I'm not 100% sure if this is how I found my solution. But I switched to using vendor, therefore namespaces are autoloaded by that. Then, I added this line in my bootstrap file:

```php
AnnotationRegistry::registerFile(__DIR__ . "/Gedmo/Timestampable/Mapping/Driver/Annotation.php");
```
Obviously change __DIR__ to where ever you need it to be. Let me know if that works for you.

**Comment by nueckman** [comment]
Thanks @GreeKatrina. Works like expected.

**Comment by l3pp4rd** [comment]
you could also try: `Gedmo\DoctrineExtensions::registerAnnotations();` which registers all available annotations for you.
