### ISSUE TITLE
Translatable and Class Table Inheritance

### ISSUE THREAD

**Issue by aderuwe** [Atlantic18/DoctrineExtensions#1313]
I seem to be having issues with Translatable and Class Table Inheritance ... I really hope I am simply doing something wrong.

I have the following base-class:

```php
/**
 * @Gedmo\TranslationEntity(class="Entity\Translation\Template")
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"mail" = "MailTemplate", "print" = "PrintTemplate"})
 * @ORM\Table(name="template")
 */
abstract class Template implements TranslatableInterface
{
    /**
     * @var string
     *
     * @Gedmo\Translatable
     * @ORM\Column(type="string", name="name")
     */
    private $name;

    /**
     * @var string
     *
     * @Gedmo\Translatable
     * @ORM\Column(type="text", name="description", nullable=true)
     */
    private $description;
}
```

And the following sub-class:

```php
/**
 * @Gedmo\TranslationEntity(class="Entity\Translation\MailTemplate")
 * @ORM\Entity
 * @ORM\Table(name="mail_template")
 */
class MailTemplate extends Template
{
    /**
     * @var string
     *
     * @Gedmo\Translatable
     * @ORM\Column(type="text", name="body", nullable=true)
     */
    private $body;
}
```

No matter what permutations of the `@Gedmo\TranslationEntity` annotation, it seems that only the translations for `Template` (name and description) are stored in template_translation - mail_template_translation remains empty (body never appears in any translation table).

I tried setting both classes to the same `@Gedmo\TranslationEntity`, but that still doesn't work.
Also tried having the `@Gedmo\TranslationEntity` annotation only on the sub-class, but that doesn't work either.

Help or pointers much appreciated!

**Comment by aderuwe** [comment]
Yup, was definitely doing something wrong.

Sorry about the noise.

**Comment by dmitryChernukh** [comment]
Hi @aderuwe. Please, can you describe how did you solve this issue?
we faced with same I suppose - https://github.com/Atlantic18/DoctrineExtensions/issues/1984
