### ISSUE TITLE
Translatable in different language but same value don't persist in db

### ISSUE THREAD

**Issue by Ronan-Lenor** [Atlantic18/DoctrineExtensions#1315]
Hello,

I have a problem when i want to persist the word 'service' in 'fr' (default locale) and then persist it again in 'en', it doesn't work. (yes, 'service' have the same writing in french & english lol)
when i check my database, there's no entry with 'service' in 'en'.

but it work if i write 'serrrrrrvice', so it's seem to not persisting when 2 value are same, no matter if locale is different.

by the way, i must use fallback:false for the website. so when i try to get my category 'service' in 'fr' it work. but the field is empty in 'en' (logic, because as there's no record in database and my fallback is false)

my question is, is there a way to force persistance in the database if there's a duplicate "value" and a different 'locale' ?

(i would prefer not use the "Personal translations" with "addTranslation" method, because i would loose the convenience of a simple caterogy->setTitle('service') )

Thanks

Edit 1:
i find the problem. It come from the fact that the method setTranslatableLocale() modify a parameter that is not handled by doctrine. so the Entity seem to been not changed and there's no trigger to update the Entity in the database.

now i have to find a solution to force the update without taking too much ressource. if you have many different suggestion, i'm listening :)

but that would be great if the doctrine extension could resolve this problem.

Edit 2:
i found a solution quiet good but not great. as i'm also using the extension "timestampable", i added this to the method:

public function setTranslatableLocale($locale)
{
    $this->locale = $locale;
    $this->updated = date_create(date('Y-m-d H:i:s', time()));
}

so it resolve the problem but sadly make Timestampable and Translatable dependant of each other...

**Comment by l3pp4rd** [comment]
yes, it does not persist, orm does not see it as a change. in that case you can use `$repository->translate(...)`

**Comment by Ronan-Lenor** [comment]
Well i tried your solution, sadly it lead to another problem.

Because if the field Title have a sluggable annotation, "$repo->translate($Category, 'title',...);" won't trigger the slug event.

i think that setTranslatableLocale should aware doctrine(in the UnitOfWork?) when a setter which is handle by the annotation "translatable" is trigged.

i'm not sure of how the UnitOfWork work(haha) but there's something about the trigger when doctrine have to update an entity or not, isn't it?

Anyway, i think that we can consider the problem as bug (as we don't get the excpeted result).

**Comment by goatherd** [comment]
This is basically a duplication of #1014.

**Comment by redjanym** [comment]
Hope this will help anyone still having the issue. 
I found a workaround for it. Before setting the translated value via $entity->translate('locale') method you first need to manually set and change the default locale of the entity before persisting it. 
Example:
```php
$entity->setDefaultLocale("en");
$entity->translate("en")->setTitle("English Title");

$entity->setDefaultLocale("sq");
$entity->translate("sq")->setTitle("Titull Shqip");

$entityManager->persist($entity);
$entity->mergeNewTranslations();
```

**Comment by AkenRoberts** [comment]
Thank you @redjanym. Closing as duplicated of #1014.
