### ISSUE TITLE
version 2.3.12 might be causing DEPRECATED logs in Symfony 2.7

### ISSUE THREAD

**Issue by ZCJ** [Atlantic18/DoctrineExtensions#1331]
DEPRECATED - The ability to pass file names to the Symfony\Component\Yaml\Yaml::parse method is deprecated since version 2.2 and will be removed in 3.0. Pass the YAML contents of the file instead.

**Comment by l3pp4rd** [comment]
thanks, indeed

**Comment by l3pp4rd** [comment]
right, it is ok in master, but all current tags are using old format. will push the maintenance release next week, cheers

**Comment by ZCJ** [comment]
Thanks
