### ISSUE TITLE
scheduleExtraUpdate does not exist in Doctrine\ODM\MongoDB\UnitOfWork

### ISSUE THREAD

**Issue by pomm0** [Atlantic18/DoctrineExtensions#1333]
I get the error 
```
Attempted to call method "scheduleExtraUpdate" on class "Doctrine\ODM\MongoDB\UnitOfWork"

gedmo/doctrine-extensions/lib/Gedmo/Loggable/LoggableListener.php - line 141
```

The method "scheduleExtraUpdate" used in
* lib/Gedmo/Tree/Strategy/ODM/MongoDB/MaterializedPath.php
* lib/Gedmo/SoftDeleteable/SoftDeleteableListener.php
* lib/Gedmo/Loggable/LoggableListener.php
* lib/Gedmo/Tree/Strategy/AbstractMaterializedPath.php

but it does not exist in Doctrine\ODM\MongoDB\UnitOfWork

**Comment by l3pp4rd** [comment]
what version of ODM?

**Comment by pomm0** [comment]
latest dev-master

**Comment by pomm0** [comment]
latest dev-master

**Comment by pomm0** [comment]
it seems that it has been deleted there: https://github.com/doctrine/mongodb-odm/compare/f9d26e2...master#diff-ae2c9f4b58c612dce08a0f60ff683aecL1538

**Comment by l3pp4rd** [comment]
well if you have time, you can try to submit a pull request with a fix. an alternative to schedule extra update.. not sure when I have time to look into it

**Comment by malarzm** [comment]
Is this possible to replace `scheduleExtraUpdate` with something different here in Extensions? Justification for removal was "this is marked as internal and we're not using it for some time"

**Comment by malarzm** [comment]
If I'm not mistaken the `scheduleExtraUpdate` was used to create reference between inserted item and its log, right? In ODM ids are assigned at the time of persist so there is no need to call `scheduleExtraUpdate` just to update the field, id could be passed to log entry upfront. Also [this](https://github.com/Atlantic18/DoctrineExtensions/blob/dedfbd7bd2ffb290ea19f3b1bbae52aa36c6008a/lib/Gedmo/Loggable/Document/MappedSuperclass/AbstractLogEntry.php#L36-L49) could be changed to use `@ReferenceOne()` without targetDocument specified which allows you to link anywhere, but I guess this is bigger change and is not feasible.

**Comment by l3pp4rd** [comment]
well, if someone is suffering from this one, you can open a PR? not sure when I will be able to submit a fix..

**Comment by malarzm** [comment]
Cross referencing with #1346

**Comment by phiamo** [comment]
@malarzm @l3pp4rd atm master of mongo-odm is not usable anymore with e.g. softdeletable behaviour ...

**Comment by malarzm** [comment]
@phiamo are you checking with DoctrineExtensions with #1346 merged?

**Comment by phiamo** [comment]
@malarzm i used a composer update.
i added gedmo/doctrine-extensions dev-master too and it works, before it was pulled in by stof/doctrine-extensions, which seemed to lead to a more stable version than master, without this fix.

**Comment by l3pp4rd** [comment]
ok, need to publish a tag, materialized path may have some issues, not sure whether it will work well with mongo

**Comment by l3pp4rd** [comment]
`composer update gedmo/doctrine-extensions`

**Comment by phiamo** [comment]
yeah works like a charm :-)
