### ISSUE TITLE
TranslationWalker don't translate in some case 

### ISSUE THREAD

**Issue by Ronan-Lenor** [Atlantic18/DoctrineExtensions#1334]
In the Class TranslationWalker, the method prepareTranslatedComponents() doesn't work correctly.
the line 327 
.' = '.$this->conn->quote($meta->name);
should be replace by
.' = '.$this->conn->quote($config['useObjectClass']);

Because if you have a "CompanyBundle" having a class "Category" which own the translationMappedSuperclass\AbstractTranslation with the Class "CategoryTranslation".

And then have a "ClientBundle" which extends the class Category with a class ClientCategory (owning relations with more ClientBundle:Entities...).
if form the ClientCategory Repository i want to build some stuff using the:

$query->setHint(
	\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
	'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
);

it will try to get the translation based on the entity name "ClientBundle\Entity\ClientCategory" and not "CompanyBundle\Entity\Category" as excpected in the field "object_class".

the result given is empty translated field (or the translated fallback).

this is why using $config['useObjectClass'] resolve this problem. As it give the real owner of the AbstractTranslation

**Comment by l3pp4rd** [comment]
hi, can you open a pull request referencing this issue?

**Comment by Ronan-Lenor** [comment]
Done.

https://github.com/Atlantic18/DoctrineExtensions/pull/1336

Hope it will be commited soon :P
