### ISSUE TITLE
[Sortable] Moving to last position with -1 causes gap

### ISSUE THREAD

**Issue by bennoz** [Atlantic18/DoctrineExtensions#1348]
Group | Name | Position
------- | ------- | -------
0 | Item 1 | 0
0 | Item 2 | 1
0 | Item 3 | 2

When moving `Item 1` to position `-1` it should be moved to the last position (`2`). But, the following table reflects the resulting positions.

Group | Name | Position
---------| ------- | -------
0 | Item 2 | 0
0 | Item 3 | 1
0 | Item 1 | **3**

Notice the position of `Item 1`: **3**.

Tested with:

Package | Version
----|-----
doctrine/orm                         | v2.4.7
gedmo/doctrine-extensions            | v2.3.12
stof/doctrine-extensions-bundle      | v1.1.0
symfony/symfony                      | v2.7.1

**Comment by l3pp4rd** [comment]
thanks for the details, not sure when someone may look into it ;)

**Comment by rubenrua** [comment]
I have fixed in pull request #1372.
