### ISSUE TITLE
Mapping/ExtensionMetadataFactory does not support Phpcr class metadata?

### ISSUE THREAD

**Issue by aramalipoor** [Atlantic18/DoctrineExtensions#1351]
I'm trying to use `referenceManyEmbed` type to reference many Image documents to a Product entity. XML below is part of ``Product.orm.xml`

``` xml
<field name="imageIds" column="image_ids" type="array" nullable="true"></field>
<gedmo:reference type="document"
   reference="referenceManyEmbed"
   field="imageIds" identifier="id"
   class="Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Image" />
```

When using Phpcr document manager error below raises on [Gedmo/Mapping/ExtensionMetadataFactory#86](https://github.com/Atlantic18/DoctrineExtensions/blob/3940af1099c47dd4bea036616730e8760a3fdba1/lib/Gedmo/Mapping/ExtensionMetadataFactory.php#L86-L89) since Phpcr's ClassMetadata does not provide such method:

```
FatalErrorException: Error: Call to undefined method
Doctrine\ODM\PHPCR\Mapping\ClassMetadata::isInheritanceTypeNone() in
vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/ExtensionMetadataFactory.php line 86
```

Is this a bug or am I missing something here?
I'm not sure how should I fix this if it really is a bug!?

**Comment by l3pp4rd** [comment]
well extensions were not intended for phpcr. if you are trying to adapt it, look if there is a common way to update the code to be compatible
