### ISSUE TITLE
Security context deprecated in Symfony 2.6

### ISSUE THREAD

**Issue by ArgiroPanagopoulou** [Atlantic18/DoctrineExtensions#1358]
Re factor code in DoctrineExtensionListener so as to be compatible with Symfony 2.6 security.authorization_checker.

**Comment by l3pp4rd** [comment]
I doubt that extensions depend on any symfony components except yaml reader.. what part do you mean about refactoring?

**Comment by shadypierre** [comment]
I think it's a mistake with this symfony2 bundle implementation https://github.com/stof/StofDoctrineExtensionsBundle

This issue should be closed.
