### ISSUE TITLE
[Reference_Integrity] Nullify and ReferenceMany.

### ISSUE THREAD

**Issue by Alsatian67** [Atlantic18/DoctrineExtensions#1360]
I have two documents Meeting and Guest (in Symfony).

```
class Meeting
{
    /** 
     * @MongoDB\ReferenceMany(targetDocument="Guest",inversedBy="meetings",simple=true)
     */
    private $guests;
}

class Guest
{
    /** 
    * @MongoDB\ReferenceMany(targetDocument="Meetings",mappedBy="guests",simple=true)
    * @Gedmo\ReferenceIntegrity("nullify")
    */
    private $meeting;
}
```

So for each Meeting I have an array of referenced guests.

-> When I remove a guest from the dB, I wish that it goes deleted from each meetings.

It is done but the full list of guests from each impacted meeting is setted to null.

Is it not possible to configure the listener so that it only remove the reference from the array instead of nullify the full array ?

**Comment by Alsatian67** [comment]
Easy to do with $pull :
http://docs.mongodb.org/manual/reference/operator/update/pull/

**Comment by l3pp4rd** [comment]
well I think that is not configurable, you could submit a PR to fix that..

**Comment by Alsatian67** [comment]
OK I will do it.
Should I add a third option [nullify,restrict,pull] ?
Or modify the nullify so that it only pulls the value ?

**Comment by l3pp4rd** [comment]
regarding option, what works better on your opinion
