### ISSUE TITLE
[References] Yaml driver missing

### ISSUE THREAD

**Issue by ahmed-hachena** [Atlantic18/DoctrineExtensions#1365]
This is the only extension without Yaml driver.

**Comment by l3pp4rd** [comment]
well, contributions are welcome if you need the yaml driver it is fairly simple to implement ;)

**Comment by ahmed-hachena** [comment]
alright then I will implement it as soon as possible.

**Comment by l3pp4rd** [comment]
that would be great, thanks ;)

**Comment by ahmed-hachena** [comment]
there is a pull request for this #1262
