### ISSUE TITLE
[Sluggable] Transactional integrity issue when running in concurrent environment

### ISSUE THREAD

**Issue by edhgoose** [Atlantic18/DoctrineExtensions#1368]
Hi there,

I seem to be having a problem related to Sluggable with concurrency and transactions. It may be my misunderstanding of how Doctrine works, but I'm not sure.

I currently have a process which takes some input information, generates an entity and then persists it inside a transaction. In the process of doing this, a sluggable is created for the entity.

Our sluggable is created from a provided firstname, surname, facebook id (if present, normally not) and a unique id which is just a number. We don't provide a value for uniqueId either. The annotation on our sluggable is:

    /**
     * @Gedmo\Slug(fields={"Firstname","Surname","FBUsername","UniqueId"}, updatable=false)
     * @ORM\Column(length=128, unique=true)
     */
    private $Slug;

This process runs on multiple machines concurrently, and I'm observing behaviour where integrity constraint violations occur when identical data is submitted and picked up by different processes.

I'm not entirely sure what exactly is happening and the reasoning for it, but it looks like the call to `generateSlug` is happening before a formal transaction starts.

1. Process A calls `onFlush`, which in turn calls `generateSlug`. `generateSlug` decides the entity should be called ed-goose-7.
2. Process B also calls `onFlush`, which because process A hasn't locked the database to execute the write also decides that the entity should be called ed-goose-7.
3. Process A starts a database transaction and ed-goose-7 is written to the database.
4. Process B starts a database transaction and ed-goose-7 fails to be written to the database because Process A has already written.

I'm not sure how best to produce a test case, but this produced identical behaviour for me:

0. Put a breakpoint on $this->generateSlug in the SluggableListener `onFlush` method.
1. Start a transaction in Doctrine.
2. Create a new entity which uses Sluggable.
3. Flush the entity. 
4. Step over generateSlug. Verify the value on `$object` of the Slug is a currently unique value and keep the code paused.
5. Simulate another task updating or inserting an entity with the same Slug. I manually updated an entity via MySQL.
6. Continue the code. Watch it fail.

Is this expected behaviour? Can the implementation of Sluggable use locking or something similar to prevent this issue occurring? Or is it expected that the developer (namely, me) implements the locking before calling flush?

Thanks!
Ed

**Comment by l3pp4rd** [comment]
Hi, yes you should handle locking for your self, extensions cannot know where the lock and how it should be applied for best performance. Sometimes it might be enough to select a relation entity for update within transaction, sometimes not.
It would not matter if transaction would be started sooner, it only runs select statements before. There is a locking problem in your case, there is always locking problem in extensions or php in overall. doctrine orm cannot restart transaction if for instance primary key allocation fails in concurrent environment for natural reasons. If you would work in highly concurrent environment, you would not use orm in the first place..

**Comment by edhgoose** [comment]
Thanks @l3pp4rd, that's the assumption I had come to but it is useful to have it validated.

We have a few possible solutions in our architecture (e.g. obtaining a lock earlier or removing the concurrency that is occurring).
