### ISSUE TITLE
Is it possible to use loggable with updateQueries in Document

### ISSUE THREAD

**Issue by tomcyr** [Atlantic18/DoctrineExtensions#1371]
Hi, 
when I'm saving documents by persist() and flush() methods Loggable listener works fine, but when I'm using QueryBuilder with:
```php
$qb
            ->update()
            ->multiple(true)
            ->field('id')->in($ids)
            ->field('status')->set($status)
```
loggable listener is not working. Is it an issue or not ??

**Comment by l3pp4rd** [comment]
it is not an issue, loggable cannot track these kind of queries, you would need to make manual entries in this case. loggable is a very basic behavior usually it does not fit into requirements

**Comment by tomcyr** [comment]
OK. Thanks for answer :)
