### ISSUE TITLE
[Translatable] PostgreSQL FK cast

### ISSUE THREAD

**Issue by iosipeld** [Atlantic18/DoctrineExtensions#1383]
Hello,

I had some problems with a personal translations and PostgreSQL in my Symfony project.

When I am using the ```Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker``` class, Doctrine throws an error, saying that I'am passing an integer parameter to the where clause (my FK are ints). The main part of the query, which cause the problem looks like this: ```...t1_.object_id = a0_.id::VARCHAR...```.

I found that in TranslationWalker there is an if statement on line 307:

```$castFK = ($this->platform instanceof PostgreSqlPlatform) ? '::VARCHAR' : '';```

Can I ask please, what is the meaning of this statement? When I comment that, all queries are OK.

Thanks!

**Comment by l3pp4rd** [comment]
yes, actually there is a casting done. so for postgresql either use a custom translation entity where you can overide the mapping to int instead of string. or use personal translations. the initial version was made to support mainly mysql.

**Comment by iosipeld** [comment]
Yes, I've already wrote, that I'm using personal translations.

I don't think, that overriding some part of the entity would solve the problem, because if statement depends on a platform:

``` $this->platform instanceof PostgreSqlPlatform ? '::VARCHAR' : '' ```

I cannot understand the meaning of this statement, because in the most cases FK are integers, not Varchar. Could this feature be configurable or somehow extendable?

Thanks!

**Comment by l3pp4rd** [comment]
well, it certainly would be best to have only integers and prevent casting at all. since this is not backward compatible, I would advice you to have a fork now with appropriate modifications. extensions will not change the behavior in future releases. so for the specific project that would be a good solution..

**Comment by l3pp4rd** [comment]
should be fixed in master

**Comment by iosipeld** [comment]
Thank you!
