### ISSUE TITLE
Translatable with having the whole entity translated

### ISSUE THREAD

**Issue by OndrejPiza** [Atlantic18/DoctrineExtensions#1384]
Hi,

I don't know if this is possible to achieve, but I need my document (MongoDB) be able to save translations as the whole entity. The better solution will be, if it will store translations in the nested document collection, but the logic to store it in the separate shared collection is OK. But not the storing it by property. I would like to apply versioning on translations separately from the main document as well and I don't think that this is achieveable with saving translations property by property.

I'm not so much familiar with mapping,I know just basics, so is it possbile to achieve the first scenario, I mean main document, containing nested documents with translations, which then could be versioned as standalone documents in another collection containing versions? 

Thank you for any advice or correction

**Comment by l3pp4rd** [comment]
hi, translatable translates only one field per document or entity. it is basic and also easy to use, but not performance wise. if you need a faster or custom solution, implement it. should not be that complex for odm. If translatable would translate whole entities it would need to track their fields and somehow update them, which is a complex task, a manual solution for such case would be recommended..

**Comment by OndrejPiza** [comment]
Hi,

thank you for reply. Now I understand.
