### ISSUE TITLE
[Timestampable] Allow define DateTimeInterval offset for Timestampable property

### ISSUE THREAD

**Issue by FlyingDR** [Atlantic18/DoctrineExtensions#1385]
It would be good to have an ability to define additional ```DateTimeInterval``` that would be added / subtracted from current ```DateTime``` on timestampable property. Real world case is creation of something that should be expired after certain amount of time, e.g. access tokens. Something like:
```php
    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable=false)
     * @Gedmo\Timestampable(on="create")
     */
    private $addedAt;
    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable=false)
     * @Gedmo\Timestampable(on="create", add="PT1H")
     */
    private $expiresAt;
```

**Comment by l3pp4rd** [comment]
extend timestampable, look at blameable or ip traceable if you want custom features. that is a rare use case and options for such behavior won't be added to timestampable, it is meant only for what it does now and it is already too much

**Comment by FlyingDR** [comment]
Ok, thank you for advice
