### ISSUE TITLE
Issue with default locale in TranslatableListener

### ISSUE THREAD

**Issue by jamesfade** [Atlantic18/DoctrineExtensions#1386]
I set the default locale to "zh" other than "en", and the translation fetch doesn't work. The content fetched from DB is in 'en', while I need them in 'zh'.

It seems that the problem is in the TranslatableListener.php

line 456:
if (isset($config['fields']) && ($locale !== $this->defaultLocale || $this->persistDefaultLocaleTranslation)) {
    // fetch translations
    ....
}

Analysis: 
$locale is got from object:
 $locale = $this->getTranslatableLocale($object, $meta);
It seems that it won't fetch translations if the $locale and $this->defaultLocale is same. 
However, I initialize the defaultLocale to 'zh', and the object->locale is 'zh' too, while the object->content is in 'en'.

So I make the !== to ===. I doesn't fully understand the $object, so correct me if I am wrong.

Thanks,
james

**Comment by l3pp4rd** [comment]
are the database queries cached? if so, probably you need to use a query hint to set the locale.

**Comment by jamesfade** [comment]
I reverted my changes to the original TranslatableListener.php
I build the whole contents based on 'en', so i should set the default_locale to 'en', $translatableListener->setDefaultLocale('en');
After that, I change the default locale of the website from 'en' to 'zh', and leave the default_locale of TranslatableListener as 'en'. It works fine.

I am new to this, so I am not sure how to set doctrine repository to fetch content in specific locale.
Thanks,
James
