### ISSUE TITLE
Get tree hiearchy using MaterializedPath returns array of arrays instead of array of Node objects

### ISSUE THREAD

**Issue by OndrejPiza** [Atlantic18/DoctrineExtensions#1390]
Hi,

I don't know is there is some wrong settings, but what I need is tree hiearchy returning array of nodes, but hydrated nodes, not associated arrays. I couldn't find any settings that cover this, so I guess the hydration should be by default. I'm also using StofDoctrineExtensions Bundle.

Am I missing something, some config settings or do I need to change some NestedTreeRepository method?

```
 * @ODM\Document(collection="acmeFolder",repositoryClass="ACME\MediaBundle\Repository\FolderRepository")
 * @ODM\HasLifecycleCallbacks
 * @Gedmo\Tree(type="materializedPath", activateLocking=true)
 */

......

    /**
     * @var Folder
     *
     * @ODM\ReferenceOne(targetDocument="Folder", name="parent")
     * @Gedmo\TreeParent
     */
    protected $parent;

    /**
     * @ODM\String(name="path")
     * @Gedmo\TreePath(separator="|")
     */
    private $path;

    /**
     * @Gedmo\TreeLockTime
     * @ODM\Date(name="lockTime")
     */
    private $lockTime;

...................

use Gedmo\Tree\Document\MongoDB\Repository\MaterializedPathRepository;

class FolderRepository extends MaterializedPathRepository

```

Thank you for any advice

**Comment by OndrejPiza** [comment]
Sorry guys, I've finally founded, it was harcoded in the method getNodesHierarchy

**Comment by OndrejPiza** [comment]
I have to reopen this issue, because after some testing and playing aroung with this, I cannot find out, how to create a tree hiearchy with objects. For some reason the method build tree can work properly only with array or nested arrays. So far good but I need to work with objects. Which is problem, because at some point your repository utils, line 142, is trying to access the node as an array and assign $item[$this->childrenIndex] = array();  but because the $item is object, it can't. 

Possible workaround could be implement ArrayAccess on Documents, but before that I have to ask, if this utility can really work only with arrays?

Thanks for any advice

**Comment by l3pp4rd** [comment]
objects are not supported so far, there was a feature request some time ago, it is quite hard to manage all relations like children lists
