### ISSUE TITLE
[Translatable] Question: Why is fallback not supported for scalar results?

### ISSUE THREAD

**Issue by stefankleff** [Atlantic18/DoctrineExtensions#1391]
I see no reason why COALESCE should not be used in scalar results. See here: https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Translatable/Query/TreeWalker/TranslationWalker.php#L369

Any idea why this was added?

**Comment by l3pp4rd** [comment]
well indeed, it could be added. are you willing to submit PR?
