### ISSUE TITLE
[Tree][Closure] Build the tree of existing entity with parent property/column

### ISSUE THREAD

**Issue by silasrm** [Atlantic18/DoctrineExtensions#1395]
Hi,

I've a entity User and this contain a property ```parent``` and this is quite similar to the structure that ClosureTree need:
- 1:admin (parent: null)
- 2:user1 (parent: 1)
- 3:user2 (parent: 1)
- 4:user3 (parent: 2)
- 5:user4 (parent: 4)

But now I need to make a real tree structure, and I'll use the ClosureTree type. 

I make the config, add annotations, add extra entity, everything is ok. But if I update the entity, the closure table continue empty. But if add a new User, the closure table is populated.

How to I build the closure table of existing users?

Thk's

**Comment by l3pp4rd** [comment]
hi, you would need to backup the users table or rename it, and run through inserts for all users in the needed parent - child structure..

**Comment by silasrm** [comment]
Hi,

I'll try this. But this is a bad solution :(

Many thank's. :D
