### ISSUE TITLE
[softdeleteable] Filter fails because of a "LEFT JOIN" in the inheritance.

### ISSUE THREAD

**Issue by Alsatian67** [Atlantic18/DoctrineExtensions#1396]
I have three entities related :
- UserRoot is the root of an inherited table and is SoftDeleteable
- UserType1 extends UserRoot
- Message is related to a UserType1

When I do this ***DQL*** request : 

```
SELECT m FROM AppBundle:Message m JOIN m.UserType1 u ORDER BY u.id
```

Doctrine create this ***SQL*** request :
```
SELECT * FROM Message a0_ INNER JOIN UserType1 a1_ ON a0_.usertype1_id = a1_.id LEFT JOIN UserRoot e2_ ON a1_.id = e2_.id AND (e2_.deletedate IS NULL) ORDER BY a1_.id ASC
```

-> Due to the ***LEFT JOIN***, It retrieves entities that are Softdeleteded ...

Entity Classes : 

```
<?php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Message
 *
 * @ORM\Table()
 * @ORM\Entity()
 */
class Message
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
    * @ORM\ManyToOne(targetEntity="AppBundle\Entity\UserType1", inversedBy="alertsartists")
    * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
    */
    private $artist;
}

<?php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use AppBundle\Entity\UserRoot;

/**
 * UserType1
 *
 * @ORM\Table
 * @ORM\Entity()
 */
class UserType1 extends UserRoot
{            
   /**
    * @ORM\OneToMany(targetEntity="AppBundle\Entity\Message",mappedBy="artist", fetch="EXTRA_LAZY")
    */
    private $alertsartists;
}

<?php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * UserRoot
 *
 * @ORM\Table
 * @ORM\Entity()
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="smallint")
 * @ORM\DiscriminatorMap({10 = "UserType1", 20 = "UserType2"})
 * @Gedmo\SoftDeleteable(fieldName="deletedate")
 */
class UserRoot
{    
    const NB_LIST = 15; 
    
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
    * @var \DateTime
    *
    * @ORM\Column(name="deletedate", type="datetime", nullable=true)
    */
    private $deletedate;
}
```

**Comment by Alsatian67** [comment]
SoftDeleteable Extension bug or Doctrine Filters Bug ?

**Comment by l3pp4rd** [comment]
well, not sure about it, looks like a bug in extensions.

**Comment by Alsatian67** [comment]
If I disable the softdeleteable filter and manualy do:

```
SELECT m FROM AppBundle:Message m JOIN m.UserType1 u WHERE u.deletedate IS NULL ORDER BY u.id
```

Doctrine create this ***SQL*** request :
```
SELECT * FROM Message a0_ INNER JOIN UserType1 a1_ ON a0_.usertype1_id = a1_.id LEFT JOIN UserRoot e2_ ON a1_.id = e2_.id ***WHERE*** e2_.deletedate IS NULL ORDER BY a1_.id ASC
```

And it works ...
So, the problem is not the ***LEFT JOIN*** but the argument in ***ON*** instead in ***WHERE***.

**Comment by Alsatian67** [comment]
I think the problem is in Doctrine, because in the addFilterConstraint we can't choose where the returned $addCondSql will be inserted in the SQL.

**Comment by l3pp4rd** [comment]
I see, thanks for the details. the [filter](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/SoftDeleteable/Filter/SoftDeleteableFilter.php) needs to be updated in some way to have it in where clause

**Comment by Alsatian67** [comment]
Are you sure the filter can be updated to do that ? Or Doctrine is inserting "e2.deletedate IS NULL" and we can't change the location of the insertion ?

**Comment by l3pp4rd** [comment]
well, I have looked at the code and it seems like.. with filters we cannot fix this, in that case I would just recommend to manage it manually, etc use where deletedAt is null in your select queries and disable the filter at all.

**Comment by Alsatian67** [comment]
OK. Thank you for your recommendation.

**Comment by Jalliuz** [comment]
There is a solution but only if all the **SoftDeletable logic is on the abstract base class**<br/>
Instead of this:
````
->leftJoin(y.theClass, 'x')
````
Use the classname
````
->leftJoin(TheClass::class, 'x', Expr\Join::WITH, 'y.theClass = x.id')
````

Then the abstract sub class holding the deletedAt field will automatically be inner joined in the correct way. And the SoftDeleteableFilter will do its work again.
