### ISSUE TITLE
Gedmo Timestampable and Blameable doesnt work after Merge Entity

### ISSUE THREAD

**Issue by kmehmety** [Atlantic18/DoctrineExtensions#1399]
I have two entities. Schemas like this:

         /*
            * @ORM\MappedSuperClass
            * @JMS\ExclusionPolicy("all")
         */

            abstract class BaseEntity {

            /**
             * @var string $createdBy
             *
             * @Gedmo\Blameable(on="create")
             * @ORM\Column(name="created_by", type="string", nullable=true)
             */
             protected $createdBy;
             /**
              * @var \DateTime $created
              * @Gedmo\Timestampable(on="create")
              * @ORM\Column(name="created_at", type="datetime", nullable=true)
              */
              protected $createdAt;

Other entity like this:

              /**
                * Survey
                *
                * @ORM\Table(name="answers")
                *@ORM\Entity(repositoryClass="AnswerRepository")
                 */
                 class Answer extends BaseEntity {

               /**
                 * @var integer
                 * @ORM\Column(name="id", type="integer")
                 * @ORM\Id
                 * @ORM\GeneratedValue(strategy="AUTO")
                 */
                 protected $id;

Question is:

                $data = $em->merge($datas);
                $em->persist($data);
                $em->flush();

After this process Gedmo Blameable, Timestampable doesn't work.

What should I do to make this work correctly?

**Comment by l3pp4rd** [comment]
yes, it is a known issue, probably need to document it somewhere. there are trade offs to this and backward compatibility issue. I would recommend to avoid merge in this case for extensions or use a fork with this [reverted diff](https://github.com/Atlantic18/DoctrineExtensions/commit/ddec6010fe5545daff71ebd95bc7f4fd91d9dc7e)
