### ISSUE TITLE
How to use the TreeListener in unit tests?

### ISSUE THREAD

**Issue by felicitus** [Atlantic18/DoctrineExtensions#1400]
Hi,

I'm using the tree in a sf2 project. Now I wanted to write unit tests, however, when attempting to write a fixture, the call to getRepository fails with the following message:

`Gedmo\Exception\InvalidMappingException: Tree listener was not found on your entity manager, it must be hooked into the event manager`.

How can I hook the listener into the event manager for unit testing? I haven't found any documentation for that within this repository.

**Comment by stof** [comment]
Well, register it when creating your entity manager in tests

**Comment by felicitus** [comment]
I don't create any entity manager in my tests. This seem to come from LiipFunctionalTestBundle, I guess?

**Comment by l3pp4rd** [comment]
try to understand what you are doing, what is entity manager, how it works, how listeners are attached and so on.. you should respect our time when asking these kind of questions.

**Comment by felicitus** [comment]
@l3pp4rd I know what an entity manager is, I know how it works and I know how listeners are attached in the Sf2 configuration. 

In my case, I'm using LiipFunctionalTestBundle which provides the service container, so it is most likely an issue with that bundle and not DoctrineExtensions.

**Comment by l3pp4rd** [comment]
my personal recommendation is to use less of bundles :)
