### ISSUE TITLE
Softdeleteable: can't use it with trait

### ISSUE THREAD

**Issue by KopiasCsaba** [Atlantic18/DoctrineExtensions#1404]
Hi!

Maybe it's a dump question, but i can't use trait with annotation for softdeleteable.
So if i put the @Gedmo\SoftDeleteable... annotation into the trait it will not work, but if i put it in the entity it works fine.

I don't know if it's a bug, a feature, or a technical limitation, but it would be nice to have it if it is possible.

Thanks!

**Comment by l3pp4rd** [comment]
with traits, all anotations must be set in the class which uses trait. traits do not import annotations, this is not related to extensions it is how php traits work

**Comment by KopiasCsaba** [comment]
Oh, thanks then!
