### ISSUE TITLE
Reference Integrity mappedBy field null

### ISSUE THREAD

**Issue by akd3vs** [Atlantic18/DoctrineExtensions#1412]
Is it supported that the mappendBy field is null?

When I try to remove a Document, it tries to pull out the reference of that Document from the parent (in my case the mappendBy field).

This is my Document:

```
     /**
     * @MongoDB\ReferenceOne(targetDocument="Intranet\CategoryBundle\Document\Mycategory", cascade={"persist"}, mappedBy="children")
     * @Gedmo\ReferenceIntegrity("pull")
     */
    protected $parent;

    /**
     * @MongoDB\ReferenceMany(name="children", targetDocument="Intranet\CategoryBundle\Document\Mycategory", cascade={"persist", "remove"}, inversedBy="parent", nullable=true)
     */
    protected $children;
```

If it is a bug, I'm interested in doing a PR.

Thank you.

**Comment by l3pp4rd** [comment]
the null should be supported, probably a bug. but please not the space after if and coding standards used. make it elseif instead, more readable. cheers

**Comment by akd3vs** [comment]
Is it ok now? Also, when would be published?

Thank you.

**Comment by l3pp4rd** [comment]
thanks, please open a PR, tag will be in a week
