### ISSUE TITLE
SortableRepository causes an error with order

### ISSUE THREAD

**Issue by melnikoved** [Atlantic18/DoctrineExtensions#1415]
Hi!
After updating, we had a problem with sortable extension. When we use querybuilder and write in select any aggregate function (for example select('COUNT(mqtt)') ) SortableRepository causes an error by adding orderBy.
CreateQueryBuilder was redefined in cb95546bdcad2a86b8f152784cc307084472b4b6 commit.

**Comment by l3pp4rd** [comment]
Hi, please submit a PR to revert the commit or fix the problem another way, I currently do not have time for extensions at all.
