### ISSUE TITLE
Build tree for fosRestBundle with JMS serializer

### ISSUE THREAD

**Issue by lucasgranberg** [Atlantic18/DoctrineExtensions#1417]
This is more of an idea than an issue. Is this a dumb way to do it / is there some built in method for building a tree out of entities rather than arrays?

I needed to build a tree of categories. I didn't want to use getArrayResult as described in the [docs](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/tree.md#generate-your-own-node-list) becouse then I loose serialization provider by the JMS serializer. I wrote my own buildTree method like this:

``` php
    public function buildCategoryTree($categories)
    {
        $nestedTree = array();
        if (count($categories) > 0) {
            // Node Stack. Used to help building the hierarchy
            $stack = array();
            foreach ($categories as $category) {
                $item = $category;
                // Number of stack items
                $l = count($stack);
                // Check if we're dealing with different levels
                while ($l > 0 && $stack[$l - 1]->getLvl() >= $item->getLvl()) {
                    array_pop($stack);
                    $l--;
                }
                // Stack is empty (we are inspecting the root)
                if ($l == 0) {
                    // Assigning the root child
                    $i = count($nestedTree);
                    $nestedTree[$i] = $item;
                    $stack[] = &$nestedTree[$i];
                } else {
                    // Add child to parent
                    $i = count($stack[$l - 1]->children);
                    $stack[$l - 1]->children[$i] = $item;
                    $stack[] = &$stack[$l - 1]->children[$i];
                }
            }
        }
        return $nestedTree;
    }
```

This requires the children variable to be public in the entity (I think) becouse it is accessed by reference. I also removed the ORM mapping so it wouldn't interfere.

**Comment by l3pp4rd** [comment]
I see, this has been requested many times, probably will need to have a look at some point, thanks for the details, cheers.
