### ISSUE TITLE
[SoftDeletable] How to deal with Entities referencing the softdeleted one?

### ISSUE THREAD

**Issue by mmeuser** [Atlantic18/DoctrineExtensions#1427]
What is the best way to deal with entities that maintain references to the softdeleted entities?
The filter makes the referenced softdeleted entity inaccessable. What is the best practice here?

**Comment by fsevestre** [comment]
I ask myself the same question as @mmeuser.
We have a REST API, and our only soft deletable entity has (for now) 5 levels of entities below it. But we can retrieve a "child" entity even if it ancestor is soft deleted.

How can we deal with this use case ?

**Comment by l3pp4rd** [comment]
cascade remove with all children as softdeleteables too. But I would advice to use something custom to manage relations. softdeleteable behavior is only good for cases when it does not involve relation management.

**Comment by fsevestre** [comment]
This is what I feared, I'll try your way.

Thanks

**Comment by mmeuser** [comment]
We found another suitable solution:
The SoftDeleteable Filter does not aply to EAGER fetching, therefore it is possible to load the softdeleted Entity through the reference if the relation is declared as fetch="EAGER". If you query for your Entity relation to a softdeleted one, the fetching will populate the reference correctly.

Another very explicit option is to disable the filter before querying and enabling it afterwards.

**Comment by fsevestre** [comment]
I tried eager fetching too, but we can only fetch one level parent (no cascade), which doesn't work for my use case with 5 levels of entities :(

I ended up with a cascade remove with softdelete on all my children entities (and will do a command to cascade undelete)

**Comment by datasage** [comment]
It appears, prior to doctrine 2.5, eager associations where were handled with separate queries. Doctrine 2.5 changed that into a join query. Unfortunately, this extension does not apply to correctly to eager joins.

**Comment by nathanmarcos** [comment]
I ask myself the same question as @mmeuser and @fsevestre too.

For my use case, I'd like to preserve the ordinary way, like when I wasn't using the soft delete without cascade remove. An exception should be triggered when try to soft delete and entity that is referenced by other one. Every entities are "soft deleteables" but, only when have no references, exactly when everything was hard deleted. 

Any idea to preserve that behavior with soft delete?

**Comment by Glideh** [comment]
I have this issue with forms containing a related deleted entity, generating an exception.
I know of no way to prevent it for now.

**Comment by embryologist** [comment]
is there a code example,
I have the same situation here, softDelete only works for sub-entities if I eagerly call remove for them?

**Comment by Quberik** [comment]
The problem regarding not only to SoftDeleteable, but to any other filters as well.

**Comment by fuser82** [comment]
Any solution?

**Comment by oojacoboo** [comment]
It'd be great to get some clarity around this.  As is, soft-delete is almost entirely useless.  Take the following example...

```php
$home = new Home();
$dog = new Dog()
$dog->setHome($home);

$em->persist($home);
$em->persist($dog);
$em->flush();

$em->remove($home); // Bad dog
$em->flush();

$em->refresh($dog);
$dog->getHome(); // Should be null - but still returns $home
```

**Comment by patrickdamery** [comment]
So here's a solution I came up with to selectively disable the softdeleteable filter for specific models at the Controller level using annotations.

First I created a custom annotation at /src/Annotations/IgnoreFilter.php
```
<?php
namespace App\Annotations;

/**
 * @Annotation
 * @Target({"METHOD", "CLASS", "PROPERTY"})
 * @Attributes({
 *  @Attribute("filter", type = "string"),
 *  @Attribute("forClasses",  type = "array"),
 * })
 */
class IgnoreFilter
{
    /** @Required */
    public $filter;

    /** @var array */
    public $forClasses = array();

}
```
Then created eventlistener at /src/EventListener/IgnoreFilterListener.php
```
<?php
namespace App\EventListener;
 
use App\Annotations\IgnoreFilter;
use Doctrine\Common\Annotations\Reader;
use Doctrine\ORM\EntityManagerInterface;
use Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter;
use ReflectionClass;
use ReflectionException;
use RuntimeException;
use Symfony\Component\HttpKernel\Event\{ControllerEvent};

class IgnoreFilterListener
{
    private $annotationReader;
    private $em;

    public function __construct(Reader $annotationReader, EntityManagerInterface $em)
    {
        $this->annotationReader = $annotationReader;
        $this->em = $em;
    }

    public function onKernelController(ControllerEvent $event): void
    {
        if (!$event->isMasterRequest()) {
            return;
        }

        $controllers = $event->getController();
            if (!is_array($controllers)) {
            return;
        }

        $this->handleAnnotation($controllers);
    }

    private function handleAnnotation(iterable $controllers): void
    {
        list($controller, $method) = $controllers;

        try {
            $controller = new ReflectionClass($controller);
        } catch (ReflectionException $e) {
            throw new RuntimeException('Failed to read annotation!');
        }

        $this->handleClassAnnotation($controller);
        $this->handleMethodAnnotation($controller, $method);
    }

    private function handleClassAnnotation(ReflectionClass $controller): void
    {
        $annotation = $this->annotationReader->getClassAnnotation($controller, IgnoreFilter::class);

        if ($annotation instanceof IgnoreFilter) {
            $filter = $this->em->getFilters()->enable($annotation->filter);
            if ($filter instanceof SoftDeleteableFilter) {
                foreach ($annotation->forClasses as $ignored_class) {
                    $filter->disableForEntity($ignored_class);
                }
            }
        }
    }

    private function handleMethodAnnotation(ReflectionClass $controller, string $method): void
    {
        $method = $controller->getMethod($method);
        $annotation = $this->annotationReader->getMethodAnnotation($method, IgnoreFilter::class);

        if ($annotation instanceof IgnoreFilter) {
            $filter = $this->em->getFilters()->enable($annotation->filter);
            if ($filter instanceof SoftDeleteableFilter) {
                foreach ($annotation->forClasses as $ignored_class) {
                    $filter->disableForEntity($ignored_class);
                }
            }
        }
    }
}
```
Then registered the event listener:

```
App\EventListener\IgnoreFilterListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
```

Now you can use the annotation in your controller or controller's methods (haven't worked out how to make this work on the entities yet):

```
   /**
     * @Route("s", methods={"GET"}, name="show_books")
     * @IgnoreFilter(filter="softdeleteable", forClasses={Author::class, Publisher::class})
     * @return JsonResponse
     */
```
This will allow you to load a list of books including those with a softdeleted author or publisher while excluding any books that are softdeleted.

**Comment by oojacoboo** [comment]
We look a little bit different approach.  We added the following method to a base repository class that all of our repositories extend.

```php
    /**
     * Disables the soft-deleteable filtering for a single callback, then re-enables.
     *
     * @note we use a callback to handle this so we're positive that it always gets re-enabled.
     *
     * @param callable $callback    Takes the parameter of the current repository
     * @param string $entityClass   Optional entity classname to only include archived for
     *
     * @return mixed
     */
    public function includeDeleted(callable $callback, ?string $entityClass = null)
    {
        if ($entityClass) {
            if (!\class_exists($entityClass)) {
                throw new Exception("Class {$entityClass} does not exist");
            }

            $this->getEntityManager()->getFilters()->getFilter('soft-deleteable')->disableForEntity($entityClass);
            $result = $callback($this);
            $this->getEntityManager()->getFilters()->getFilter('soft-deleteable')->enableForEntity($entityClass);

            return $result;
        }

        $this->getEntityManager()->getFilters()->disable('soft-deleteable');
        $result = $callback($this);
        $this->getEntityManager()->getFilters()->enable('soft-deleteable');

        return $result;
    }
```

Basically this will disable soft-delete for a specific repository method/call, optionally only on a specific entity as well.  We use a callback to ensure that it's always re-enabled without a developer forgetting.

Usage looks like:

```php
$id = 123;
$foo = $fooRepository->includeDeleted(fn ($repo) => $repo->findPk($id));
```

**Comment by AkenRoberts** [comment]
While SoftDeleteable was never intended to handle situations like this, I recognize that this use case is extremely common. I'm going to evaluate how we can possible improve DoctrineExtensions for this scenario, either by adjusting the SoftDeleteable API, or introducing a new similar extension.

Thank you all for sharing your work-around solutions. 🥂

**Comment by MinaZakaria** [comment]
Any update ?

**Comment by JoDarma-lp** [comment]
I am facing the same issue mentioned in this post, I am using Symfony 6.1 and API-PLATFORM.
After several unsuccessful attempts I come back here to find out if there has been anything new in the implementation of DoctrineExtension to solve this problem? (@AkenRoberts 👀 )

@patrickdamery  I would like to use your solution but I don't want to create custom controller (because in this case I have to make custom controller for all GET routes of all my entity) and I want to use custom annotation directly on entity (but it doesn't work) did you find a way to make it work on the entity?

**Comment by nicholas-semenda** [comment]
https://github.com/doctrine-extensions/DoctrineExtensions/issues/2506#issuecomment-1359286996

**Comment by Alderi-Tokori** [comment]
I'm having the same issue with an api platform project. Any update about this @AkenRoberts ?

**Comment by vince83110** [comment]
As a quick workaround, but care about side effets, using Api Platform, you can decorate the provider, for Api Platform 3, for example, using State Provider:

```
<?php

namespace App\State;

use ApiPlatform\Doctrine\Orm\State\CollectionProvider;
use ApiPlatform\Metadata\CollectionOperationInterface;
use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProviderInterface;
use Doctrine\ORM\EntityManagerInterface;

final readonly class CollectionIncludeDeletedProvider implements ProviderInterface
{
    public function __construct(
        private CollectionProvider $collectionProvider,
        private EntityManagerInterface $manager
    ) {
    }

    public function provide(Operation $operation, array $uriVariables = [], array $context = []): iterable
    {
        $isSoftDeletableEnabled = $this->manager->getFilters()->isEnabled('softdeleteable');
        if ($operation instanceof CollectionOperationInterface && true === $isSoftDeletableEnabled) {
            $this->manager->getFilters()->disable('softdeleteable');
            return $this->collectionProvider->provide($operation, $uriVariables, $context);
        }
    }
}

```

You can then use this provider in your GetCollection operation for each entity you need :

`new GetCollection(provider: CollectionIncludeDeletedProvider::class),`

It's a workaround

**Comment by dataconcept-it** [comment]
You can also do this in your Symfony Repository constructor:

```php
public function __construct(ManagerRegistry $registry)
{
        $filter = $registry->getManager()->getFilters()->enable('softdeleteable');
        $filter->disableForEntity(User::class);
        parent::__construct($registry, User::class);
}
```

The good thing is, you can even do this for relations of an entity like:

```php
public function __construct(ManagerRegistry $registry)
{
        $filter = $registry->getManager()->getFilters()->enable('softdeleteable');
        $filter->disableForEntity(UserTasks::class);
        parent::__construct($registry, User::class);
}
```

**Comment by oojacoboo** [comment]
@dataconcept-it this is risky.  That's a global disable for that Entity for the remainder of that process (or, if you're running an async server - forever).  You need to be employing ways to ensure it's always re-enabled to prevent side-effects.

The same issue with @vince83110.

This might work okay for you, until it doesn't.  It depends on your call-stack and process life-cycle.  Nonetheless, these are careless implementations.

I have provided a solution in my [comment](https://github.com/doctrine-extensions/DoctrineExtensions/issues/1427#issuecomment-628059026) above.  It's not the most beautiful API, but it's pretty good.  We also have a global function implementation of this, for cases where you're not using a repository.

**Comment by AkenRoberts** [comment]
@phansys I never did investigate a solution. Any thoughts here?

It's a really common use case even though I'd prefer developers choose a different hiding criteria than soft deletes.
