### ISSUE TITLE
[Sluggable] unique check after running TreeSlugHandler

### ISSUE THREAD

**Issue by vlcekmi3** [Atlantic18/DoctrineExtensions#1429]
Hi, is there any possibility to generate unique slug after the slug is handled by TreeSlugHandler?

Example:
I have two entitties
```
1. entity --> slug = "test"
2. entity --> slug = "entity_with_sub-entity"

3. entity (before persist) --> slug = "test"
```
and then i wanna persist 3rd entity, which is nested to 2nd entity (so resulted slug should be "test/xxx")

expected result: `3. entity --> slug = "entity_with_sub-entity/test"`
received result: `3. entity --> slug = "entity_with_sub-entity/test-1"` because unique slug is generated before TreeSlugHandler do anything

**Comment by lashae** [comment]
@vlcekmi3 I have the same issue. Since you had closed the issue, i suppose you fixed it. How did you manaage to fix?
