### ISSUE TITLE
how to update category_closure table if we have existing data ?

### ISSUE THREAD

**Issue by vishalmelmatti** [Atlantic18/DoctrineExtensions#1430]
Hi,
I have existing category hierarchy with parent_id column. I have configured Gedmo Tree extension and update schema. I can see 'level' column is added to category table and category_closure table is created.

How do I populate the data in category_closure table.  There are no 
    $repo->verify();
    $repo->recover();

methods for ClosureTreeRepository. I have tried updating category records so that to trigger TreeListener but still there is no data in category_closure.

How do I populate hierarchy in category_closure table ?

**Comment by l3pp4rd** [comment]
Hi,  you need to do that manually.

**Comment by vishalmelmatti** [comment]
Hi,

Thanks, schema for closure table is,

+------------+---------+------+-----+---------+----------------+
| Field      | Type    | Null | Key | Default | Extra          |
+------------+---------+------+-----+---------+----------------+
| id         | int(11) | NO   | PRI | NULL    | auto_increment |
| ancestor   | int(11) | NO   | MUL | NULL    |                |
| descendant | int(11) | NO   | MUL | NULL    |                |
| depth      | int(11) | NO   | MUL | NULL    |                |
+------------+---------+------+-----+---------+----------------+

What should be there in depth column ? Is there any example for this ?

**Comment by l3pp4rd** [comment]
no there isn't, insert few nodes and you will see what it creates..
