### ISSUE TITLE
ORA-01843: not valid month

### ISSUE THREAD

**Issue by jljunior3** [Atlantic18/DoctrineExtensions#1433]
Hi, 
I'm using ORM doctrine and SoftDelete feature.
But it is returned a date error in the updateas shown below.

How can I set another date format ?

DriverException in AbstractOracleDriver.php line 76:
An exception occurred while executing 'UPDATE cadastros SET deletedAt = ? WHERE id = ?' with params ["2015-10-20 11:43:59", 3]:

ORA-01843:
![a79a2af2-7710-11e5-84bb-86dac494c8f7](https://cloud.githubusercontent.com/assets/13906859/10647208/d9f9533c-7815-11e5-8e11-c7d64381c483.PNG)
 não é um mês válido

**Comment by stof** [comment]
date formatting is handled at the Doctrine level, not in extensions. Extensions are just passing a DateTime object to Doctrine

**Comment by jljunior3** [comment]
Do you know how I can format the date in doctrine?

**Comment by l3pp4rd** [comment]
It is a valid point @stof see [this](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/SoftDeleteable/Filter/SoftDeleteableFilter.php#L46) and [that](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/SoftDeleteable/Query/TreeWalker/SoftDeleteableWalker.php#L78)

**Comment by stof** [comment]
arf, we should be using the DBAL layer to format date here instead of hardcoding the format.

**Comment by jljunior3** [comment]
@stof how override this class ?

**Comment by jljunior3** [comment]
My database is oracle and is configures as "dd/mm/yyyy hh:mm:ss", 
I can not save any field date in database, doctrine force "yyyy-mm-dd hh:mm:ss"

**Comment by l3pp4rd** [comment]
if your database is not configured with custom date format, then maybe it is a bug in doctrine DBAL. try asking there http://www.doctrine-project.org/jira/browse/DBAL

**Comment by jljunior3** [comment]
i will see, thanks @l3pp4rd

**Comment by jljunior3** [comment]
Can anyone help me where I set this in laravel?

services:
    oracle.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect }
