### ISSUE TITLE
Only get translated records

### ISSUE THREAD

**Issue by picks44** [Atlantic18/DoctrineExtensions#1436]
Hello,
I have an Article entity which uses the Translatable extension.
My default locale is "en".
I have a user which translate Article records into the "fr_FR" locale", but not all of them, only the one which are relevant to its own universe.
When I'm trying to display the page which lists the Article records in the "fr" locale, I have a Twig error saying that the slug attribute is missing (which is normal because it has not been translated for all Article records, as said above).
How can I get round this ?

**Comment by l3pp4rd** [comment]
query translations with [inner join hint](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#using-inner-join-strategy) in that case it will fetch only translated in french records. Other options are to use fallback to EN hint without inner join.

**Comment by picks44** [comment]
OK thks. I'm using the [StofDoctrineExtensions Bundle](https://github.com/stof/StofDoctrineExtensionsBundle) in my project and my query now looks like 
```
public function findAllPublishedByCreatedOnDesc($defaultLocale, $locale)
    {
        return $this->createQueryBuilder('a')
            ->where('a.localeZone = :locale')
            ->setParameter('locale', $locale)
            ->orWhere('a.localeZone = :default')
            ->setParameter('default', $defaultLocale)
            ->andWhere('a.published = 1')
            ->orderBy('a.createdOn', 'desc')
            ->setFirstResult(0)
            ->setMaxResults(5)
            ->getQuery()
            ->setHint(\Gedmo\Translatable\TranslatableListener::HINT_INNER_JOIN, true)
            ->getResult()
            ;
    }
```
I still have my unstranslated articles.

**Comment by l3pp4rd** [comment]
you still need to set:

``` php
$query->setHint(
    \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
    'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
);
$query->setHint(
    \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
    'en' // take locale from session or request etc.
);
```

Look into documentation more carefully

**Comment by picks44** [comment]
Indeed. I'm not really used to Query Hint, but now it's fine ! 
Now I just need to figure out how to also display articles genuinely created with the fr_FR locale (localized articles).
