### ISSUE TITLE
Position set to -1 when element parent changes

### ISSUE THREAD

**Issue by sowbiba** [Atlantic18/DoctrineExtensions#1445]
Hello,
I found an issue during my application tests. It's look like the one reported here

https://github.com/Atlantic18/DoctrineExtensions/issues/1094

It's only happens when I move a child to a parent which has no children

Here is my structure

        ---> garage-1
                |
                 ---> car-1
                |
                 ---> car-2
        
        ---> garage-2
                |
                 ---> garage-3

__The entities__

*Car*

        use Doctrine\ORM\Mapping as ORM;
        use Gedmo\Mapping\Annotation as Gedmo;
                
        /**
         * @ORM\Table(name="car")
         * @ORM\Entity()
         */
        class Car
        {
            /**
             * @var int
             *
             * @ORM\Column(name="id", type="integer")
             * @ORM\Id
             * @ORM\GeneratedValue(strategy="AUTO")
             */
            protected $id;
        
            /**
             * @var string
             *
             * @ORM\Column(name="name", type="string", length=255)
             */
            protected $name;
        
            /**
             * @Gedmo\SortableGroup
             *
             * @var Garage
             *
             * @ORM\ManyToOne(targetEntity="Garage")
             * @ORM\JoinColumn(name="garage_id", referencedColumnName="id", nullable=true)
             */
            protected $parent;

            /**
             * @ORM\Column(name="position", type="integer")
             *
             * @Gedmo\SortablePosition
             */
            protected $position;

            ...
        }

*Garage*

        use Doctrine\Common\Collections\ArrayCollection;
        use Doctrine\ORM\Mapping as ORM;
        use Gedmo\Mapping\Annotation as Gedmo;
        
        /**
         * @ORM\Table(name="garage")
         * @ORM\Entity()
         *
         * @Gedmo\Tree(type="nested")
         */
        class Garage
        {
            /**
             * @var int
             *
             * @ORM\Column(name="id", type="integer")
             * @ORM\Id
             * @ORM\GeneratedValue(strategy="AUTO")
             */
            protected $id;

            /**
             * @var string
             *
             * @ORM\Column(name="name", type="string", length=255)
             */
            protected $name;

            /**
             * @Gedmo\TreeLeft
             * @ORM\Column(name="lft", type="integer")
             */
            protected $lft;

            /**
             * @Gedmo\TreeLevel
             * @ORM\Column(name="lvl", type="integer")
             */
            protected $lvl;
        
            /**
             * @Gedmo\TreeRight
             * @ORM\Column(name="rgt", type="integer")
             */
            protected $rgt;
        
            /**
             * @Gedmo\TreeRoot
             * @ORM\Column(name="root", type="integer", nullable=true)
             */
            protected $root;
        
            /**
             * @Gedmo\TreeParent
             *
             * @ORM\ManyToOne(targetEntity="Garage", inversedBy="children")
             * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE")
             */
            private $parent;
        
            /**
             * @ORM\OneToMany(targetEntity="Garage", mappedBy="parent")
             * @ORM\OrderBy({"lft" = "ASC"})
             */
            private $children;
        
            /**
             * @var ArrayCollection
             *
             * @ORM\OneToMany(targetEntity="Car", mappedBy="parent", cascade={"persist", "remove"})
             *
             * @ORM\OrderBy({"position"="ASC"})
             */
            private $cars;
        
           ...
        }

And here is the test

__Fixture__

        AppBundle\Entity\Garage:
            garage-1:
                id: 1
                name: 'Garage 1'
            garage-2:
                id: 2
                name: 'Garage 2'
            garage-3:
                id: 3
                name: 'Garage 3'
                parent: @garage-2

        AppBundle\Entity\Car:
            car-1:
                id: 1
                name: 'Car 1'
                parent: @garage-1
            car-2:
                id: 2
                name: 'Car 2'
                parent: @garage-1

__Test__

        public function testChangeParent()
        {
                $this->loadFixtures([
                    'AppBundle\Tests\Fixtures\CommonFixtures',
                ], null, 'doctrine', null);

                /**
                 * @var Garage $garage3
                 */
                $garage3 = $this->getEntityManager()->getRepository('AppBundle:Garage')->find(3);
        
                /**
                 * @var Car $car
                 */
                $car = $this->getEntityManager()->getRepository('AppBundle:Car')->find(2);
        
                $car->setParent($garage3);
                $car->setPosition(0);
        
                $this->getEntityManager()->flush($car);
        
                /**
                 * @var Car $car
                 */
                $car = $this->getEntityManager()->getRepository('AppBundle:Car')->findOneBy(['id' => $car->getId()]);

                var_dump($car->getPosition());
        }

**Comment by l3pp4rd** [comment]
Hi, thanks for all the details. sadly I do not have much time to dig into extensions, hope to find some. If it is a critical bug, you could try to develop a test case and submit a pull request.
