### ISSUE TITLE
Sortable feature: only relocate until gap

### ISSUE THREAD

**Issue by luksurious** [Atlantic18/DoctrineExtensions#1450]
For the sortable extension I have a feature request:

Assuming you have entities sorted by position with varying gaps between some numbers, e.g. 1, 2, 3, 10, 11, 20, etc.

If I add a new entity at position 4, I would like the rest of the positioning to not change.
If I add a new entity at position 3, however, the old 3 should move to 4, but the rest should stay the same.

Would also appreciate hints where to look at for trying to implement this myself.

**Comment by l3pp4rd** [comment]
hi, the author of sortable is not available recently, so the project is at feature freeze. if you need it working differently, fork or copy and update source to your needs, try and see when editing, you can use tests for that.

**Comment by l3pp4rd** [comment]
in general I doubt that this feature can be implemented without introducing much of complexity in sortable. anyway, if you want that kind of behavior you will need to hook another listener or extend the current to modify the behavior.
