### ISSUE TITLE
[SoftDeleteable] and unique fields problem.

### ISSUE THREAD

**Issue by Soimil** [Atlantic18/DoctrineExtensions#1452]
Hi, I have a problem with softDeleteable.
I have a table where unique field is "name".
If you delete the record where I have a name, for example - London and in form again type the same name - the London to not bereave me a message with the given name already exists but crashes error:

>SQLSTATE [23000]: Integrity constraint violation: 1062: Duplicate entry 'London' for key 'UNIQ_140AB6205E237E06'

And I want to be showed with the name is already in the database.

Please help because I fight with it for a few days to no avail.

**Comment by l3pp4rd** [comment]
you should solve it on your side, when persisting new entity and checking for uniqueness, disable softdeleteable filter or hard delete softdeleted entity. extension cannot know what exactly you would want to do in this case. sometimes it is more convenient to manage softdeleting manually or even restricting deleting at all.

**Comment by Soimil** [comment]
On how to do it but maybe some examples. I am a beginner in this field.

**Comment by l3pp4rd** [comment]
sorry for the late reply, but enabling and disabling of filters is explained in [softdeleteable documentation](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/softdeleteable.md#setup-and-autoloading)
