### ISSUE TITLE
html tree Customize output

### ISSUE THREAD

**Issue by ebcamps** [Atlantic18/DoctrineExtensions#1456]
When html tree Customize output in $ options = array (
     $ options = array (
     'decorate' => true,
     'rootOpen' => '<ul>',
     'rootClose' => '</ ul>',
     'childOpen' => '<li ---> here that this li id is the id in the database node>',
     'childClose' => '</ li>',
     }
);
I need time to create the $ option to pass it to the <li> have the id that has the node in the database as I do ??

**Comment by l3pp4rd** [comment]
tree provides everything you need to build custom html, look at the repository method used, copy it and customize in your service or repository based on your needs.,
