### ISSUE TITLE
Customize html tree

### ISSUE THREAD

**Issue by ebcamps** [Atlantic18/DoctrineExtensions#1457]
When html tree Customize output in $ options = array (
     $ options = array (
     'decorate' => true,
     'rootOpen' => '<ul>',
     'rootClose' => '- </ ul>',
     'childOpen' => '- <li ---> here that this li id is the id in the database node>',
     'childClose' => '</ li>',
     }
);
I need time to create the $ option to pass it to the <li> have the id that has the node in the database as I do ??
Necesito a la hora de crear el $option para pasarselo que los <li> tengan el id que tiene el nodo en la base de datos como puedo hacerlo??

**Comment by l3pp4rd** [comment]
it provides everything you need to build a custom html tree, see what the method is doing and replicate in a customized on your needs repository method or service.
