### ISSUE TITLE
[Sortable] Are there any way to sort by more than one sortable group?

### ISSUE THREAD

**Issue by xserrat** [Atlantic18/DoctrineExtensions#1459]
Hi,

I'm trying to sort an entity by more than one column (or sortableGroup), and I would know the correct way to specify at the very beginning what is the order for entity before insert. Should I use discriminator field?

Thanks,

**Comment by l3pp4rd** [comment]
hi, currently sortable supports only one field for position. you should do something custom in that case

**Comment by l3pp4rd** [comment]
can be closed, will be supported in 3.0.0 and is available in master
