### ISSUE TITLE
[Sortable] Wrong position when changing group but keeping the same position

### ISSUE THREAD

**Issue by fsevestre** [Atlantic18/DoctrineExtensions#1462]
Hi guys,

We are having an issue with the position of an item in this case: (important thing, we manage the position of items by `drag and drop` and the database `update` is done after each `drop`)

Initial state:
* Category 1
  * Item 1 (position 0)
  * Item 2 (position 1)
* Category 2
  * Item 3 (position 0)

We change the category of our Item 3 (position 0) to the position 0 of Category 1 (so, no position changes: only group changes):
* Category 1
  * Item 3 (position 0)
  * Item 1 (position 1)
  * Item 2 (position 2)
* Category 2

We refresh the page / check in database
* Category 1
  * Item 1 (position 0)
  * Item 2 (position 1)
  * Item 3 (position 2)
* Category 2

This issue is caused by the re-calculation of the position when the group is changed (but not the position):
https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Sortable/SortableListener.php#L282
https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Sortable/SortableListener.php#L297

I'm working on a fix atm

**Comment by fsevestre** [comment]
A test is covering this issue, but I don't understand why the item position is set in last position.
See: https://github.com/Atlantic18/DoctrineExtensions/blame/51360a4c289045a2713b68d0b97fb19a4a8dd2c7/tests/Gedmo/Sortable/SortableTest.php#L542

@l3pp4rd Is it a wanted behavior ?
The result seems strange to me. (even more when the position and the group are managed by an user in drag and drop)

**Comment by l3pp4rd** [comment]
Hi, indeed, it does not make sense. I currently do not work with extensions. If that is a big concern, you could consider to contribute a patch ;)
