### ISSUE TITLE
Error when upgrading to 2.4.8

### ISSUE THREAD

**Issue by kliko** [Atlantic18/DoctrineExtensions#1464]
When i upgrade to version 2.4.8 i get the follwing error:

PHP Catchable fatal error:  Argument 1 passed to Gedmo\AbstractTrackingListener::loadClassMetadata() must be an instance of Doctrine\Common\Persistence\Event\LoadClassMetadataEventArgs, instance of Doctrine\ORM\Event\LoadClassMetadataEventArgs given, called in /var/www/project/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php on line 63 and defined in /var/www/project/vendor/gedmo/doctrine-extensions/lib/Gedmo/AbstractTrackingListener.php on line 43

Symfony version: v2.3.35

**Comment by l3pp4rd** [comment]
will probably have a look tomorrow, this one is important

**Comment by Zorpen** [comment]
Same issue here. Any fix?

**Comment by stof** [comment]
I think you need to use a newer version of the Doctrine ORM

**Comment by l3pp4rd** [comment]
will be fixed and tagged, this was introduced. older versions should be supported
