### ISSUE TITLE
Issue with materialized path

### ISSUE THREAD

**Issue by drola** [Atlantic18/DoctrineExtensions#1467]
Function [buildTreeArray](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/RepositoryUtils.php#L130)expects that $nodes are sorted by path. However at least on PostgreSQL 9.4.5 result from a query sorted by path might be exactly what one would expect as shown on the screenshot below.
![izbor_008](https://cloud.githubusercontent.com/assets/1074328/11454969/f3631428-9644-11e5-94eb-fbb7c280910c.jpg)

The consequence is that buildTreeArray($nodes) puts `dir 1/R1/` and `dir 1/R4/` under `dir 1 copy/` which is clearly wrong. I think that assumptions about order of `$nodes` are too strong in the current version of `buildTreeArray()` which results in messed up trees on some DB engines. 

I propose we sort nodes in [`MaterializedPathRepository::getNodesHierarchy()`](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Entity/Repository/MaterializedPathRepository.php#L193) in PHP.

**Comment by l3pp4rd** [comment]
well yes, we can do that. can you submit a PR?
