### ISSUE TITLE
[Translatable] Won't deliver translation for entities linked by @ManyToOne

### ISSUE THREAD

**Issue by AntoineViau** [Atlantic18/DoctrineExtensions#1473]
Hello,

Say you have an entity Category :  

    class Category 
    {
        /**
         * @Gedmo\Translatable
         */
        private $categoryName;
    }

And an entity Module.  
Each Module belongs to one Category : 

    class Module 
    {
        /**
         * @Gedmo\Translatable
         */
        private $moduleName;

        /**
         * @ManyToOne(targetEntity="Module")
         */
        private $category;
    }

Using the query hint I can get a Module translated to a specific locale : 

    function getModule($id, $locale) 
    {
        $query = $em->createQuery('select m from AppBundle\Entity\Module m where m.id=' . $id);
        $query->setHint(TranslatableListener::HINT_TRANSLATABLE_LOCALE, $locale);
        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );
        $module = $query->getSingleResult();
        return $module;
    }

Testing : 

    $module = getModule(1234, 'en');
    // SUCCEED
    $this->assertEquals('module name in english', $module->getModuleName();
    $category = $module->getCategory();
    // FAIL !
    $this->assertEquals('category name in english', $category->getModuleName();
    // SUCCEED (but one more request)
    $category->setTranslatableLocale('en');
    $em->refresh($category);
    $this->assertEquals('category name in english', $category->getModuleName();

In few words : the query hint is able to insert a JOIN to the SELECT statement for the Module entity.
Call to $module->getCategory() will trigger lazy loading. But this time, there will be no translation JOINed.
Meaning I have to explicitly ask for the english version of the category.

Question : is it possible to have associated entities translated when querying the owner entity ? (having the FAILed test to succeed)  

I already tried eager fetching on the ManyToOne association. Won't work because I am querying through DQL.

**Comment by l3pp4rd** [comment]
join the category inside the query, now it does lazy fetch, and note the sql injection through your parameters in query

**Comment by AntoineViau** [comment]
Thanks for the tip, it works !
But in a perfect world I would love to have a generic code like this one : 

    protected function getEntityById($className, $id, $locale = null)
    {
        $dql = 'select e from AppBundle\Entity\\' . $className . ' e where e.id=' . $id;
        $query = $this->em->createQuery($dql);
        $query->setHint(
            \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
            $locale
        );
        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );
        $entity = $query->getSingleResult();
        return $entity;
    }

How to update this piece of code to have the associated entities to be loaded with the correct locale ?

**Comment by l3pp4rd** [comment]
make it a common repository method trait or something.. it is possible in many ways to abstract it.

**Comment by Alsciende** [comment]
Could it be possible to give an example of how to solve this problem in that simple Module/Category test case? I have the same issue, but in my case I'm already joining the association inside the query.

```
$qb = $this->doctrine->getRepository('AppBundle:Card')->createQueryBuilder('c');
$qb->leftJoin('c.type', 't');
$query = $qb->getQuery();
$query->setHint(
    \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
    'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
);
$query->setHint(
	\Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
	$locale
);
$query->setHint(
	\Gedmo\Translatable\TranslatableListener::HINT_FALLBACK, 
	1
);
$rows = $query->getResult();
$card = $rows[0];
$card->getText(); // translated
$card->getType()->getName(); // not translated
```

**Comment by l3pp4rd** [comment]
you can make a repository or static method:

``` php
<?php

public translate(QueryBuilder $qb, $locale)
{
$query = $qb->getQuery();
$query->setHint(
    \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
    'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
);
$query->setHint(
    \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
    $locale
);
$query->setHint(
    \Gedmo\Translatable\TranslatableListener::HINT_FALLBACK, 
    1
);
return $query;
}
```

**Comment by Alsciende** [comment]
It's worth noting that the association must be joined **and** selected, if the query is build with the QueryBuilder. Simply having the association in the joined entities is not enough.

**Comment by l3pp4rd** [comment]
you can create any query builder and pass it to the method to only apply the query hint and return the query ready to execute. Or am I missing something?

**Comment by Alsciende** [comment]
If I use the QueryBuilder but I only `select` my primary entity, then the associated entities are not translated.

```
$qb = $this->em->getRepository('AppBundle:Card')->createQueryBuilder('c');
$qb->leftJoin('c.type', 't');
$query = $qb->getQuery();
$query->setHint(
    \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
    'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
);
$query->setHint(
	\Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
	$locale
);
$rows = $query->getResult();
$card = $rows[0];
$card->getName(); // translated
$card->getType()->getName(); // not translated, although Type is joined inside the query
```

But if I select the associated entity, it works

```
$qb = $this->em->getRepository('AppBundle:Card')->createQueryBuilder('c');
$qb->select('c', 't');
$qb->leftJoin('c.type', 't');
$query = $qb->getQuery();
$query->setHint(
    \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
    'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
);
$query->setHint(
	\Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
	$locale
);
$rows = $query->getResult();
$card = $rows[0];
$card->getName(); // translated
$card->getType()->getName(); // translated
```

**Comment by l3pp4rd** [comment]
ah, if you do not select it with query, ORM does lazy load the entities which where not in select. In that case you should always set the active **locale** in listener: `$translatableListener->setTranslatableLocale($locale);` and it will translate lazy loaded entities. You can set this locale on every request hook, like in symfony2 there is onKernelRequest event and etc..

**Comment by Alsciende** [comment]
Ok, thank you!
