### ISSUE TITLE
softdeleteable   is not working properly

### ISSUE THREAD

**Issue by videni** [Atlantic18/DoctrineExtensions#1476]
I already have a card entity in database, which has been marked soft deleted, but when I try to  make it undeleted, I find  no matter what I do , the deleted_at field is simply not changed , anybody knows why?

```
    $this->entityManager->getFilters()->disable('softdeleteable');   

    /**
     * @var  $card Card
     */
    $card = $this->entityManager->getRepository('ToukeEtcBundle:Card')->findOneBy(array(
        'no' => $contractRequestMessage->getEtcCardNo(),
    ));


    $card->setDeletedAt(null);
    $card->setCardNo(9999);
    $this->entityManager->persist($card);
    $this->entityManager->flush();

    $this->entityManager->getFilters()->enable('softdeleteable'); 

    $this->entityManager->refresh($card);
    var_dump($card->getDeletedAt());  // still has data
  var_dump($card->getCardNo());  // return 9999
```

these code above will generate these sql statements:

[2015-12-04 21:25:02] doctrine.DEBUG: "START TRANSACTION" [] []
[2015-12-04 21:25:02] doctrine.DEBUG: UPDATE etc_card SET card_no = ? WHERE id = ? ["9999",1] []
[2015-12-04 21:25:02] doctrine.DEBUG: "COMMIT" [] 

as you can see , the deleted_at field is ignored.  there must be something wrong with the softdeleteable filter

**Comment by l3pp4rd** [comment]
are you sure the filter is named **softdeleteable**?

**Comment by videni** [comment]
Yep , I name it here

~~~
orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
              softdeleteable:
                  class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                  enabled: true
~~~

**Comment by videni** [comment]
@l3pp4rd, the name of the filter has to be softdeleteable in my case , because I can get the the deleted card only when I disable the filter first.

**Comment by videni** [comment]
@l3pp4rd,  I am very need to figure out why it doesn't work , can you point me the right way to debug, thanks a lot.

**Comment by l3pp4rd** [comment]
you can disable listener instead, or look why it does not work, by debugging orm internals. maybe it stopped working this way. I do not have time to help. you always have to maintain all third parties you are using in your project

**Comment by l3pp4rd** [comment]
have you solved the issue? looks weird on the second look, was the setter good?

**Comment by videni** [comment]
@l3pp4rd , nope,  it might be related to socket , I am using symfony2 together with socket, right now I can  solve this problem  temporarily   using DBAL way to set deleted_at as null.

```
            $connection = $this->entityManager->getConnection();
            $statement = $connection->prepare("update touke_etc_card set deleted_at=null where id=:cardId");
            $statement->bindValue('cardId', $card->getId());
            $statement->execute();
```

**Comment by l3pp4rd** [comment]
thanks for the details, will need to have another look, just in case if listener is involved in resetting this value
