### ISSUE TITLE
[Sluggable] Transliteration and Urlize reduce slug to empty string, which causes long queries or ugly slugs

### ISSUE THREAD

**Issue by edhgoose** [Atlantic18/DoctrineExtensions#1478]
Hi,

We're using Sluggable to generate URLs for people's names. Bob Smith becomes bob-smith for instance.

We're finding that some of the names that get fed to us are being run through urlize and transliteration and coming out as empty slugs. An example that comes up occasionally for instance is people putting in their names as "????" or as unicode.

When urlize and transliteration run in SluggableListener the slug gets turned into "" (the empty string).

This in turn, because we're using the 'unique' option, turns the query executed by `getSimilarSlugs` in SluggableAdapter to run a query like:

    SELECT Slug FROM user WHERE Slug LIKE "%"

We have 4.5million users at the moment, so this query takes an astronomical amount of time!

There are a couple of obvious solutions, like adding a unique field into the slug (so Bob Smith becomes bob-smith-1234), but that results in slightly less nice urls for our customers. We're looking for the more complicated solution :)

We're looking to see if we can extend/change the implementation of Sluggable to only add the uniqueness just before the `getSimilarSlugs`? Is there a way we can modify this functionality without having to: a) rewrite everything or b) compromise on our irrational requirements?

My first thought was there might be a way to just overwrite that function (`getSimilarSlugs`) but it, and other entry points that I thought made sense are private.

My one thought so far is to add a handler that implements the urlize and transliteration steps that currently exist, but that feels like a bit of a fudge (because the transliteration step then runs twice). Is there something I'm missing in how I might extend Sluggable? Or some work I can assist in to make it easy to extend?

Thanks hugely for any advice in advance and apologies for being difficult!

Kind Regards,
Ed

**Comment by edhgoose** [comment]
I think I've solved this, but I guess I thought it was a pretty hacky solution:

Firstly, I've created a Handler that runs at the last possible point, just before the transliteration and urlization.

````php
<?php

namespace Nora\ProjectBundle\Utility\Sluggable;

use Doctrine\Common\Persistence\Mapping\ClassMetadata;
use Doctrine\Common\Persistence\ObjectManager;
use Gedmo\Sluggable\Handler\SlugHandlerInterface;
use Gedmo\Sluggable\Mapping\Event\SluggableAdapter;
use Gedmo\Sluggable\SluggableListener;
use Gedmo\Sluggable\Util\Urlizer;
use Nora\CommonBundle\Utility\StringUtils;

class NotEmptySluggableHandler implements SlugHandlerInterface
{
    /**
     * @var ObjectManager
     */
    protected $om;

    /**
     * @var SluggableListener
     */
    protected $sluggable;

    /**
     * {@inheritDoc}
     */
    public function __construct(SluggableListener $sluggable)
    {
        $this->sluggable = $sluggable;
    }

    /**
     * @inheritDoc
     */
    public function onChangeDecision(SluggableAdapter $ea, array &$config, $object, &$slug, &$needToChangeSlug)
    {
        // Do nothing. We don't make any decision until the last possible point.
    }

    /**
     * @inheritDoc
     */
    public function postSlugBuild(SluggableAdapter $ea, array &$config, $object, &$slug)
    {
        $transliterator = new Urlizer();

        $slug = $transliterator->transliterate($slug);

        $slug = $transliterator->urlize($slug);

        if (StringUtils::isNullOrEmpty($slug)) {
            $slug = uniqid();
        }
    }

    /**
     * @inheritDoc
     */
    public function onSlugCompletion(SluggableAdapter $ea, array &$config, $object, &$slug)
    {
        // Do nothing. Once the Slug is complete, we're happy.
    }

    /**
     * @inheritDoc
     */
    public function handlesUrlization()
    {
        return true;
    }

    /**
     * @inheritDoc
     */
    public static function validate(array $options, ClassMetadata $meta)
    {
        // No validation is required. There are no settings for this handler.
    }

}
````

This handler will do both the urlisation and the transliteration, and checks to see if the slug is empty. Then it adds a random uniqid.

The only problem is the transliteration would now run twice, which feels a bit inefficient (nb: urlize is disabled because of the handy `handlesUrlization` function).

So I wrote a new SluggableListener that just overwrites the Transliteration operation.

````php
class OverridenSluggableListener extends SluggableListener
{
    public function __construct()
    {
        parent::__construct();

        $this->setTransliterator(array('\Nora\ProjectBundle\Utility\Sluggable\OverridenSluggableListener', 'noopTransliteration'));
    }

    /**
     * We already run transliteration in the NotEmptySluggableHandler. So this just does nothing.
     *
     * @param string $slug
     * @return string
     */
    public static function noopTransliteration($slug) {

        return $slug;
    }
}
````

Seems to work, hope it might be useful for someone.

In the meantime - I'd be interested in hearing if this is the most efficient way to approach this problem and if not, what I might do to improve it? Otherwise this can be closed.

**Comment by stof** [comment]
instead of using an handler doing the work, and then a noop transliteration, why not simply using a custom transliterator or urlizer (depending of the place where you actually need it) which would call the original implementation and ensure it does not return an empty string ? This might be more efficient

**Comment by edhgoose** [comment]
Yes, that would make sense. I could just override the urlizer as that's currently the last step that causes problems in our implementation.

Thanks, I'll close this.
