### ISSUE TITLE
SoftDeleteable Integrity

### ISSUE THREAD

**Issue by g33kcentric** [Atlantic18/DoctrineExtensions#1479]
Hello! 

Is there a way in the SoftDeleteable extension itself to restrict the deleting of parent entities that still have children, or would this be something I would have to implement myself with an event or similar? 

Thanks :)

**Comment by l3pp4rd** [comment]
hi, sadly there are no magic options, softdeletable does not manage relations, it is too complex

**Comment by g33kcentric** [comment]
Ok, thanks for your reply!
