### ISSUE TITLE
[Translatable] paginating when using TranslationWalker

### ISSUE THREAD

**Issue by ErikTrapman** [Atlantic18/DoctrineExtensions#1482]
Hi,

i'm not sure where to post this issue, but i'll start here.
I'm having trouble paginating filtered results when using the TranslationWalker.
For pagination i use the KnpPaginationBundle, which uses Doctrine's own CountOutputWalker to calculate the total amount of entities in the pagination. 
In order to search in translations I've enabled the TranslationWalker.

To test this I've set up a very simple project with 1 entity: Product, that has a translated name.

These are the queries that I get:

Query1: the familiar count-query from CountOutputWalker
```SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_0 FROM (SELECT p0_.id AS id_0, p0_.name AS name_1 FROM product p0_ WHERE p0_.name LIKE '%einz%') dctrn_result) dctrn_table```

Query2: the filter-query
```SELECT p0_.id AS id_0, t1_.content AS name_1 FROM product p0_ LEFT JOIN ext_translations t1_ ON t1_.locale = 'de' AND t1_.field = 'name' AND t1_.object_class = 'AppBundle\\Entity\\Product' AND t1_.foreign_key = p0_.id WHERE t1_.content LIKE '%einz%';```

Because the LEFT JOIN from query2 is missing in query1, the count-query will always return 0 results, making it impossible to paginate filtered results.

Is there any way to fix this?

**Comment by ErikTrapman** [comment]
These are the packages I'm using:

```json
"require": {
        "php": ">=5.5.9",
        "symfony/symfony": "~2.8.0",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "knplabs/knp-menu-bundle": "~2.0.0",
        "knplabs/knp-menu": "~2.0.1",
        "knplabs/knp-components": "~1.2.5",
        "knplabs/knp-paginator-bundle": "~2.4.2",
        "stof/doctrine-extensions-bundle": "~1.1.0"
    },
```

**Comment by l3pp4rd** [comment]
the problem is that both, knp paginator and translation walker, use sql walker. there can be only one of them and paginator overrides it. If you are sure that you will paginate only orm entities, try a simple solution [like one I use](https://github.com/DATA-DOG/DataDogPagerBundle) it may not look as elegant as knp, but it is small and simple to change. Though it works with query builder, just download source as your project bundle and edit to add translation query hints. this pager has almost no source code.. won't be hard to maintain compared to others.

**Comment by ErikTrapman** [comment]
Thanks for the reply. 

I briefly considered writing my own pagination, but I skipped that (I see you didn't, I'll keep that bundle in mind for future reference) and I've worked around it by creating my own count-query with a clone of the already filtered querybuilder and passing the result as query-hint to the paginator (https://github.com/KnpLabs/KnpPaginatorBundle/blob/master/Resources/doc/manual_counting.md).

**Comment by ErikTrapman** [comment]
@l3pp4rd I've created the best of both worlds by maintaining the original KNP-interface and functionality but internally using the DataDogPaginatorBundle: https://github.com/SamsonIT/SimplerKNPPaginatorBundle
