### ISSUE TITLE
Can't use UUID as ID type with Tree

### ISSUE THREAD

**Issue by Booteille** [Atlantic18/DoctrineExtensions#1483]
Hi.

I use UUID as ID for my entities but as it is a string I can't use it with Tree annotations.
TreeLeft()/TreeRight()/TreeRoot() annotations expect type to be an integer and UUID is a string.

**Comment by l3pp4rd** [comment]
hi, yes there is no uid support if you use tree root I think. try without tree root.

**Comment by Booteille** [comment]
"Tree left field - [lft] type is not valid and must be 'integer' in class"

**Comment by l3pp4rd** [comment]
tree left is not a problem, this is a query builder bug

**Comment by l3pp4rd** [comment]
try it now on master

**Comment by Booteille** [comment]
It's fixed ! Thanks !
