### ISSUE TITLE
Timestampable trait not work

### ISSUE THREAD

**Issue by christiancannata** [Atlantic18/DoctrineExtensions#1485]
I'm using timestampable trait in my entity, but when I am going to persist, created_at is null and I get mysql error.

use LaravelDoctrine\Extensions\Timestamps\Timestamps;
/**
 *
 * @ORM\Entity
 * @ORM\Table(name="user")
 * @ORM\HasLifecycleCallbacks
 */
class User implements Authenticatable, CanResetPassword
{
    use \LaravelDoctrine\ORM\Auth\Authenticatable;
    use \Illuminate\Auth\Passwords\CanResetPassword;
    use Timestamps;

1048 Column 'created_at' cannot be null",

**Comment by l3pp4rd** [comment]
you must import Gedmo Timstampable annotation, not in a trait, but in entity. traits do not carry annotations to classes they are used.

**Comment by christiancannata** [comment]
Now I've put attributes with annotations in Entity, but the problem is the same:
    /**
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     * @Gedmo\Timestampable(on="create")
     * @var DateTime
     */
    protected $createdAt;

    /**
     * @ORM\Column(name="updated_at", type="datetime", nullable=false)
     * @Gedmo\Timestampable(on="update")
     * @var DateTime
     */
    protected $updatedAt;



Column 'created_at' cannot be null

**Comment by l3pp4rd** [comment]
in that case look how to hook TimestampableListener to EventManager of your EntityManager and read documentation carefully

**Comment by hshahdoost** [comment]
@christiancannata (I know it's late but) are you actually changing any field in the entity? because if you just load and entity call flush without any changes the `update` event wouldn't be called.
