### ISSUE TITLE
fetch="EAGER" on translations

### ISSUE THREAD

**Issue by alexcandy91** [Atlantic18/DoctrineExtensions#1489]
Hello, 
I have a class "answer" that could have translations -> "answerTranslations" when I call get on the entity answer and than translate it the system do one query to have the translation of all answer.
Is it possible to have a fetch="EAGER" relation between the two entities in order to do more faster the application?

Nb.. If i try to do a custom query like this 

```
class AnswerRepository extends EntityRepository
{
    public function getAnswerTranslated($locale){
        $repository = $this->getEntityManager()
            ->getRepository('AppBundle:Answer')
            ->createQueryBuilder('a')
            ->select("a.id")
            ->leftJoin("a.answerTranslation","answerTranslation")
            ->where('answerTranslation.locale = :locale')
            ->setParameter('locale',$locale);
        $query = $repository->getQuery();
        dump($query->getResult());die;
    }

}

```
The application show to me this error.

![image](https://cloud.githubusercontent.com/assets/16149868/11844326/8dcf43e8-a40e-11e5-9ba6-fb4ec3ae05af.png)

Thank you so much.

**Comment by l3pp4rd** [comment]
I would advice to use translation query hint, it will do necessary joins in a single query. Of course left joins are expensive and it does them for each field. The queries can be cached though, because all hinted parameters like locale will be taken into account, so anyway, that is the best choice, unless you use custom solutions. Translatable was not made to support new way of eager fetching, it has changed.

**Comment by alexcandy91** [comment]
Hello, 
I can't understand very well what you say, can you show to me an example? 
Because I have to create a complex query and is impossible to get the value of entity translation.

Can you help me?
thanks

**Comment by l3pp4rd** [comment]
Just use the [query hints](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#orm-query-hint) that is meant exactly for these kind of use cases
