### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by Jean85** [Atlantic18/DoctrineExtensions#1491]
I'm upgrading my project to PHP7, and I'm checking the compatibility of my dependencies.
I've run PHP7CC against my vendor folder, and it found just this line in this project:

    File: [...]/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity/Repository/ClosureTreeRepository.php
    > Line 320: Possible array element creation during by-reference assignment
        $refs[$node[$idField]] =& $tmp[$key];

That refers to this line: 

https://github.com/Atlantic18/DoctrineExtensions/blob/e94b30342810d028559dade3e4bac13520e93ba1/lib/Gedmo/Tree/Entity/Repository/ClosureTreeRepository.php#L320

Afar from this, is this project usable under PHP7? Can we put an upper boundary to the composer.json line about this?

**Comment by stof** [comment]
I just fixed our Travis setup so that the tests actually run on PHP 7 (was broken because it was trying to install the ODM and ext-mongo does not exist on PHP 7). Tests are passing on PHP 7 (for the ORM of course, not for the ODM).

**Comment by Jean85** [comment]
Great, thanks!

**Comment by stof** [comment]
Regarding the case reported above, I would need more explanation about when such element creation happens, to understand whether it is a false-positive or no

**Comment by Jean85** [comment]
It's related to this BC change in PHP7: http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.array-order

It seems to affect only the order of the array. I don't know right now if it matters in this context.

**Comment by stof** [comment]
Well, it is not relevant here, as we are dealing with different arrays.

I'm closing this issue now
