### ISSUE TITLE
Introduce TreeRepository traits and remove AbstractTreeRepository's

### ISSUE THREAD

**Issue by aramalipoor** [Atlantic18/DoctrineExtensions#1493]
Sometimes in an app like Sylius they're extending their repositories from **their own** `AbstractRepository` so it is not possible to extend from `NestedTreeRepository` too.

In another hand, as far as I know creating a `AbstractTreeRepository` causes so much duplicates.

Is it a good approach to introduce a **trait** e.g. **NestedTreeRepositoryTrait** so that those systems can use its useful methods? If it is I would be happy to create a PR!

**Comment by l3pp4rd** [comment]
hi, yes that would be a good idea. but should be done to all strategies, closure, path and nested. I was looking forward to remove these abstract repositories one day and now when orm 2.5 requires php 5.4 it would be good to move forward to min PHP 5.4 and bump minor version to extensions. So if you want, I'd be happy to merge it including removal of abstract tree repository nonsense ;)
