### ISSUE TITLE
[Tree] Using "sibling" property is wrong

### ISSUE THREAD

**Issue by kpeu3i** [Atlantic18/DoctrineExtensions#1498]
First of all, sorry for my English.

When i try to move up/down a node (not root) without defined "sibling" property in my Entity class it throws an error. If the property ("sibling") manually defined than after save node has not correct level.

I think the problem in 
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.10/lib/Gedmo/Tree/Strategy/ORM/Nested.php#L334 

and

https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.10/lib/Gedmo/Tree/Strategy/ORM/Nested.php#L350

Also, we can't set the property without exists check
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.10/lib/Gedmo/Tree/Entity/Repository/NestedTreeRepository.php#L113

**Comment by l3pp4rd** [comment]
yes that is an ugly solution to use that property in extensions, so in your case you do have a property named **sibling** on your entity? PHP should add the property if it does not exist, but that should be fixed anyway to different solution, thanks for reminding

**Comment by kpeu3i** [comment]
Thanks for the reply.

I am using combination of magic methods (__call, __set/__get) to call "virtual" setters/getters for all declared properties in my entities. So, solution was to define <code>setSibling()</code> / <code>getSibling()</code> methods and remove **sibling** property declaration.
