### ISSUE TITLE
ID of parent entity not available in filename generation of uploaded file

### ISSUE THREAD

**Issue by SvetlinStaev** [Atlantic18/DoctrineExtensions#1503]
Hi,

I am having a problem with the uploadable extension. I have an Auction entity with an ArrayCollection of AuctionPicture entities which are configured as uploadable. When the auction form is submitted the files are uploaded correctly but I have a problem with the naming when using custom name generator.

In the generate method of the class as per:

```
public static function generate($filename, $extension, $object = null);
```

I receive the AuctionPicture instance which is fine. It has a one-to-one relationship with the Auction and I receive it fine as ```$object->getAuction()``` but the problem is that I get the instance before the Auction is persisted so I do not get an ID for the Auction to use it in naming the file for the AuctionPicture. I would like to name it in the following format:

```
{AUCTION-ID}_{TIMESTAMP}.{EXTENSION}
```
Is there some configuration I am missing in having the entity being processed after the parent one is persisted?

**Comment by l3pp4rd** [comment]
hi, it cannot have ID in this stage, either change the name to some hash of file or use custom implementation of uploading. In general uploadable extension is rarely used, because there may be many custom features which may need manual intervention.

**Comment by SvetlinStaev** [comment]
Got it, will write a custom solution for that. I was under the impression that it is a configuration issue of the listener to hook to the prePersist event
