### ISSUE TITLE
Doctrine UniqueEntity StofDeletable

### ISSUE THREAD

**Issue by shubaivan** [Atlantic18/DoctrineExtensions#1505]
I have UniqueEntity field email and I use SoftDeleteable

            filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

     * @Gedmo\SoftDeleteable(fieldName="deletedAt")
     * @UniqueEntity(
     *     fields="email",
     *     errorPath="not valid",
     *     message="This email is already in use."
     * )

and when in my DB I have user with deletedAt some date and find entity by email 

    $user_by_email = $em->getRepository('ArtelProfileBundle:Users')->findOneByEmail($email);

I have null and this is ok. But when I create new user I have error 

    Integrity constraint violation: 1062 Duplicate entry 'wwwwwdww@1111.com' for key 'UNIQ_1483A5E9E7927C74'",

this my action. But have error when flush, when validate not error. Help

            $data = $request->request->all();
            $data = $this->get('serializer')->serialize($data, 'json');
            $user = $this->get('serializer')->deserialize($data, 'Artel\ProfileBundle\Entity\Users', 'json');

            if (count($errors = $this->get('validator')->validate($user)) > 0) {
                $view = $this->view((string) $errors, 400);

                return $this->handleView($view);
            }

            $em->persist($user);
            $em->flush();

**Comment by l3pp4rd** [comment]
well you have to disable softdeleteable during the insert of new entity

**Comment by GyniO** [comment]
Anyone have a idea how to fix that problem or have other way to avoid this problem?

**Comment by shubaivan** [comment]
I solved. I create a old_email column (non-unique) and set to email when you soft delete a user. And then empty the email column. That's all
