### ISSUE TITLE
[Loggable] issue with userentity

### ISSUE THREAD

**Issue by ctaverne** [Atlantic18/DoctrineExtensions#1508]
Hi,

I versioned "lastlogin" field from userentity to get user connexion history.

But it is a particular case and I have the following issue: username is always NULL at this event because when user logins, username is not yet set to the loggable listener.

I think I located the reason.

in class "LoggerListener" on the function "onKernelRequest(GetResponseEvent $event)":

    /**
     * Set the username from the security context by listening on core.request
     *
     * @param \Symfony\Component\HttpKernel\Event\GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        if (HttpKernelInterface::MASTER_REQUEST !== $event->getRequestType()) {
            return;
        }

        if (null === $this->tokenStorage || null === $this->authorizationChecker) {
            return;
        }

        $token = $this->tokenStorage->getToken();

        if (null !== $token && $this->authorizationChecker->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            $this->loggableListener->setUsername($token);
        }
    }

When I want to version "lastlogin" field from Userentite, I'm in the first case because:
 $event->getRequestType() == HttpKernelInterface::MASTER_REQUEST

and unfortunately,
$this->loggableListener->setUsername($token); is not set...

How can I solve this case ?

thanks for your help
regards

**Comment by l3pp4rd** [comment]
Hi, you should try to switch the event priority if it gets invoked before security token is set. or try to debug your event listener to ensure that the token gets set and when..

**Comment by ctaverne** [comment]
Hi,

thanks a lot for your suggest.
Please could you say me how to switch event priority ?

About listener, I'm using stof/doctrine-extensions-bundle which gives "loggerListener" 

the problem remains the same:


    /**
     * Set the username from the security context by listening on core.request
     *
     * @param \Symfony\Component\HttpKernel\Event\GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        if (HttpKernelInterface::MASTER_REQUEST !== $event->getRequestType()) {
            return;
        }

        if (null === $this->tokenStorage || null === $this->authorizationChecker) {
            return;
        }

        $token = $this->tokenStorage->getToken();

        if (null !== $token && $this->authorizationChecker->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            $this->loggableListener->setUsername($token);
        }
    }

**Comment by l3pp4rd** [comment]
not sure if it is still [valid example](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/symfony2.md#doctrine-extension-listener-services), but have a look. I can't debug it for you though, since I just cannot replicate the context.
