### ISSUE TITLE
Can't to run examples

### ISSUE THREAD

**Issue by kakawi** [Atlantic18/DoctrineExtensions#1510]
I used instruction to run the tests
https://github.com/Atlantic18/DoctrineExtensions#running-the-tests
and it's okay (only 73 test was skipped)

after that I've tried to run example
https://github.com/Atlantic18/DoctrineExtensions#running-the-example
after I wrote in console **php example/run.php** I had exception:

PHP Fatal error:  Uncaught exception 'Doctrine\Common\Persistence\Mapping\MappingException' with message 'Class 'Entity\Category' does not exist' in /var/www/doctrineextensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:96
Stack trace:
#0 /var/www/doctrineextensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php(41): Doctrine\Common\Persistence\Mapping\MappingException::nonExistingClass('Entity\Category')
#1 /var/www/doctrineextensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(281): Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getParentClasses('Entity\Category')
#2 /var/www/doctrineextensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(311): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getParentClasses('Entity\Category')
#3 /var/www/doctrineextensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Class in /var/www/doctrineextensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php on line 96

**Comment by l3pp4rd** [comment]
half of the tests are running with doctrine mongo ODM, if you do not have mongodb extension or service running they will skip..

example was not running because of an update from PR which I haven't fully investigated well, it is not tested.. thanks for noticing it ;)

**Comment by l3pp4rd** [comment]
also regarding PHP7 mongodb odm is broken with old extension dependency..
