### ISSUE TITLE
how to get children/ancestors till particular level or at particular level?

### ISSUE THREAD

**Issue by vishalmelmatti** [Atlantic18/DoctrineExtensions#1517]
I am using gedmo tree - closure strategy for hierarchical data. I have requirement where I want to fetch children/ancestors till particular level/depth. and at particular level. e.g.

I have region hierarchy global regions -> region -> country -> city . 

From city I want to get 

1) its ancestors till regions. So it should return country <- region. 
2) I want to get only region in which city comes under. (at particular level)

same for children,

1) If I have global region, I want to get all children till country. (no cities) - till particular depth

2) If I have global region, I want to get all countries only which comes under global region. 

In ClosureTreeRepository->childrenQueryBuilder I can see

       if ($direct) {
          $where .= 'c.depth = 1';
       } else {
          $where .= 'c.descendant <> :node';
       }

Depth is hard-coded to 1 for direct. So i can't pass depth from outside. To be able to pass from outside might help.

There is no way to get "till depth". Can anybody please help on achieving this.

**Comment by l3pp4rd** [comment]
you can customize a query builder in your repository, if we put that as an option it may have too many options. it is not hard to copy this code and make it custom for specific query you need

**Comment by vishalmelmatti** [comment]
Thanks. Customized it in my repo. Worked.
