### ISSUE TITLE
Add methods to Timestampable interface

### ISSUE THREAD

**Issue by ste93cry** [Atlantic18/DoctrineExtensions#1521]
`Timestampable` extension has an interface called `Timestampable` that contains some annotation blocks (they're more doc block, really) and nothing else. I find really useful to be able to know that a given class is a `Timestampable` entity, but I don't understand why there are no methods defined in the interface. An interface should defines methods that all classes implementing it defines, there is no point imho to have this interface empty. My suggestion is to add the `getCreatedAt`, `setCreatedAt`, `getUpdatedAt` and `setUpdatedAt` methods to the Timestampable interface. This would probably introduce BC break, so to avoid it we could create a new `TimestampableInterface` (that follows the Symfony coding conventions by adding the `Interface` suffix and then make it extending the old interface. In this way, we don't introduce any new BC break and we can remove the base interface in a new major version. What do you think about it? As it's a really simple task to do, I would like to create a PR if you agree on my considerations

**Comment by l3pp4rd** [comment]
Hi, I cannot agree with that. The interface was used for identification reasons at some point as you mentioned. now you can use traits. there won't be BC breaks for such reasons, use traits which implement interfaces you like. People have different kinds of field names for timestamps.

**Comment by ste93cry** [comment]
> The interface was used for identification reasons at some point as you mentioned. now you can use traits

I honestly don't understand this. Traits are not interfaces and they don't serve the same purpose. Plus, your trait already lock people to use a given property name and getter/setter methods, so why would an interface defining the contract be bad? If someone still wants the old behaviour, he just have to inherit the old interface. If he wants the new interface, he just have to extend the new one and he can still identify an entity by the old interface that is just inherited by the new one

> there won't be BC breaks for such reasons, use traits which implement interfaces you like

the proposed solution would not break BC, because the new interface would have extended the old and not vice-versa.

**Comment by l3pp4rd** [comment]
You can make your own traits, you do not need to use library trait, same as interface. Library does not force you on this.. timestampable depends only on metadata, everything else is your concern and it will stay that way, cheers

**Comment by l3pp4rd** [comment]
interfaces will probably be removed
