### ISSUE TITLE
[v2.4.12] php5.3.2 not supported short array definition

### ISSUE THREAD

**Issue by dvapelnik** [Atlantic18/DoctrineExtensions#1528]
In string [Gedmo/Tree/Entity/Repository/MaterializedPathRepository.php#L97](https://github.com/Atlantic18/DoctrineExtensions/blob/2527d8f93779458e097447b5f92132bc65e672f4/lib/Gedmo/Tree/Entity/Repository/MaterializedPathRepository.php#L97) empty array defined as `[]` but `php5.3.2` not supports this syntax. But at the same time `php5.3.2` assigned as minimal supported version for `v2.4.12`

Look at my PR #1529 for changes

**Comment by l3pp4rd** [comment]
released 2.4.13
