### ISSUE TITLE
[Tree] Using doctrine inheritance with gedmo

### ISSUE THREAD

**Issue by aivus** [Atlantic18/DoctrineExtensions#1536]
Hello.
I have a mappedSuperclass entity (in yml file), which contains all gedmo configuration.
Also I have a regular entity which inherited from the mappedSuperclass entity.

But when gedmo Yaml driver trying to get mappings (https://github.com/Atlantic18/DoctrineExtensions/blob/329db2a648aa7640dd538851ea9128413e17ead1/lib/Gedmo/Tree/Mapping/Driver/Yaml.php#L43), it doesn't see mappedSuperclass configuration.

It starts work only after copy mappedSuperclass configuration to entity yml file.

Is it a bug or it's expected behaviour?

Thanks

**Comment by l3pp4rd** [comment]
Hi, this is a standard doctrine behavior, you cannot mix mapping types

**Comment by aivus** [comment]
But doctrine merge mappedSuperclass configuration and entity configuration.

I think gedmo tree will work if I will use php annotations. But it doesn't work with yml.

In my case I try to configure gedmo in mappedSuperclass and use it in my entity without any additional configurations.

**Comment by l3pp4rd** [comment]
you can specify different driver for gedmo mapped superclasses and use yaml driver for your own. as an example extensions [has a method](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/DoctrineExtensions.php#L56) to register driver for their mapping into driver chain.
