### ISSUE TITLE
[Sortable] Multiple position fields?

### ISSUE THREAD

**Issue by Padam87** [Atlantic18/DoctrineExtensions#1538]
Hi,

Is there an easy way to get sortable working with multiple position fields, based on groups?

I see that there was a commit over 2 years ago (3e87bd11d9649f7df270d48a740e75e1c9502f5b), which has never been merged, an terribly out of date.

Has anyone found a workarond for this ?

Thanks!

**Comment by l3pp4rd** [comment]
Hi, as far as I know you can only use one position for sortable

**Comment by Padam87** [comment]
I was afraid this would be the case. We absolutely need this for our new project, so I will take a stab at it.

I don't think I will be able to preserve BC, but if I do I will submit a PR.

**Comment by l3pp4rd** [comment]
current master is scheduled for 2.5.0 release and can have BC changes, if you have time to adapt it based on WIP3.0 pull request, then it can be merged, but it may take a while to update tests
