### ISSUE TITLE
[Uploadable] 'uploadablePostFileProcess' event doesn't contain the new generated filename/path.

### ISSUE THREAD

**Issue by Alsatian67** [Atlantic18/DoctrineExtensions#1542]
I'm trying to add some code in a listener listening the [uploadablePostFileProcess](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Uploadable/UploadableListener.php#L343).

In my listener I want to access the file which has been processed.

```
    public function uploadablePostFileProcess(UploadablePostFileProcessEventArgs $args)
    {	exit(var_dump($args->getFileInfo()));
        switch($args->getAction()){
			case 'CREATE':
			
			break;
			case 'UPDATE':
			
			break;
			case 'DELETE':
			
			break;
		}
    }
```

But the infos returned by $args->getFileInfo() don't contain any information on the generated path / filename. But the real name of the uploaded file.

I don't now if it is intentional ?

**Comment by Alsatian67** [comment]
May be related to #823

**Comment by Alsatian67** [comment]
May be :

```
            $evm->dispatchEvent(Events::uploadablePostFileProcess, new UploadablePostFileProcessEventArgs(
                $this,
                $om,
                $config,
                $fileInfo,
                $object,
                $action
            ));
```

Should be something like :
```
            $evm->dispatchEvent(Events::uploadablePostFileProcess, new UploadablePostFileProcessEventArgs(
                $this,
                $om,
                $config,
**                $info,**
                $object,
                $action
            ));
```

**Comment by l3pp4rd** [comment]
you get your entity as `$object` and there can be an actual file path and necessary information. also there is [callback option](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Uploadable/UploadableListener.php#L318) also you can extend [moveFile](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Uploadable/UploadableListener.php#L478) method to get the $info.. I think there are many options to hook in, I do not want to introduce backward incompatible changes for not good enough reason

**Comment by Alsatian67** [comment]
OK, I think it will be easy through the entity.

Thank you.
