### ISSUE TITLE
[SoftDeleteable] not working on bidirectional oneToOne

### ISSUE THREAD

**Issue by poolerMF** [Atlantic18/DoctrineExtensions#1548]
<?php
	/** @Entity */
	class Customer
	{
		// ...

		/**
		 * @OneToOne(targetEntity="Cart", mappedBy="customer")
		 */
		private $cart;

		// ...
	}

	/** @Entity */
	class Cart
	{
		// ...

		/**
		 * @OneToOne(targetEntity="Customer", inversedBy="cart")
		 * @JoinColumn(name="customer_id", referencedColumnName="id")
		 */
		private $customer;

		// ...
	}

there is **SoftDeleteable **on **Customer **and on **Cart**
when I want to select Customer, there is **automatic left join** ... and it's selecting even deleted cart ...
so, SoftDeleteable is not working on oneToOne

**Comment by Padam87** [comment]
This is a doctrine issue. In some cases, docrine is forced to hydrate. This is one of those cases. 

Customer has a one-to-one relation, but the owner of said relation is the cart object (that has the customer_id). The hydrator is forced to fetch and hydrate the cart. There is nothing that can be done about that by this library I think.

There are a couple of things that can possibly help you:
- Flip the owning side of the relationship
- Refactor your code to have a one-to-many relationship ordered by the deleted at timestamp
- Simply remove the cart reference from customer, and have it fetched by the repository.

**Comment by Padam87** [comment]
You could report this issue to doctrine, but there is nothing that could be done about it ATM, and I'm not sure that they would even think about it, considering the amount of work that has to be done to change this.

**Comment by poolerMF** [comment]
I don't think its problem of DOCTRINE ...
when I look at SoftDeleteableFilter, there is NOTHING about what else is in SQL query left join on another table)

SoftDeleteableFilter is solving deleteable only for "actual table/root entity" .. it's not solving, if there is oneToOne, oneToMany, manyToOne or manyToMany

I'm talking about **SELECT-ing entites**.. not about removing entities

**Comment by Padam87** [comment]
I understand that. Remove the softdeleteable, and check the queryes. The cart will still be fetched. Its done internally by doctrine.

**Comment by poolerMF** [comment]
yes, cart is still fetched ... there is no problem with that
it's problem of selecting entities in sql filter

maybe someone else should write something

**Comment by Padam87** [comment]
The sql filter currently does not work on joins, this has always been the way this extension works, you would have to add the condition manually. In your case, doctrine is making the join automatically, you can't add an extra condition without the query builder.

Either you do a quick refactor on your code, or do a PR that makes the sql filter handle joins, which would be a great new feature in 3.0 :)

**Comment by Padam87** [comment]
https://github.com/Atlantic18/DoctrineExtensions/issues/1427#issuecomment-155686889

**Comment by poolerMF** [comment]
so, with actual version of DOCTRINE there is no way to do this automatically with SoftDeleteable ..
I must refactor entities

**Comment by alcaeus** [comment]
@poolerMF this has always been the case with Doctrine. Inversed one-to-one relationships are always fetched eagerly when hydrating the document. Proxies can't be used because they rely on the identifier of the entity being known, which isn't the case for inversed references.

One common use case is, as @Padam87 already mentioned, to use a one-to-many relationship (which won't be loaded eagerly) and then have a `getCart()` method which proxies to the collection and returns the last (or first depending on how you want your logic to be) element from the `cart` collection.
