### ISSUE TITLE
Force the use of original field value on single query

### ISSUE THREAD

**Issue by Marthoni-Anders** [Atlantic18/DoctrineExtensions#1552]
I have tried to look for a solution now in several places.

Is it possible to get a query hint, something like "force fallback" or "use original value" in order to tell Gedmo not to translate a translateable field?

**Comment by l3pp4rd** [comment]
disable the translatable listener by removing it from event manager and put it back after the query if you want default field values. Or if you have set persistDefaultLocaleTranslation flag to listener, then you can query translation table directly

**Comment by Marthoni-Anders** [comment]
There are 5 translatableListeners http://imgur.com/AzmmN20 it's quite a simple thing, and a simple flag in the query is something I think would benefit a lot

**Comment by l3pp4rd** [comment]
might be something to consider, it is not a common use case though. but you could use default locale also I think, in order to load it with these fields.
