### ISSUE TITLE
GedmoTree - Resort on Parent Delete 

### ISSUE THREAD

**Issue by WildChildForLife** [Atlantic18/DoctrineExtensions#1555]
Hey, 

I am using the Closure strategy, and I would like to perform the following :
Suppose I have a Page entity, and data that are nested like this : 

--Page A
----Page A1
----Page A2
--------Page A21
--------Page A22

By deleting Page A2, i want to have this result : 

--Page A
----Page A1
----Page A21
----Page A22

By re-appending the children of the deleted page, to the their levels - 1 (the parent of the deleted page).

Actually, by deleting a page, all its children are deleted with it. How can I perform what im asking for ? 
Thank you.

**Comment by Padam87** [comment]
Are you sure that they are deleted? Their parent ID should be set to null, but the record should still exist if I remember correctly.

You could create an `onFlush` listener, grab the scheduled deletions and attach the children to the deleted item's parent. (should remove onDelete="CASCADE" from the join column)

**Comment by l3pp4rd** [comment]
this operation cannot be performed in extensions. imagine a standard directory structure, you cannot remove directory without removing it's contents. it involves two operations:

- first reparent children for page2 you want to remove, to page A (which is a parent of page2)
- then remove the page2

do it in transaction.

**Comment by WildChildForLife** [comment]
Thanks for your answers guys.
Ive found the solution, by adding a PreRemove listenner in the entity itself : 

`    /**
    * @ORM\PreRemove
    */
    public function updateOrphans()
    {
        return $this->_updateOrphans($this);
    }

    public function _updateOrphans(Page &$oPage, $bRecursive = false)
    {
        foreach( $oPage->getChildren() as $iKey => &$sValue)
        {
            // Update Level
            if ( (int)$sValue->getLevel() > 1 ) $sValue->setLevel((int)$sValue->getLevel() - 1);
            // Update Parent (Only for the direct children)
            if (!$bRecursive) $sValue->setParent($oPage->getParent());
            // Recursive 
            if ( $sValue->getChildren()->count() > 0 ) $this->_updateOrphans($sValue, true);
        }

        return $oPage;
    }`

**Comment by l3pp4rd** [comment]
great, thanks for posting example, maybe it will be useful to someone..
