### ISSUE TITLE
Replace EntityManager with EntityManagerInterface in method declarations, etc.

### ISSUE THREAD

**Issue by Housik** [Atlantic18/DoctrineExtensions#1556]
I suggest to replace EntityManager with EntityManagerInterface as attribute type in method declaration (do the same for the rest where possible). Now it is impossible to use custom EntityManager class. 

Example:
**Gedmo\Tree\Entity\Repository\AbstractTreeRepository::__construct() must be an instance of Doctrine\ORM\EntityManager**

``` php
<?php
namespace Gedmo\Tree\Entity\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Gedmo\Tree\RepositoryInterface;
use Gedmo\Tree\Traits\Repository\ORM\TreeRepositoryTrait;
abstract class AbstractTreeRepository extends EntityRepository implements RepositoryInterface
{
    use TreeRepositoryTrait;
    /**
     * {@inheritdoc}
     */
    public function __construct(EntityManager $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->initializeTreeRepository($em, $class);
    }
}
```

**Comment by l3pp4rd** [comment]
sure, you can submit a pull request

**Comment by Metabor** [comment]
Guess this can be closed now.

**Comment by PetrHeinz** [comment]
Thank you, @Metabor, for fixing this. May I just ask when will v2.4.34 be released? I want to use a decorated `EntityManager` along with this repository and I'd rather depend on a relased version than dev branch. Can I help with the release?

**Comment by l3pp4rd** [comment]
should be there ;)
