### ISSUE TITLE
[Tree] verify() and root

### ISSUE THREAD

**Issue by FranzBruckner** [Atlantic18/DoctrineExtensions#1567]
Is there a bug in NestedTreeRepository::verifyTree() or do i missunderstand something?

The sample-entity in the [documentation ](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/tree.md#entity-mapping) has a root-property of type category.

```
/**
 * @Gedmo\Tree(type="nested")
 * @ORM\Table(name="categories")
 * use repository for handy tree functions
 * @ORM\Entity(repositoryClass="Gedmo\Tree\Entity\Repository\NestedTreeRepository")
 */
class Category
{
...
    /**
     * @Gedmo\TreeRoot
     * @ORM\ManyToOne(targetEntity="Category")
     * @ORM\JoinColumn(referencedColumnName="id", onDelete="CASCADE")
     */
    private $root;
...
}
```

But it seems that the Method [verifyTree](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.13/lib/Gedmo/Tree/Entity/Repository/NestedTreeRepository.php#L896) in NestedTreeRepository expects an scalar value.
`$rootId = isset($config['root']) ? $meta->getReflectionProperty($config['root'])->getValue($root) : null;`

This throws an exception when adding the error-message to the error-array.
`$errors[] = "index [{$i}], missing".($root ? ' on tree root: '.$rootId : '');`

Line 924, 926, 945, 967, 

I'am using the latest version 2.4.13, but it seems that the traits in master have the same problem.

**Comment by l3pp4rd** [comment]
hi, yes indeed, seems to be a bug since the support was added for relation as root. would you care to open a pull request?

**Comment by FranzBruckner** [comment]
Yes, sure.
I have to check how to do that :).

**Comment by mrfijas** [comment]
any news on this?

```
$identifier = $meta->getSingleIdentifierFieldName();
$root = isset($config['root']) ? $meta->getReflectionProperty($config['root'])->getValue($root) : null;
$rootId = $meta->getReflectionProperty($identifier)->getValue($root);
```
in `NestedTreeRepository` seems to work for me
