### ISSUE TITLE
[Tree] recover() does not recover level-property

### ISSUE THREAD

**Issue by FranzBruckner** [Atlantic18/DoctrineExtensions#1568]
The method recover() does not repair the level-property

I updated [the anonymous function](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.13/lib/Gedmo/Tree/Entity/Repository/NestedTreeRepository.php#L818) with the following code:

```
$doRecover = function ($root, &$count, $level = 0) use ($meta, $config, $self, $em, &$doRecover) {
            $lft = $count++;
            foreach ($self->getChildren($root, true) as $child) {
                $doRecover($child, $count, ($level + 1));
            }
            $rgt = $count++;
            $meta->getReflectionProperty($config['left'])->setValue($root, $lft);
            $meta->getReflectionProperty($config['right'])->setValue($root, $rgt);
            $meta->getReflectionProperty($config['level'])->setValue($root, $level);
            $em->persist($root);
};
```

I will try to open a pull-request for it.

**Comment by l3pp4rd** [comment]
thanks, only the **level** is optional, so a check needs to be added:

``` php
$doRecover = function ($root, &$count, $level = 0) use ($meta, $config, $self, $em, &$doRecover) {
            $lft = $count++;
            foreach ($self->getChildren($root, true) as $child) {
                $doRecover($child, $count, ($level + 1));
            }
            $rgt = $count++;
            $meta->getReflectionProperty($config['left'])->setValue($root, $lft);
            $meta->getReflectionProperty($config['right'])->setValue($root, $rgt);
            if (isset($config['level'])) {
                $meta->getReflectionProperty($config['level'])->setValue($root, $level);
            }
            $em->persist($root);
};
```

**Comment by stephanvierkant** [comment]
Any update on this?

**Comment by l3pp4rd** [comment]
is anyone still up for pull request?

**Comment by pmishev** [comment]
I had fixed this long time ago in a pull request that you rejected:
https://github.com/Atlantic18/DoctrineExtensions/pull/1340/files#diff-feaf7e376d735096c25d45c4028b3d22L838

**Comment by l3pp4rd** [comment]
@pmishev I rejected it because you've added an api extension. **level_base** is not necessary and it works fine for everyone as being **0** for initial level. Another point, is that you've added **reorder** method functionality into recover, it can be avoided by using [reorder](https://github.com/pmishev/DoctrineExtensions/blob/091414a99bc86b90e723531482227bad17165f67/lib/Gedmo/Tree/Entity/Repository/NestedTreeRepository.php#L851) after recovering.
