### ISSUE TITLE
[Tree] Not correct setter for root node

### ISSUE THREAD

**Issue by vvasilenok** [Atlantic18/DoctrineExtensions#1571]
For  [this ](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/transaction-safety.md) example setter of root element works not correctly. Now in the current implementation, Nested set root to self but need to set root to Shop entity.
I think need replace [this string](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Strategy/ORM/Nested.php#L400) to
 `if ($root = $meta->getFieldValue($node, $config['root'])) {
                $newRoot = $root;
            } else {
                if ($meta->isSingleValuedAssociation($config['root'])) {
                    $newRoot = $node;
                } else {
                    $newRoot = $wrapped->getIdentifier();
                }
            }`

**Comment by l3pp4rd** [comment]
hm, seems like an issue, can you submit a pull request?
