### ISSUE TITLE
Timestampable and Commands

### ISSUE THREAD

**Issue by foaly-nr1** [Atlantic18/DoctrineExtensions#1574]
I added the following field to my User entity I use with FOSUserBundle:

```php
  /**
   * @ORM\Column(type="datetime")
   * @Gedmo\Timestampable(on="create")
   */
  private $createdAt;
```

It works fine when creating a user from a service. It fails from the command line.

```bash
php bin/console fos:user:create admin hello@domain.com admin --super-admin

[Doctrine\DBAL\Driver\PDOException]                                                       
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created_at' cannot be null 
```

**Comment by l3pp4rd** [comment]
maybe you use different environment to run command. it seems like listener is not injected to the entity manager. this issue is not related to extensions, but to a framework configuration or bundles you use. you should debug that yourself, the library works fine even in console
