### ISSUE TITLE
Wrong namespace leads to warning "Node no longer exists"

### ISSUE THREAD

**Issue by scuben** [Atlantic18/DoctrineExtensions#1598]
With the xml doctrine schema and the example from https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/timestampable.md it uses the namespace

`xmlns:gedmo="http://Atlantic18.github.io/DoctrineExtensions/schemas/orm/doctrine-extensions-3.0.xsd"`

But the correct namespace is

`xmlns:gedmo="http://gediminasm.org/schemas/orm/doctrine-extensions-mapping"`

**Comment by siimrei** [comment]
I think that the problem lies in DoctrineExtensions/lib/Gedmo/Mapping/Driver/Xml.php where the wrong namespace is being used.
`const GEDMO_NAMESPACE_URI = 'http://gediminasm.org/schemas/orm/doctrine-extensions-mapping';`
The readme file says that differents schemas are used for different versions but the code expects only one invalid url.

**Comment by l3pp4rd** [comment]
yes, probably this needs to be fixed and uri should be changed

**Comment by PeterLabos** [comment]
Thanks, 2 hours spent on this irritating error "Node no longer exists".

**Comment by PeterLabos** [comment]
Thanks, 2 hours spent on this irritating error "Node no longer exists".

**Comment by holtkamp** [comment]
I am not sure this approach is totally correct. 

The namespace can differ from the "physical" location of the XML Schema. 

This is perfectly valid XML AFAIK:

```xml
<doctrine-mapping 
xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping" 
xmlns:gedmo="http://gediminasm.org/schemas/orm/doctrine-extensions-mapping" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping https://raw.githubusercontent.com/doctrine/doctrine2/master/doctrine-mapping.xsd gedmo http://Atlantic18.github.io/DoctrineExtensions/schemas/orm/doctrine-extensions-2.4.xsd"/>
```


So this says:
- the namespace "http://gediminasm.org/schemas/orm/doctrine-extensions-mapping"
- can be found in a XML Schema at URL "http://Atlantic18.github.io/DoctrineExtensions/schemas/orm/doctrine-extensions-2.4.xsd"

I think this would have been a more elegant approach opposed to changing the namespace in the XML Drivers, which kind of breaks all mapping files of users already using it: 

**Warning: Gedmo\Mapping\Driver\Xml::_isAttributeSet(): Node no longer exists**

Look at this strange situation, the version tagged as ```2.4.14``` uses the ```3.0.x``` namespace:
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.14/lib/Gedmo/Mapping/Driver/Xml.php#L21

A big warning on the main page would be appropriate, or a fix to correct this?

**Comment by l3pp4rd** [comment]
there was a mistake in the tag recently, wrong branch was tagged

**Comment by holtkamp** [comment]
@l3pp4rd , aah, ok. Sorry for my ranting than 😊. I can see the proper namespace is used again:
```http://gediminasm.org/schemas/orm/doctrine-extensions-mapping```
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.14/lib/Gedmo/Mapping/Driver/Xml.php#L21

I do find this an interesting issue, that a mismatch in namespaces seems to result in such strange error message. In my case the ```timestampable``` XML tag was for some reason processed, while it was in the "wrong" name space at that time. Will have a look at that 👍
