### ISSUE TITLE
How to define the locale in which to retrieve entities?

### ISSUE THREAD

**Issue by Alsciende** [Atlantic18/DoctrineExtensions#1600]
I'm trying to do a simple thing, I guess, but I didn't find any help in the documentation. I really wished there was one more paragraph in the section [Basic usage examples](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#basic-usage-examples), telling us how to retrieve the entity in `de_de` locale, because that's exactly what I want to do. This section explains how to set the fields in `en_us`, then how to set the fiels in `de_de`, then how to retrieve the fields in `en_us`. The omission of "how to retrieve the fields in `de_de`" is glaring (even if it is to say that the translations cannot be retrieved via the standard repository methods and give pointers).

I have my entities correctly translated in the ext_translation table. I can use the query hints from [Using ORM query hint](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#using-orm-query-hint) to get the entities in any locale. But when I try to use the `find()` method of my repository, I get the entity in the default locale. I don't know how to change that. I tried setting the locale of my request, but it didn't help.

**Comment by l3pp4rd** [comment]
translatable listener has a **setTtanslatableLocale** method. usually it should be set early in from request or session. see the symfony2 example [request listener](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/symfony2.md#doctrine-extension-listener-services) the php class sample following after yml.

**Comment by Alsciende** [comment]
I can't find a clear explanation of how to use **setTranslatableLocale** manually, when I want to use a different locale from the one from the request or session.

After a careful re-reading of the documentation, I discovered these lines that I had missed at first:

```
// reload in different language
$article = $em->find('Entity\Article', 1 /*article id*/);
$article->setLocale('ru_ru');
$em->refresh($article);
```

I'm going to submit a PR to make the documentation more easy to follow in this section.

**Comment by l3pp4rd** [comment]
well, it's not exactly an entity method. it is [listener](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Translatable/TranslatableListener.php#L278) when set early in request it will load all translated entities by this locale. Another option is to use query hints when you need to load lists of entities.
