### ISSUE TITLE
Slug validation on duplicate entry

### ISSUE THREAD

**Issue by ducho** [Atlantic18/DoctrineExtensions#1604]
Hi. 
Is it possible to validate slug (title) after form submit? UniqueEntity() not working becouse slug is generated with onFlush() handler. 

Now, after flush() is calling exception: 

> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'spolocnost/pracovne-prilezitosti' for key 'UNIQ_140AB620989D9B62'
500 Internal Server Error - UniqueConstraintViolationException

I need to validate slug before persist and if exists duplicate slug the return error message to form. 

Thanks.
Ducho.

**Comment by l3pp4rd** [comment]
Hi, if you set unique option for slug field it will prefix non unique slug with index. if you do not wish to have an index, I suggest you simply use [sluggable transliterator](https://github.com/Behat/Transliterator/blob/master/src/Behat/Transliterator/Transliterator.php) in your form data transformer and then form is validated in controller confirm that it is unique by querying a database.

**Comment by ducho** [comment]
Thanks for quick reply. That transliterator is compatible with $sluggableListener->generateSlug() ?

**Comment by l3pp4rd** [comment]
yes, it uses it

**Comment by ducho** [comment]
This annotation not working with unique index.
   
    /**
     * @Gedmo\Slug(handlers={
     *      @Gedmo\SlugHandler(class="Gedmo\Sluggable\Handler\TreeSlugHandler", options={
     *          @Gedmo\SlugHandlerOption(name="parentRelationField", value="parent"),
     *          @Gedmo\SlugHandlerOption(name="separator", value="/")
     *      })
     * }, fields={"title"}, unique=true)
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

**Comment by ducho** [comment]
The sluggable transliterator is not possible to use with:
Sluggable + NestedTree + TreeSlugHandler

@ORM\PreFlush() not working too... 

No exists solution to handle slug duplicity with Forms...

**Comment by l3pp4rd** [comment]
slug handlers do not check the uniqueness, the library needs to be improved concerning this case. but probably there was a reason, why it is so, just can't remember now.

**Comment by ducho** [comment]
Sorry, but probably I do not understand enough... What is the purpose function makeUniqueSlug() in the SluggableListener?

**Comment by l3pp4rd** [comment]
as far as I remember slug handlers are not checked for uniqueness

**Comment by ducho** [comment]
Uniqueness is solved only at the first level. So if is used with TreeSlugHandler then function makeUniqueSlug() don't increments slug with separator and number (e.g. company-1). I will try to fix this bug.

**Comment by ducho** [comment]
@l3pp4rd so I fixed it... 
Do I have to do pull request?

**Comment by l3pp4rd** [comment]
would be great @ducho
