### ISSUE TITLE
[Sluggable] Incompatibility with php 7.0.7

### ISSUE THREAD

**Issue by stefanotorresi** [Atlantic18/DoctrineExtensions#1605]
PHP 7.0.7 introduced this change: https://bugs.php.net/bug.php?id=72209

This has unveiled a peculiar bug in `Gedmo\Sluggable\SluggableListener::makeUniqueSlug()`: when there are multiple entities with the same `slug` property, at some point in [this cycle](https://github.com/Atlantic18/DoctrineExtensions/blob/f3c474dd9c3dbcf2fcd86075961a4ffad88fd20e/lib/Gedmo/Sluggable/SluggableListener.php#L436-L444) the wrong metadata is used, so a reflection of a different entity object is used, and this now results in an error.

I was able to write a patch to fix the issue:

```diff
diff --git a/lib/Gedmo/Sluggable/SluggableListener.php b/lib/Gedmo/Sluggable/SluggableListener.php
index e4af702..7858617 100644
--- a/lib/Gedmo/Sluggable/SluggableListener.php
+++ b/lib/Gedmo/Sluggable/SluggableListener.php
@@ -434,10 +434,12 @@ class SluggableListener extends MappedEventSubscriber
         // collect similar persisted slugs during this flush
         if (isset($this->persisted[$class = $ea->getRootObjectClass($meta)])) {
             foreach ($this->persisted[$class] as $obj) {
-                if ($base !== false && $meta->getReflectionProperty($config['unique_base'])->getValue($obj) !== $base) {
+                $similarMeta = $om->getClassMetadata(get_class($obj));
+                if ($base !== false && $similarMeta->getReflectionProperty($config['unique_base'])->getValue($obj) !== $base) {
                     continue; // if unique_base field is not the same, do not take slug as similar
                 }
-                $slug = $meta->getReflectionProperty($config['slug'])->getValue($obj);
+                $slugRefl = $similarMeta->getReflectionProperty($config['slug']);
+                $slug = $slugRefl->getValue($obj);
                 $quotedPreferredSlug = preg_quote($preferredSlug);
                 if (preg_match("@^{$quotedPreferredSlug}.*@smi", $slug)) {
                     $similarPersisted[] = array($config['slug'] => $slug);
```

but honestly I'm a bit lost on writing a unit test for this; I'm not familiar with the codebase, there are no contributing guidelines, and as far as I've seen there are mostly functional test, so I could use some pointers to put together a proper PR.

**Comment by l3pp4rd** [comment]
this can be simply fixed in the code, adding a unit test case for this exact case, won't prevent users from changing it in another. thanks for pointing it out, I will have a look later

**Comment by stefanotorresi** [comment]
I got the gist of it and I'm working on a full PR with a functional test to prevent regressions.
