### ISSUE TITLE
NestedTree moveUp/moveDown not working as expected

### ISSUE THREAD

**Issue by adiq** [Atlantic18/DoctrineExtensions#1606]
NestedTree moveUp/moveDown is not working as expected.

It should: change up/down position in same level
What it does: changes parent of node

https://github.com/Atlantic18/DoctrineExtensions/blob/8eae0903abfe8cfac2715018d807637bb92bbfc5/lib/Gedmo/Tree/Traits/Repository/ORM/NestedTreeRepositoryTrait.php#L621

https://github.com/Atlantic18/DoctrineExtensions/blob/8eae0903abfe8cfac2715018d807637bb92bbfc5/lib/Gedmo/Tree/Strategy/ORM/Nested.php#L287

Probably it's buggy because of line `list($position, $siblingInPosition) = $this->nodePositions[$oid];` overriting `$position` value.

I will be glad if someone can look into this. Cheers :smiley:

**Comment by l3pp4rd** [comment]
Hi, maybe you can generate a failing test case?

**Comment by adiq** [comment]
Probably not relevant anymore, as this class seems to be refactored and fixed.
