### ISSUE TITLE
[SoftDeletable] Deleted entry and unique validator

### ISSUE THREAD

**Issue by rscarriere** [Atlantic18/DoctrineExtensions#1607]
I have a case where users are entering unique IDs into a table directly (rather than autogenerating) and I am using the @UniqueEntity validator to prevent constraint violations.  

However it seems if an entry is "soft deleted" the validator is ignored resulting in a error/exception being executed due to unique constraint violation.  Steps to reproduce would be:

1. Create an entry with id "test"
2. Delete entry (soft delete)
3. Create a new entry with "test" again.

Is there a way to continue to use this validator even with soft deleted entries?

I know I could work around this by using an auto generating ID column and keeping this as a unique secondary identifier however I was hoping for a cleaner solution.

**Comment by l3pp4rd** [comment]
extend the validator and make your own which disables softdeleteable when the check is done. the symfony framework cannot interfere if extensions and visa versa. you have to adapt to whatever you use.

**Comment by rscarriere** [comment]
Thanks.  I found a thread here which outlines how someone approached it:
https://github.com/symfony/symfony/issues/6955

Definitely not a quick and simple solution.  Here's hoping something more straight forward come along to help us newbs in the future.
