### ISSUE TITLE
how to disable translation for a specific query

### ISSUE THREAD

**Issue by strauss69400** [Atlantic18/DoctrineExtensions#1612]
hi,
I would like to disable , for a query specific, the translation layer .

indeed I executes a query that return me 1500 objects.

the problem is that for every object, an additional request is made for traduction.i would like to disable it just for this request for to get only a single query.

this my query :

 `SELECT a0_.id AS id_0, a0_.ordre AS ordre_1, a0_.dateCrea AS dateCrea_2, a0_.dateModif AS dateModif_3, a0_.datePubli AS datePubli_4, a0_.highlight AS highlight_5, a0_.actif AS actif_6, a0_.slug AS slug_7, a0_.actifLocale AS actifLocale_8, a0_.slugcustom AS slugcustom_9, a0_.title AS title_10, a0_.text_intro AS text_intro_11, a0_.meta_description AS meta_description_12, a0_.content AS content_13, a0_.oldurl AS oldurl_14, a0_.oldid AS oldid_15, a0_.oldurlen AS oldurlen_16, a0_.oldiden AS oldiden_17, a0_.oldurles AS oldurles_18, a0_.oldides AS oldides_19, a0_.auteur_id AS auteur_id_20, a0_.vignette_id AS vignette_id_21, a0_.vignette2_id AS vignette2_id_22, a0_.vignetteoriginal_id AS vignetteoriginal_id_23 FROM article a0_ ORDER BY a0_.ordre ASC `

and for every object this query is made : 
`SELECT t0.id AS id_1, t0.locale AS locale_2, t0.field AS field_3, t0.content AS content_4, t0.object_id AS object_id_5 FROM article_translations t0 WHERE t0.object_id = ?
Parameters: [2178] `

do you have a solution for to disable all this queries.
thanks

**Comment by l3pp4rd** [comment]
see [query hint](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#orm-query-hint) it autojoins translations.

**Comment by YuriyChmil** [comment]
Hello. I am also interested in this option. I want to disable translation at all for a specific query. Is it possible?
