### ISSUE TITLE
[Sluggable] I want to keep the history

### ISSUE THREAD

**Issue by alexseif** [Atlantic18/DoctrineExtensions#1614]
Hello I just started using sluggable today, now I'm thinking that if I update my title the slug will be updated, and this is the intended behavior.
However I would also like to redirect traffic from the old slug to the new slug..
How is that possible? should I use loggable alongside ?

**Comment by l3pp4rd** [comment]
loggable or something more [useful for auditing](https://github.com/DATA-DOG/DataDogAuditBundle)

**Comment by alexseif** [comment]
After digging in loggable it doesn't look like the ideal solution as it
would degrade performance in the long run. However adding a listener to
loggable and adding old slugs to a redirect table of some sort and a
listener on sluggable to avoid duplicates.

Wish he luck, dunno if i can pull this off XD

**Comment by l3pp4rd** [comment]
implement a custom event listener, this is much easier actually, instead of looking for existing solutions which are for broad use cases..

**Comment by alexseif** [comment]
Now that you mention that i guess the best course of action is adding a
feature to Sluggable [redirect-updated-slugs] to the vendor and then making
a pull request. But i doubt I'll do it properly, neither would the feature
be easily accepted

**Comment by l3pp4rd** [comment]
I would not accept such feature, it is not related to sluggable in general. sluggable may be used in different context not only url related and such options are not a concern of sluggable.

**Comment by alexseif** [comment]
Thank you @l3pp4rd you've been very helpful, I will close this issue now.
