### ISSUE TITLE
 Incorrect syntax for arrays in PHP 5.3 for version 2.4.x

### ISSUE THREAD

**Issue by Loscillo** [Atlantic18/DoctrineExtensions#1638]
Hi,

In the commit 7c85797d06ded72d3e768e34c41ab0bf383fc699, the short syntax to create array was used in line 407 : 

`$errors = [];`

However, if [we look](https://packagist.org/packages/gedmo/doctrine-extensions#v2.4.18) at the version of PHP required to run the extension in version 2.4.x, this is the version 5.3.2. I know that PHP 5.3 has been abandoned, but it would be good to update the dependencies or maintain compatibility.

**Comment by l3pp4rd** [comment]
indeed, could you submit a pull request?
