### ISSUE TITLE
Registered sign

### ISSUE THREAD

**Issue by gazouweb** [Atlantic18/DoctrineExtensions#1640]
Hi,
How to prevent convert the sign registered ?
For exemple, for "the mark®" I would "the-mark" and not "the-mark'r".
Tanks in advance

**Comment by gazouweb** [comment]
Help ...

**Comment by l3pp4rd** [comment]
Hi, you can customize the transliteration method and do whatever you like. listener has a method to override it..

**Comment by gazouweb** [comment]
Sorry for the delay, but I don't understand how to implement

**Comment by l3pp4rd** [comment]
go through the code or google it. I do not have willing or time to explain it. I'm sure there are similar questions on stackoverflow
