### ISSUE TITLE
Translate image path

### ISSUE THREAD

**Issue by Audax23** [Atlantic18/DoctrineExtensions#1643]
Hi everybody,
I work on a multi-language website, i use gedmo translatable to translate the text.
i need to have a different picture on each language, so i created an entity translation, the text is translated successfully but when i upload a new file, the picture in default language is replaced, how can i do to have a new image in the translation entity instead of default ?
thanks for your help

**Comment by Audax23** [comment]
up, nobody can help me ?

**Comment by l3pp4rd** [comment]
store path as a text, because probably the uploading extension you are using, is performing actions after translatable. or try to switch listener position in event manager. anyway, these kinds of issues are your concern, you did not even provide the context how you upload a file.

**Comment by Audax23** [comment]
ok first, thank you for your time.
you have right, it's probably because upload is done before and translation after.
i haven't tested with gedmo uploadable, but i understand that using it can help me.
please look context of the image entity that i use, as you can see, i have put a prePersist to set filename and postPersist element to make upload, i have added @translatable on the path, the variable is displayed in my database but value is set to null in entity translation table.

6 en ADX\CmsBundle\Entity\Image name 59 test en2
7 en ADX\CmsBundle\Entity\Image path 59 NULL

<?php
namespace ADX\CmsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo; // gedmo annotations
use Gedmo\Translatable\Translatable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Table("adx_image")
 * @ORM\Entity(repositoryClass="ADX\CmsBundle\Repository\ImageRepository")
 * @Gedmo\TranslationEntity(class="ADX\CmsBundle\Entity\Translation\ImageTranslation")
 * @ORM\HasLifecycleCallbacks
 */
class Image implements Translatable
{
    /**
     * @var integer
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @Gedmo\Translatable
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var string
     * @Gedmo\Translatable
     * @ORM\Column(name="path", type="string", length=255, nullable=true)
     */
    private $path;

    /**
     * @Assert\File(maxSize="6000000")
     */
    private $file;

    // propriété temporaire old file for delete
    private $tempFileName;

    /**
     * Post locale
     * Used locale to override Translation listener's locale
     * @Gedmo\Locale
     */
    protected $locale;

    /**
     * @var \DateTime
     * @ORM\Column(name="updated_at",type="datetime", nullable=true)
     */
    private $updateAt;

    /**
     * Get id
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set name
     * @param string $name
     * @return Image
     */
    public function setName($name) {
        $this->name = $name;
        return $this;
    }

    /**
     * Get name
     * @return string
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Set path
     * @param string $path
     * @return Image
     */
    public function setPath($path) {
        $this->path = $path;
        return $this;
    }

    /**
     * Get path
     * @return string
     */
    public function getPath() {
        return $this->path;
    }

    /**
     * Sets file.
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null) {
        $this->file = $file;
        if (null !== $this->path) {
            $this->tempFilename = $this->path;
            $this->path = null;
        }
    }

    /**
     * Get file.
     * @return UploadedFile
     */
    public function getFile() {
        return $this->file;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
        if (null !== $this->file) {
            // generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->path = $filename.'.'.$this->file->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        if (null === $this->file) {
            return;
        }
        $this->file->move($this->getUploadRootDir(), $this->path);
        unset($this->file);
    }

    /**
     * @ORM\PostLoad()
     */
    public function postLoad() {
        $this->updateAt = new \DateTime();
    }

    public function getAbsolutePath() {
        return null === $this->path ? null : $this->getUploadRootDir().'/'.$this->path;
    }

    public function getWebPath() {
        $webPath = null === $this->path ? null : $this->getUploadDir().'/'.$this->path;
        return $webPath;
    }

    protected function getUploadRootDir(){
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    public function getUploadDir(){
        return 'upload/images';
    }

    /**
     * Get updateAt
     * @return \DateTime
     */
    public function getUpdateAt(){
        return $this->updateAt;
    }

    /**
     * Set updateAt
     * @param \DateTime $updateAt
     * @return Image
     */
    public function setUpdateAt($updateAt){
        $this->updateAt = $updateAt;
        return $this;
    }

    /**
     * Sets translatable locale
     * @param string $locale
     */
    public function setTranslatableLocale($locale) {
        $this->locale = $locale;
    }

    public function __toString(){
        return $this->getName();
    }
}

**Comment by Audax23** [comment]
i have followed the doc, with the example "How to Upload Files" in the doc of symfony, the file is upload in the good table, so i continue my dev in this sense.
thank you again for your answer, that helps me going in the good way in this project.
