### ISSUE TITLE
@Timestampable/Blameable "on change" does not work on "create" but "on update" does

### ISSUE THREAD

**Issue by sgehrig** [Atlantic18/DoctrineExtensions#1653]
We're using a rather standard setup for timesampable and blameable on one of our entities (documents because we're using MongoDB) with:
- `createdAt` (`@Gedmo\Timestampable(on="create")`)
- `createdBy` (`@Gedmo\Blameable(on="create")`)
- `modifiedAt` (`@Gedmo\Timestampable(on="update")`)
- `modifiedBy` (`@Gedmo\Blameable(on="update")`)

That works as expected. Both `created*` and `modified*` are set when creating a document and `modified*` fields are updated when updating the document. Now we've added an embedded comments collection to the document and we don't want to update the `modified*` fields when a comment has been added/deleted/modified. For that we're using the `@Gedmo\Timestampable(on="change")` and `@Gedmo\Blameable(on="change")` annotations with a list of fields. 

The problem now is that the `modified*` fields are not updated any more when creating the document. That wouldn't be that big of a problem with `Timestampable` because we could easily set the `createdAt` and `modifiedAt` values in the constructor, but with `Blaemable` that's a bigger thing. Of course we could do some things internally such as redirecting the `getModified*` accessors to the `created*` fields if the `modified*` fields are NULL, but that does not solve things like sorting by modified date etc.

Why is it that `on="change"` behaves so differently from `on="update"`? Is there any way around that? Adding two annotations does not work because the annotation drivers for `Blameable` and `Timestampable`call `getPropertyAnnotation()` on the annotation reader which returns only the first annotation of a given type.

**Comment by sgehrig** [comment]
Can someone please shed some light onto this one?

Thanks in advance...

**Comment by l3pp4rd** [comment]
Hi `OneToMany` collections cannot be tracked, because they are changing from the other side `ManyToOne` only. So you either need to track it manually with additional listener where you watch the collection for changes and updating referenced entities. or add on change from the ManyToOne relation side. In general the document does not have any change event triggered (Blameable or Timestampable) when their OneToMany collection changes. These events cannot be tracked that easy, unless you go through all metadata and look which entities has such relations and etc

**Comment by sgehrig** [comment]
We're not using associations to model the `document <-> comments` relationship. `comments` are embedded into the `document`, that's why any changes to comments are being picked up by the `update` listener. 

The only issue here is that when we change the listener to `change` the `modified*` fields aren't initialized any more when creating a document. The rest is working like a charm: the `modified*` fields are only updated when changes occur in the listed fields (that excludes the `comments` field).

**Comment by l3pp4rd** [comment]
if it is related to embedded collection, then it may be the case that this feature is simply not supported yet in extensions. I do not work with PHP anymore, but if you could submit a pull request with such an upgrade to current solution, that would be helpful to others too.

**Comment by sgehrig** [comment]
Never dug that deep into the library, but I'll try my very best. Thanks for getting back to me on this issue.

Is there any other contributor that may be helpful?

**Comment by l3pp4rd** [comment]
whoever is dealing with the same problem. but guess no at this point

**Comment by AkenRoberts** [comment]
Closing in favor of the more recent #2023.
