### ISSUE TITLE
Timestamble works, then no longer works.

### ISSUE THREAD

**Issue by tristanbes** [Atlantic18/DoctrineExtensions#1686]
Hello,

Fair warning, it might be a `apcu`/`opcache`/`php7` bug, but still, i'm posting this if you have an idea / or to help other developper that might encounter this.

At first, `Timestampable` (`gedmo/doctrine-extensions = v2.4.23`)  behaviour works, then, times goes by, and it just stops working. Then we get only 500 error when creating the object that relies on `Timestampable` behaviour.  The *only* way to fix the solution is to restart `php7.0-fpm` service.

````
Doctrine\DBAL\Exception\NotNullConstraintViolationException An exception occurred while executing 'INSERT INTO template_container .... :SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created_at' cannot be null' in ...Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112
```

Our Entity (`TemplateContainerEntity`)  that throws the error looks like looks like:

```php
abstract class TemplateContainerEntity {
    use InheritableEntity;
    ...
}
```

```php
trait InheritableEntity {
    use AnotherTrait;
    ...
}
```

```php
trait AnotherTrait {
    use TimestampableEntity;
    ...
}
```

```php
trait TimestampableEntity
{
    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime", name="created_at")
     */
    protected $createdAt;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", name="updated_at")
     */
    protected $updatedAt;

    /**
     * Sets createdAt.
     *
     * @param  \DateTime $createdAt
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Returns createdAt.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Sets updatedAt.
     *
     * @param  \DateTime $updatedAt
     *
     * @return $this
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Returns updatedAt.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }
}
```

Exact version of php is `PHP 7.0.10` running with `apcu` && `opcache`

**Comment by l3pp4rd** [comment]
if you are always persisting entities through orm and listener is hooked into that instance then I doubt it can be related to extensions. I had few reports before from apcu due to wrong cache, that may be related. though, so many implementations using timestampable mostly and they do not experience such issues. with redis cache backend I have never experienced anything similar. in php most problems are cache problems

**Comment by l3pp4rd** [comment]
can't help you much with that, unless you really find something where cache is missed or similar. currently it always regenerate cache in case of miss and cache concurrent writes are handled by cache implementation in doctrine. most probably the cache entry was spoiled by a leak in apcu as usual.

**Comment by tristanbes** [comment]
ok, closing the issue so. thanks :-)

**Comment by tristanbes** [comment]
Ok, so it might be valuable to add the reason behind this.

**Never use** both `apc_enabled=1` AND `opcache.enable=1` or you will have inconsistent code behaviour after a certain amount of time !

This is what caused this problem. I've been "reproducing" this accross 2 different project, 2 different version of symfony, 2 different servers but both with `APC` and `opcache`enabled.

/ ping @l3pp4rd for information.

**Comment by l3pp4rd** [comment]
whenever there is a **wtf** is in PHP, it is 90% probability of cache issue.

**Comment by do-web** [comment]
Problem still exists....

**Comment by verbold** [comment]
> Problem still exists....
@do-web 

Make sure the extension is properly integrated (or use the [integration bundle](https://github.com/antishov/StofDoctrineExtensionsBundle)). If you're using the integration bundle, ensure `timestampable` is enabled in `config/packages/stof_doctrine_extensions.yaml`, e.g.:

```
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
```
