### ISSUE TITLE
[Tree] `childrenHierarchy` for objects?

### ISSUE THREAD

**Issue by iluuu1994** [Atlantic18/DoctrineExtensions#1687]
I'm looking for a way to fetch a whole mapped tree. I have found nothing in the documentation, the code or the GitHub issues. This seems to be unsupported at the moment. Basically I'm looking for a method like `childrenHierarchy` that returns mapped entities instead of an array.

Could this be achieved with a custom hydrator?
Has anyone tried this before?

I'm guessing that there's some kind of limitation since this has not been implemented?

**Comment by iluuu1994** [comment]
@l3pp4rd I'd really appreciate your input on this one 😃
If I get something working I'll make sure to contribute back.

**Comment by l3pp4rd** [comment]
there is no such option so far. It can be done in ORM but you have to manually build all children collections for each entity if you want to iterate them without triggering ORM on each oneToMany collection. I saw somewhere a similar implementation, but forgot to make such functionality in extensions (there was no need in my case at that point).

**Comment by iluuu1994** [comment]
@l3pp4rd I see, thanks for your input! I've tried a few things. Writing a custom hydrator messed with the mapping of all the other associations while doing it after hydration caused Doctrine to create unnecessary update queries (since it was recognized as a change). 

Anyways, I'll see if I can find a way.

**Comment by l3pp4rd** [comment]
there is a way I'm sure, I've seen it done before. @tyomo4ka maybe you still have some code snippet for it?

**Comment by tyomo4ka** [comment]
@l3pp4rd @iluuu1994 

I can share my code, but it's more complicated. Actually, DQL like this should work fine to get your data in one query. There is no any problem in using custom hydration as well.

```sql

SELECT e, ech
    FROM MyTreeEntity e
    LEFT JOIN t.children ech
WHERE
    ....

```

**Comment by l3pp4rd** [comment]
hm, maybe you could also share the code with hydration to children collections. It might be useful since left joins would produce a much bigger resultset before hydration. or there might be some caveats in combining results. Otherwise we can just put such example with left join in documentation

**Comment by tyomo4ka** [comment]
@l3pp4rd 

Another way is to use native query and custom ResultSetMapping. I actually removed this code from the project and just use the version in previous message. In some cases it can give you better performance I guess, but in my case there is no real economy. As Node entity is tiny, it's just tree structure, w\o actual data in it.

This is another variant, it actually requires two queries. Something like this:

```
        // We select all data using normal DQL, without `LEFT JOIN`

        // Create custom result set mapping
        $rsm = new \Doctrine\ORM\Query\ResultSetMapping;
        $rsm->addEntityResult('St\CoreBundle\Entity\TagNode', 'tn');
        $rsm->addFieldResult('tn', 'id', 'id');
        $rsm->addJoinedEntityResult('St\CoreBundle\Entity\TagNode', 'c', 'tn', 'children');
        $rsm->addFieldResult('c', 'child_id', 'id');

        // Select just tree structure using plain SQL
        $sql = 'SELECT tn.id, c.id AS child_id FROM tag_tree_node tn LEFT JOIN tag_tree_node c ON c.parent_id = tn.id JOIN tag_tree t ON t.id = tn.id WHERE t.project_id = '.$projectId. ' ORDER BY c.lft';
        $query = $this->getEntityManager()->createNativeQuery($sql, $rsm);
        $result = $query->getResult();

        // Mark all children collections as initialised
        foreach($result as $node) {
            if ($node->getChildren() instanceof \Doctrine\ORM\PersistentCollection) {
                $node->getChildren()->setInitialized(true);
            }
        }
```

Not sure if you want to put this into documentation, as it is too low level.

**Comment by l3pp4rd** [comment]
No, I'm thinking to put it into repository ;) thanks ! @iluuu1994 guess it is now possible to put it into repository

**Comment by iluuu1994** [comment]
@l3pp4rd @tyomo4ka 

Yeah but that requires writing a native query, doesn't it?
I found a working (not properly tested) solution using a custom hydrator.

```php
<?php

use Doctrine\ORM\Internal\Hydration\ObjectHydrator;

class TreeHydrator extends ObjectHydrator
{
    protected function hydrateAllData()
    {
        $data = parent::hydrateAllData();
        $childrenHashmap = $this->buildChildrenHashmap($data);
        $this->populateChildrenArray($data, $childrenHashmap);

        // Only return root elements
        // The sub-nodes will be accessible via the `children` property
        return isset($childrenHashmap[null])
            ? $childrenHashmap[null]
            : array();
    }

    protected function buildChildrenHashmap($nodes)
    {
        $r = array();

        foreach ($nodes as $node) {
            $parentId = $node->getParent() !== null
                ? $node->getParent()->getId()
                : null;

            $r[$parentId][] = $node;
        }

        return $r;
    }

    protected function populateChildrenArray($nodes, $childrenHashmap)
    {
        foreach ($nodes as $node) {

            // Mark all children collections as initialized to avoid select queries
            $node->getChildren()->setInitialized(true);

            if (!isset($childrenHashmap[$node->getId()])) { continue; }

            $node->getChildren()->clear();

            foreach ($childrenHashmap[$node->getId()] as $child) {
                $node->getChildren()->add($child);
            }
        }
    }
}
```

This solution requires the `HINT_INCLUDE_META_COLUMNS` query hint.

```php
$widgets = $pages = $em->getRepository(...)
            ->getQuery()
            ->setHint(Query::HINT_INCLUDE_META_COLUMNS, true)
            ->getResult('tree');
```

Obviously this hydrator is not ready for merging into DoctrineExtensions. It assumes that the root nodes will be selected, it implicitly sets `initialized` to `true` on all children collections even though it doesn't know if that is actually the case and it also might waste a lot of memory in large trees. The fact that `HINT_INCLUDE_META_COLUMNS` is required isn't so cool either...

What do you think?

**Comment by iluuu1994** [comment]
Oh and it also doesn't use the meta data cache either, it just assumes there will be `parent` and `children` properties. If you think this is something usable I can flesh it out so we can merge it.

**Comment by l3pp4rd** [comment]
well, you can't assume that children or parent field will be available. you have to use metadata and extension config from it, with reflection to update these properties. the children can be determined by the collection type and class name if it is oneToMany.

**Comment by iluuu1994** [comment]
Yes, as mentioned above I'll do that 🙂

**Comment by iluuu1994** [comment]
[Here's an initial attempt](https://github.com/iluuu1994/DoctrineExtensions/commit/facc94d6297059a91e68eb589efecb2a0d8057e2).

I have not written any tests yet, nor dealt with all of the issues mentioned above. I'll create a pull request once I feel like it's stable and generic enough for the rest of the world.

**Comment by l3pp4rd** [comment]
great, thanks ;) guess many devs will be happy to have this repository method, there were few issues regarding it before

**Comment by oniric85** [comment]
This seems very useful! @iluuu1994 do you have any news? Which are the remaining issues of your PR?

**Comment by iluuu1994** [comment]
@oniric85 Well, a few things:

- The hydrator currently assumes that the whole tree will be returned
- I have no idea how it performs with large data sets (as it builds a large lookup table)
- One has to `->setHint(Query::HINT_INCLUDE_META_COLUMNS, true)` on each query

I might take this up again this weekend and create a PR.

**Comment by oniric85** [comment]
I'm not concerned too much about the large data sets but I'm not sure what HINT_INCLUDE_META_COLUMNS is for. Any clue? Also, does your hydrator work for NestedSet trees to supported by this extension?

**Comment by iluuu1994** [comment]
@oniric85 Doctrine omits some meta data for non-object hydrators. In this case, I assume that the primary key of the parent is accessible. Unfortunately, only the actual `ObjectHydrator` class gets this meta data. This seems to be hard coded [right here](https://github.com/doctrine/doctrine2/blob/09cbb9ff48f00003f8708a67d937e6b2d86cdce3/lib/Doctrine/ORM/Query/SqlWalker.php#L708).

So unless you set that query hint, the hydrator won't be able to figure out which `id` the parent has and thus won't be able to build the tree.

**Comment by iluuu1994** [comment]
@oniric85 

> Also, does your hydrator work for NestedSet trees to supported by this extension?

And yes, that's it's exactly its purpose. It'll be able to build a tree for any tree strategy.

**Comment by iluuu1994** [comment]
I created an [issue](https://github.com/doctrine/doctrine2/issues/6396) in the Doctrine repository. Maybe they can help us out.

**Comment by oniric85** [comment]
Thank you @iluuu1994 for the clarifications! In the meantime I'll try your custom hydrator and see if I find any issue with it ;)

**Comment by iluuu1994** [comment]
@oniric85 I made some adjustments. The performance looks decent with large trees. Nobody should expect incredible performance with an ORM anyway. Fetching subtrees now works too. The only issue to be tackled now is the query hint.

**Comment by l3pp4rd** [comment]
the hint is not that bad if documented, translatable already uses some of the hints. users can hide that within their repositories ;)

**Comment by oniric85** [comment]
I guess so, yes. Also I don't think Doctrine maintainers are going to change that part any soon.

@iluuu1994 can you perhaps give a short example of how one should use the custom hydrator?

**Comment by iluuu1994** [comment]
Have a look at the TreeObjectHydratorTest class. I'll add a section to the documentation later.

**Comment by oniric85** [comment]
I see now, thank you!

**Comment by iluuu1994** [comment]
@oniric85 Ok, let me know how it works out.

**Comment by oniric85** [comment]
Just a quick update, using the custom Hydrator for almost a week and no issues so far. Good work! It would be nice to have this added to the repo, not sure if I would enable it by default though (of course in a new major version of the extension). What do you think @l3pp4rd?

**Comment by iluuu1994** [comment]
@oniric85 AFAIK DoctrineExtensions doesn't enable anything by default. There are other repos like [StofDoctrineExtensionsBundle](https://github.com/stof/StofDoctrineExtensionsBundle) that do that on a framework basis.

**Comment by oniric85** [comment]
I mean, the default hydrator used by the childrenHierarchy method :)

**Comment by iluuu1994** [comment]
@oniric85 Oh sorry, that makes sense. Yes, that would break BC and thus should be done in a new major version.
