### ISSUE TITLE
[Tree] The order of top level rootless nodes is incorrect

### ISSUE THREAD

**Issue by iluuu1994** [Atlantic18/DoctrineExtensions#1688]
When using a tree entity that has no `root` property ([as instructed here](https://github.com/Atlantic18/DoctrineExtensions/issues/451#issuecomment-8225672)) DoctrineExtensions should treat your table as one whole tree, thus allowing nodes on the top-level to be sorted.

Unfortunately, in this case the the order of the nodes is persisted incorrectly. The node is always persisted last, no matter which of the following methods is used:
- `persistAsFirstChild`
- `persistAsLastChild`
- `persistAsNextSiblingOf`
- `persistAsPrevSiblingOf`

I've created a [fork](https://github.com/iluuu1994/DoctrineExtensions/tree/v2.4.x) and added a unit test to demonstrate the problem. The issue can be reproduced in both the `v2.4.x` and the `master` branch. I've also tried to find the bug but [felt a little lost](http://i1.kym-cdn.com/photos/images/facebook/000/234/765/b7e.jpg). These are the things I found:
1. The `Nested` strategy class [seems not to handle](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Strategy/ORM/Nested.php#L392) this case (as there is no switch case as above)
2. Several calls to `Nested::updateNode` don't pass the `$position` parameter (defaults to `'FirstChild'` or pass a hard coded value [[1](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Strategy/ORM/Nested.php#L166)] [[2](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Strategy/ORM/Nested.php#L168)] [[3](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Strategy/ORM/Nested.php#L181)]

I'm down to helping investigate this issue but I fear that my knowledge is not sufficient for finding this bug. Any help would be appreciated.

**Comment by l3pp4rd** [comment]
Hi, I have left the php world, but from the looks in [location you gave](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Strategy/ORM/Nested.php#L392) the edge always take the LAST CHILD position. It should build a gap with shiftRL method and make there some space for new node like this [switch](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Strategy/ORM/Nested.php#L338), so it looks like a bug. The nested set implementation is very easy, but managing it with ORM becomes too complex, all small changes takes much time to implement. I think you would spend much of the time to make this fix, that is why there are so many users but not much of the contributors and not many of behaviors for ORM from other parties.

**Comment by iluuu1994** [comment]
I got it working [here](https://github.com/iluuu1994/DoctrineExtensions/commit/4c8300ce4cdf4b810b25f40ea911832f76265958).
I'd be really happy if someone could skim though it to make sure I did nothing stupid. 😅

**Comment by iluuu1994** [comment]
My fix seems not to work on `master`. I'll check it out tonight and get back to you.

**Comment by mneuhaus** [comment]
any chance to get a bugfix tag for this ? :)

**Comment by iluuu1994** [comment]
@mneuhaus This bug is fixed but it has not been released yet. The issue with the `master` branch was fixed and merged in #1692.

**Comment by mneuhaus** [comment]
yea, i know, that's why i asked for a bugfix tag, in order to avoid a dev-master in my composer ;)

**Comment by iluuu1994** [comment]
@mneuhaus Oh sorry, my bad. I misread your question. 😅 Yeah I think this is safe to be tagged after two months without any issues 👍

**Comment by iluuu1994** [comment]
@mneuhaus The tag has been created, can you confirm that this solves the issue?

**Comment by mneuhaus** [comment]
yea, thanks :)
