### ISSUE TITLE
Xml definition not up to date

### ISSUE THREAD

**Issue by nxtvibe** [Atlantic18/DoctrineExtensions#1695]
tree-path is not up to date in 
http://Atlantic18.github.io/DoctrineExtensions/schemas/orm/doctrine-extensions-3.0.xsd

Need to add it to list of fields and also update attributes.

``` xml
<xs:element name="tree-path" type="gedmo:tree-path"/>

<xs:complexType name="tree-path">
    <xs:attribute name="separator" type="xs:string" use="optional" default="|" />
    <xs:attribute name="append_id" type="xs:boolean" use="optional" default="false" />
    <xs:attribute name="starts_with_separator" type="xs:boolean" use="optional" default="false" />
    <xs:attribute name="ends_with_separator" type="xs:boolean" use="optional" default="false" />
  </xs:complexType>
```

**Comment by l3pp4rd** [comment]
this version is for master branch. use one from v2.4.x if you are using stable tag release. in case if you are using master **dev-master** in composer, then could you explain it in more detail?

**Comment by nxtvibe** [comment]
Hi,

I am using dev-master in composer, and php-storm is complaining that tree-path (and tree-path-hash) is not defined in doctrine-extensions-3.0.xsd

I might be doing something wrong here, because tree-path, tree-path-source, and tree-path-hash always return NULL or an empty string. I've set up the following in the mapped superclass xml config file.

```xml
<field name="path" type="text" nullable="true"><gedmo:tree-path append_id="true" separator="|" starts_with_separator="false" ends_with_separator="false" /></field>
<field name="treePathSource" type="integer" nullable="true"><gedmo:tree-path-source/></field>
<field name="treePathHash" type="text" nullable="true"><gedmo:tree-path-hash/></field>
```

I also noticed that tree-path-hash did not make it through the tree XML driver and should probably be added on line 143.
```php
elseif (isset($mapping->{'tree-path-hash'})) {
    if (! $validator->isValidFieldForPathSource($meta, $field)) {
        throw new InvalidMappingException("Tree PathHash field - [{$field}] type is not valid and must be 'string' in class - {$meta->name}");
    }
    $config['path_hash'] = $field;
} 
```

**Comment by nxtvibe** [comment]
Path returned NULL because I didn't change nested to materializedPath. My bad on that one :)
