### ISSUE TITLE
Problem with translation and zf3

### ISSUE THREAD

**Issue by joepsyko** [Atlantic18/DoctrineExtensions#1699]
After migrating my zf2 project to zf3 I encountered a strange behavior with translation.

The documentation says:

```
$article = $em->find('Entity\Article', 1 /*article id*/);
$article->setLocale('ru_ru');
$em->refresh($article);
```

And that was working perfectly with zf2.

Here is the problem, when i try to do same think with zf3 the refresh simply empties all the fields of the entity.

Here are some cases:

**entity with only default language**
accessing default language -> empty
accessing a translation -> empty

**entity translated**
accessing default language -> empty
accessing translation -> returned correctly

Any suggestion?

**Comment by l3pp4rd** [comment]
can't help you, I do not use zf3. probably something with the integration. you'll have to debug this or maybe someone else could share their experience.

**Comment by joepsyko** [comment]
Ok, I think I figure out the problem, I was adding the listener two times.

For  an unknown reason zf2 doesn't complain for that.
