### ISSUE TITLE
Sluggable: force non-empty slug

### ISSUE THREAD

**Issue by miguelrs** [Atlantic18/DoctrineExtensions#1702]
I have an entity with a `slug` defined like:
```
slug:
    type: string
    nullable: false
    gedmo:
        slug:
            fields: [label]
            unique: true
            unique_base: someAssociation
            updatable: false
label:
    type: string
    nullable: false
```
The problem is I want to allow the `label` to be something like `...`, `?` or even an emoji - all those labels are leading to an empty slug `''`, and I want the slugs to be always non empty...    
For example, I'd expect for a label like `...` to get a slug like `1`.

I guess I can add a prefix/suffix, but wanted to avoid that if possible. Or I could write a custom handler, but seems too much effort for this...

Any other option?

**Comment by l3pp4rd** [comment]
you can implement your [own slug transliterator](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/sluggable.md#transliterator)

**Comment by miguelrs** [comment]
ok thanks @l3pp4rd I did create a custom transliterator. It looks something like this if someone is interested:

```
class Transliterator
{
    /**
     * @param string $text
     * @param string $separator
     * @param object $object
     * @return string
     */
    public static function transliterate($text, $separator, $object)
    {
        // Urlizer is what Sluggable uses to generate the slug.
        $generatedSlug = Urlizer::transliterate($text, $separator);

        // If generated slug is empty, try to use the short class name.
        if ($generatedSlug === '') {
            $className = (new ReflectionClass($object))->getShortName();
            // Regexp to convert CamelCase to snake_case from http://stackoverflow.com/a/19533226/1813625.
            // It does not cover all possibilities perfectly, but I don't care that much.
            $generatedSlug = preg_replace('/(?<!^)[A-Z]+/', ' $0', $className);
            $generatedSlug = Urlizer::transliterate($generatedSlug, $separator);
        }

        // At this point the slug should never be empty at all, but just in case...
        if ($generatedSlug === '') {
            $generatedSlug = 'reference';
        }

        // The returned slug will still be made unique by Sluggable after this point if specified!
        return $generatedSlug;
    }
}
```

Then I needed to figure out how to make this work with Symfony, which I found in [sf.khepin.com](http://sf.khepin.com/2012/01/doctrine-sluggable-and-transliteration/).  
Basically you cannot tell it to use your custom Transliterator directly, so you need to write a custom Listener that uses your custom Transliterator, and then register that Listener in Symfony config.

**Comment by l3pp4rd** [comment]
if you do not use doctrine extensions bundle, then you can simply call setTransliterator on you service configuration if you follow the [documentation for symfony2](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/symfony2.md#doctrine-extension-listener-services) the bundle makes listeners private and that sometimes gets in your way

**Comment by l3pp4rd** [comment]
I will not integrate custom transliterators in this library, because different use cases require different implementations it would be too complicated to choose the one fitting your needs. (too custom)

**Comment by miguelrs** [comment]
What I mean is it may be useful to have some option (e.g., `nullable`) to force slugs to be not empty.  
In my project, I use slugs almost like IDs - that's why I don't want just a string I generate myself and I instead require the fancy Sluggable features like `unique`, `uniqueBase`, etc...   

```
mySlug:
    column: my_slug
    type: string
    nullable: false
    gedmo:
        slug:
            fields: [label]
            unique: true
            nullable: false
```

What's the best and most generic way to generate a slug when the `label` leads to an empty slug? I don't know... for me, even having the field name/column (i.e., `mySlug`) would be alright... or the entity/table name... whatever other than an empty string!

Anyway I was thinking that was a major issue, but if nobody else requested this, maybe it's just me ;)

**Comment by l3pp4rd** [comment]
so far it is only just you. if I'll add too many options into the library, it will be hard to understand which to choose for everyone using the library.

**Comment by miguelrs** [comment]
Just as a funny side note - we have been using Sluggable for longer than a year and it was always wrong (for us), but we didn't notice until someone tried to create a thing with an emoji as the label...
So I'd bet that although I'm the first to point it out, many people relying on slugs and allowing any character in the label, are potentially in danger, but they don't even know 😄 
Anyway, thanks for the help, and nice library ⭐️
