### ISSUE TITLE
Issue with persistAs...SiblingOf 

### ISSUE THREAD

**Issue by yellow1912** [Atlantic18/DoctrineExtensions#1703]
Right now, if I want to persist a node as sibling of another node which has a parent that does not have any parent then I run into this error:

> Cannot persist sibling for a root node, tree operation is not possible

Looking closer at the code, I see something like this

```
$newParent = $wrappedParent->getPropertyValue($config['parent']);
                        if (is_null($newParent) && (isset($config['root']) || $isNewNode)) {
                            throw new UnexpectedValueException("Cannot persist sibling for a root node, tree operation is not possible");
                        }
```

Not sure why we want to get the parent of the parent here, it doesn't seem to make any sense unless I understand the code wrong?

**Comment by l3pp4rd** [comment]
it is not possible tree operation when there is a root configured. do not use TreeRoot for such behavior. all root nodes are like separate trees.

**Comment by yellow1912** [comment]
@l3pp4rd Thank you very much for your reply. Can you please explain to me in more details what you meant by "do not use TreeRoot for such behavior"?

In my current setup, this is what I have in the database:

1. Node 1: no parent, root null
2. Node 2: parent is node 1, root is null
3. Node 3: parent is node 2, root is null

I tried to move node 3 to be sibling of node 2 and this error happens. I tried to manually set root for node 2 and 3 to be node 1 as well but that also did not help.

**Comment by l3pp4rd** [comment]
in your tree entity, you use `@TreeRoot` annotation mapping, this causes a tree to have root nodes as separate trees.

**Comment by Viburnum** [comment]
Same issue here. The cause of all evil were the magic methods __get() and __set() in our entity. This annihilates the following call in the NestedSetRepository:

https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Tree/Entity/Repository/NestedTreeRepository.php#L113 

Our 'solution' was to add a public property 'sibling' to the entity.
