### ISSUE TITLE
Loggable: Add support for collections using SoftDeleteable

### ISSUE THREAD

**Issue by kierzniak** [Atlantic18/DoctrineExtensions#1711]
I'm assuming that log entity association with loggable is hard to implement because:

- storing associations as serialized object is not a good idea 
- logged association entity can no longer exists

Nevertheless I think it is possible to do using SoftDeleteable extension. We can store associations as serialized array of ids and there won't be problem with data integrity.

This is rather a feature request and an invitation to discussion rather than issue.

**Comment by l3pp4rd** [comment]
I do not think there will be any new features in extensions any time soon and it is good because people can expect backward compatibility. For extensive logging you can use https://github.com/DATA-DOG/DataDogAuditBundle

**Comment by kierzniak** [comment]
Thank you. I think this bundle will satisfy my needs.

However I don't think this would break backward compatibility. This change will have impact only on associations which I suppose no one is using, because Loggable is simply not working with it.
