### ISSUE TITLE
Cleanup issues and PR's

### ISSUE THREAD

**Issue by stephanvierkant** [Atlantic18/DoctrineExtensions#1713]
There are right now 332 open issues and 59 open pull request. That seems like a hell of a lot, but my impression it that most of them are questions, features requests or already fixed issues.

I'd like to contribute, but I don't know where to start. Maybe we should start labeling issues (295 issues are unlabeled), close very old questions, etc. If I can help, please let me know!

**Comment by l3pp4rd** [comment]
Hi @stephanvierkant I do not work with PHP anymore, that makes it very hard to maintain this repository. I'm trying to keep it stable, that is all. If you wish to contribute, that is great. but I would not like to introduce backward incompatible changes. Anyway, added you to contributors, you may find something interesting to get your hands on, maybe refactor some portions of code. The master branch is somewhat staying at the same state, where 3.0.0 version was being prepared, but it stayed like that for long time.

**Comment by Padam87** [comment]
@l3pp4rd Would it be a good idea, to split this into multiple repositories? It would definitely take some doing, but there is a huge upside.

- Individual libs could improve much faster.
The 3.0 branch has a lot of good stuff, but it will never be finished. No one is capable of handling this in their spare time, and I don't think anyone is willing to take this project on company time, but lets hope I'm wrong.

- The project could have separate maintainers per extension.
I think more people would be willing to help if they would only be responsible for a small piece. I would be willing to take sortable, which I know pretty well.

- A couple of extensions could be dropped.
I would propose dropping
**uploadable** (and recommending vich uploader for symfony projects, and writing an article about doctrine uploads for non sf users),
**translatable** (drop this, ask the knp guys to contribute theirs, which is better supported by other bundles)

What do you think?

**Comment by stephanvierkant** [comment]
See #2002
