### ISSUE TITLE
Sluggable: use an unique_base array instead of string

### ISSUE THREAD

**Issue by raphaelriehl** [Atlantic18/DoctrineExtensions#1720]
I would like use an unique_base array instead of a string.
For example I have this entity (Content) with these fields:
- id
- slug
- title
- type (type.id)
- site  (site.id)
- ...

And I want a slug unique defined by type and site.
For example:

| Title | Slug   | Site   | Type |
|--|--|--|--|
| This is my title | this-is-my-title | 1 | 1 |
| This is my title | this-is-my-title | 1 | 2 |
| This is my title | this-is-my-title | 2 | 1 |
| This is my title | this-is-my-title | 2 | 2 |
| This is my title | this-is-my-title-1 | 1 | 1 |
| This is my title | this-is-my-title-2 | 1 | 1 |
| This is my title | this-is-my-title-3 | 1 | 1 |
| This is my title | this-is-my-title-1 | 1 | 2 |

The result in annotation:
unique_base={"site", "type"}

What do you think of my problem ? Is it possible to implement this feature ?

**Comment by l3pp4rd** [comment]
Hi, this cannot be accepted, too custom use case. And I have mentioned that there won't be new features accepted any time soon

**Comment by raphaelriehl** [comment]
Ok no problem. Thank you for the answer.
