### ISSUE TITLE
[Sortable] Nesting level too deep - recursive dependency?

### ISSUE THREAD

**Issue by yellow1912** [Atlantic18/DoctrineExtensions#1726]
Symfony Version: 3.1
DoctrineExtensions Version: master (as of the posted date of this message)

The above error is thrown from line 464 of the SortableListener

```php
// Special case for equal objects but different instances.
                                $matches = $gr == $value;
```

I have a simple "comment" table with each record self-linked to a parent "comment" via a column named "parent_id". If I set this parent field as sortable-group I will get the nesting level too deep issue on the 2nd child insert.

A stripped down version of 
```xml
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:gedmo="http://gediminasm.org/schemas/orm/doctrine-extensions-mapping">
<mapped-superclass name="Comment" table="Comment">
<id name="id" type="integer" column="id">
            <generator strategy="AUTO" />
        </id>
<field name="name" column="name" type="string" length="255" />
<field name="position" column="position" type="integer">
            <gedmo:sortable-position />
        </field>
<one-to-many field="children" mapped-by="parent" target-entity="CommentInterface">
            <cascade>
                <cascade-persist />
            </cascade>

            <order-by>
                <order-by-field name="position" direction="ASC"/>
            </order-by>
        </one-to-many>

<many-to-one field="parent" inversed-by="children" target-entity="CommentInterface">
            <cascade>
                <cascade-persist />
            </cascade>

            <join-column name="parent_id" referenced-column-name="id" on-delete="CASCADE" nullable="true" />
            <gedmo:sortable-group />
        </many-to-one>
</mapped-superclass>
</doctrine-mapping>
```

Some sample code to describe the steps to reproduce the issue:

```php
// create parent $parent
// create child 1
// set parent for child 1
$child1->setParent($parent);
// save and flush
// create child 2
// set parent for child 2
$child2->setParent($parent);
// save and flush --> fatal error here
```

My guess is that when we do comparison of these 2 objects that share the same parent we are triggering a circular reference?

A simple hack like this seems to solve the issue:

```php
// since I know these objects have the getId method I applied this hack just to see if it works
$matches = $gr == $value;
```

Looking forward to suggestions and advises from someone with more knowledge regarding this issue.

**Comment by yellow1912** [comment]
Inspired by https://wiki.php.net/rfc/comparable, I added a Comparable interface to sortable, then I simply check

``php
if ($gr instanceof Comparable) {
                                    $matches = $gr->compareTo($value);
                                } else {
                                    $matches = $gr == $value;
                                }
```

Not exactly elegant but it gets the job done. If this is considered a valid fix then I can submit a PR.

**Comment by l3pp4rd** [comment]
the interface is only for php 7, extensions are backwards compatible and it will not change anymore. we could consider using === to compare value (will compare object hashes in your case), but I doubt that it will not break BC. though it should not to, since the culumn has a specific type.

**Comment by yellow1912** [comment]
The interface is php7 but we do not need php7 at all. What I did was simply adding that interface directly into the Sortable folder. Any object wishes to use custom comparison simply has to implement that new interface from Sortable only.

**Comment by yellow1912** [comment]
I pushed up the initial PR for this. I can add to the documents for you as well.

If you want, I can also push a separate PR for the master branch which seems to be used in the newer Doctrine version.
