### ISSUE TITLE
Sudden issue with Gedmo, worked fine until today

### ISSUE THREAD

**Issue by Ivan0905** [Atlantic18/DoctrineExtensions#1731]
Hi, when I try to push my changes to my remote env, I am getting this error:

>   An error occurred when executing the "'cache:clear --no-warmup'" command:    
>   PHP Fatal error:  Uncaught exception 'Doctrine\Common\Annotations\AnnotationException' with message '[Semantical Error] The annotation "@\Gedmo\Mapping\Annotation\Timestampable" in property App\CoreBundle\Entity\AbstractSlider::$updatedAt does not exist, or could not be auto-loaded.' in /masked/Annotations/AnnotationException.php:54  

I have another developer who also started getting it in his projects today.

**Comment by l3pp4rd** [comment]
maybe you have updated some of your composer dependencies (which might have been broken), otherwise it may be due to cache. If it had something to do with extensions a lot more people would have raised that before.

**Comment by shengjie-chez-agriconomie** [comment]
we have same issue when using composer.phar version 1.3.0

**Comment by mrardon** [comment]
I had the same issue and the downgrade of composer solved it.

**Comment by l3pp4rd** [comment]
does it solve the problem if you include https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Mapping/Annotation/All.php in the startup of your application main php file? that may be related to the autoloading in some strange way..

**Comment by mrardon** [comment]
It definitely appears to be something with the autoloading. I use Symfony3 and manually added the following before the return in `app/autoload.php` (https://github.com/symfony/symfony-standard/blob/master/app/autoload.php).

```
AnnotationRegistry::registerFile(__DIR__ . '/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/Annotation/Slug.php');
AnnotationRegistry::registerFile(__DIR__ . '/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/Annotation/SlugHandler.php');
AnnotationRegistry::registerFile(__DIR__ . '/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/Annotation/SlugHandlerOption.php');
AnnotationRegistry::registerFile(__DIR__ . '/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/Annotation/SoftDeleteable.php');
AnnotationRegistry::registerFile(__DIR__ . '/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/Annotation/Loggable.php');
AnnotationRegistry::registerFile(__DIR__ . '/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/Annotation/Timestampable.php');
AnnotationRegistry::registerFile(__DIR__ . '/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/Annotation/Versioned.php');
```

This obviously felt wrong so I tried downgrading to composer 1.2.4 and don't need this anymore.
