### ISSUE TITLE
slug generation bug

### ISSUE THREAD

**Issue by eventhorizonpl** [Atlantic18/DoctrineExtensions#1739]
Hi,

`
    /**
     * @var string
     *
     * @Assert\Type(type="string")
     * @Gedmo\Slug(fields={"title"}, updatable=false)
     * @ORM\Column(length=255, name="slug", type="string", unique=true)
     */
    private $slug;
`

I create a post with title 'di 1' - generated slug is 'di-1'. Next I create a post with title 'di' - generated slug is 'di'. Next I create a post with title 'di' - generated slug is 'di-1'. I get an error
`
'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'di-1' for key 'UNIQ_5A8A6C8D989D9B62''
`
Shouldn't slug generation procedure check if generted slug actually exist in database?

Best regards,
Michal

**Comment by l3pp4rd** [comment]
hm, that is interesting, it should check it, do you generate all these slugs in one transaction?

**Comment by eventhorizonpl** [comment]
no. I just create a separate documents from the website ui. let me know if you need additional details about configuration. I use StofDoctrineExtensionsBundle 1.2.2 with DoctrineExtensions 2.4.2.

it works completly fine if I create a few documents with title 'foo' - slugs are properly created.

**Comment by eventhorizonpl** [comment]
@l3pp4rd 

Any progress with this issue? One user already triggered this in production.

**Comment by l3pp4rd** [comment]
well, I do not work with php for a while already, but I'll probably find some time to have a look, thanks for reminding ;)

**Comment by eventhorizonpl** [comment]
thank you!

**Comment by l3pp4rd** [comment]
maybe you softdeleted it, or somehow skipped it in select sluggable does. anyway, unless you can prove the test being wrong
