### ISSUE TITLE
[translatable] use personal translation has pivot table

### ISSUE THREAD

**Issue by lalop** [Atlantic18/DoctrineExtensions#1763]
I'm building a Menu which has a oneToMany relation with MenuEntry.
Each translation have different entries and not a translation of the entries.
I can't find a way to attach my entries to my menu through the translation entity.
Reading the documentation it seems like we can't define different relation for different language, am I wrong ?

**Comment by l3pp4rd** [comment]
personal translations have direct relation and an entry per translated field. you can create such translations manually.

**Comment by lalop** [comment]
ok I see, Is there some interface in this bundle that I should implement to declare my object has translatable or not at all ?

**Comment by l3pp4rd** [comment]
read the documentation in **doc** directory
