### ISSUE TITLE
Slugging of Czech character "Ý"

### ISSUE THREAD

**Issue by lukaszach** [Atlantic18/DoctrineExtensions#1784]
I found a problem when I run my application's tests. 

I have easy use cases test Class shown below.

The problem comes when I slugify string "ÝýÚÝ", expected is "yyuy" but returned is "uyuy". For character "Ý" should be slug "y", not "u".

<?php

namespace Ensis\Bundle\CmsCoreBundle\Repository\Structure;

use Ensis\Bundle\CmsCoreBundle\Entity\Structure\Category;
use Liip\FunctionalTestBundle\Test\WebTestCase;

class CategoryRepositoryTest extends WebTestCase
{
    /**
     * @var EntityManager
     */
    private $em;

    /**
     * @var Container
     */
    private $container;

    /**
     * {@inheritdoc}
     */
    protected function setUp()
    {
        $this->loadFixtures(array());

        $this->container = $this->getContainer();
        $this->em = $this->container->get('doctrine')->getManager();
    }

    /**
     * {@inheritdoc}
     */
    protected function tearDown()
    {
        parent::tearDown();

        $this->em->close();
        $this->em = null; // avoid memory leaks
    }

    /**
     * @dataProvider setGetCategoryGenerator
     *
     * @param $title
     * @param $extraTitle
     * @param $enabled
     * @param $description
     * @param $keywords
     * @param $rewriteUrl
     * @param $slugTest
     */
    public function testSetGetCategory($title, $extraTitle, $enabled, $description, $keywords, $rewriteUrl, $slugTest)
    {
        $category = new Category();

        $category->setTitle($title);
        $category->setTitleExtra($extraTitle);
        $category->setEnabled($enabled);
        $category->setDescription($description);
        $category->setKeywords($keywords);
        $category->setRewriteUrl($rewriteUrl);

        $this->em->persist($category);
        $this->em->flush();

        $this->assertEquals($slugTest, $category->getSlug());
    }

    /**
     * @return \Generator
     */
    public function setGetCategoryGenerator()
    {
        $data = ['extraTitle' => 'test 2', 'enabled' => true, 'description' => 'scalar', 'keywords' => 'one, two, three, four', 'rewriteUrl' => 'rewrite'];
        yield array_merge(['title' => 'Title one'], $data, ['slugTest' => 'title-one']);
        yield array_merge(['title' => 'Title 3"!'], $data, ['slugTest' => 'title-3']);
        yield array_merge(['title' => 'Žluťoučký kůň'], $data, ['slugTest' => 'zlutoucky-kun']);
        yield array_merge(['title' => '!Řehtání, čekání, žvýkání, kašlání, kůl, úl + květináč'], $data, ['slugTest' => 'rehtani-cekani-zvykani-kaslani-kul-ul-kvetinac']);
        yield array_merge(['title' => '+ě š č ř ž ý á í é = ú +ĚŠČŘŽÝÁÍÉ=Ú-ÝýÚÝ'], $data, ['slugTest' => 'e-s-c-r-z-y-a-i-e-u-escrzyaie-u-yyuy']);
    }
}

**Comment by l3pp4rd** [comment]
can you try current v2.4.x branch

**Comment by lukaszach** [comment]
Hi, I have version 2.4.28, I also tried 2.4.27. Both don't work well.

**Comment by l3pp4rd** [comment]
Well, in that case, the only option you have is to customize transliteration, by implementing custom method to transform slug https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/sluggable.md#transliterator

**Comment by lukaszach** [comment]
Hi, this works for me, thanks.
