### ISSUE TITLE
[Sortable] Impossible to use if added to existing table

### ISSUE THREAD

**Issue by NVasse** [Atlantic18/DoctrineExtensions#1789]
Hello,

I'm stuck with a problem for which I still haven't found a solution.
I have added the sortable on an **already existing table** which resulted in all the positions being set to ``NULL``.
Now if I try to manually update any position it won't work.
I tried setting each position to ``-1``, to an ``incremented int``, to ``NULL``, I tried flushing after every persist, after all the persists. Nothing worked so far, it always results in positions set to ``0`` or ``-1``.

Any help would be appreciated.

**Comment by l3pp4rd** [comment]
Hi, just use a plain sql query to update positions based on your simple initial sorting strategy. Then use sortable to manage new and current positions. If you use ORM, do not forget the good old SQL, believe me, that will come in handy. By default, extensions do not ship any migration commands, there are simply too many options to cover for such task.

**Comment by NVasse** [comment]
Alright, thanks.
Wouldn't there be a way to specify that we want to manually force the position without the listener doing its job or maybe take into account the ``NULL`` value in the logic to set the position ?

**Comment by Padam87** [comment]
A simple SQL should do the trick.

```sql
SET @current = -1;
UPDATE sortable_entity SET sortable_field=(@current:=@current+1);
```

**Comment by ln-e** [comment]
But what if i'm using sortable with SortableGroup?

**Comment by Padam87** [comment]
@ln-e You should create a custom migration for that. Doctrine migrations allows you to use container, so you can use the entity manager. You can also write a console command.

Make sure you disable the listener before updating entities, and set the position manually.

**Comment by k3rn3l3rr0r** [comment]
@Padam87 Just for heads up - this issue here helped me a lot to get things working on my end... After few hours of helpless debugging and searching around the web, while retrofitting Sortable functionality into my existing project. It should probably be stated somewhere visible - maybe directly as a part of the documentation of the Sortable extension.

**Comment by callistino** [comment]
I wanted to leave this here for future reference. This is the migration sql I used to add to an existing table when using with SortableGroup:

```sql
-- ------------------------------------------
-- Add new sort "position" field
-- ------------------------------------------
ALTER TABLE table_name
    ADD COLUMN `position` INT DEFAULT 0 NOT NULL;

-- ------------------------------------------
-- Update newly added "position" field 
-- ------------------------------------------
DELIMITER $$

DROP PROCEDURE IF EXISTS UpdateSortPositionByGroup;
CREATE PROCEDURE UpdateSortPositionByGroup()

BEGIN
    DECLARE done INT DEFAULT FALSE;
    DECLARE groupId INT;

    -- declare cursor for group id found inside table_name
    DECLARE groupIdCursor
        CURSOR FOR
        SELECT DISTINCT group_id
        FROM table_name;

    -- declare NOT FOUND handler
    DECLARE CONTINUE HANDLER
        FOR NOT FOUND SET done = TRUE;

    OPEN groupIdCursor;
    updatePositionLoop: LOOP
        FETCH groupIdCursor INTO groupId;
        IF done THEN
            LEAVE updatePositionLoop;
        END IF;

        SET @position = -1;
        UPDATE table_name
        SET position = (@position := @position + 1)
        WHERE group_id = groupId
        ORDER BY field;

    END LOOP updatePositionLoop;
    CLOSE groupIdCursor;
END$$

CALL UpdateSortPositionByGroup();
DROP PROCEDURE UpdateSortPositionByGroup;

DELIMITER ;


```
