### ISSUE TITLE
latest tag 2.4.28 blocks updating behat/behat

### ISSUE THREAD

**Issue by roelmonnens** [Atlantic18/DoctrineExtensions#1792]
Because of the dependency in v2.4.28 to behat/transliterator:1.1 I'm not able to update behat/behat to the latest code.

Could you please create another release of `master` because there it is fixed.
![fix in master](https://www.dropbox.com/s/9uutcx5kpm2ar8v/Screenshot%202017-05-30%2016.23.45.png?dl=1)

**Comment by gvanbeck** [comment]
+1
