### ISSUE TITLE
[Translation] TranslationWalker walkWhereClause issue

### ISSUE THREAD

**Issue by romain-pierre** [Atlantic18/DoctrineExtensions#1797]
Hi all, I suspect an issue with the where clause replacement. First of all, this is the current behaviour:

I have an entity with a slug parameter that is _translated_. I would like to make a query with a where statement to select by the translated slug and the current locale. Locale and slug parameters are set properly.

```php
        $q = $this
            ->createQueryBuilder('p')
            ->where('p.slug = :product')
            ->setParameter('product', $product)
            ->getQuery()
        ;

        $q->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, TranslationWalker::class);
```

Resulting query is (name, description and slug fields are marked as translated in annotations):

```sql
SELECT p0_."id" AS id_0, p0_."name" AS name_1, p0_."description" AS description_2, p0_."slug" AS slug_3, p0_."price" AS price_4, p0_.category_id AS category_id_5 FROM "product" p0_
LEFT JOIN "ext_translations" t1_ ON t1_.locale = 'fr' AND t1_.field = 'name' AND t1_.object_class = 'AppBundle\Entity\Product' AND t1_.foreign_key = p0_.id::VARCHAR
LEFT JOIN "ext_translations" t2_ ON t2_.locale = 'fr' AND t2_.field = 'description' AND t2_.object_class = 'AppBundle\Entity\Product' AND t2_.foreign_key = p0_.id::VARCHAR
LEFT JOIN "ext_translations" t3_ ON t3_.locale = 'fr' AND t3_.field = 'slug' AND t3_.object_class = 'AppBundle\Entity\Product' AND t3_.foreign_key = p0_.id::VARCHAR
WHERE p0_."slug" = 'french-slug';
```

As you can see the where statement targets the original slug value (instead of `t3_."content"`).
What do you think about this?

Thank you in advance,
Romain

**Comment by l3pp4rd** [comment]
Hi, it might be due to cache, try adding a hint for locale to the same query. it is explained in docs regarding query cache, with examples. there are tests which covers all query component translations including where statements. If the cache is not an issue, try creating a failing test case in a PR.

**Comment by romain-pierre** [comment]
Hi, thanks for your reply. I don't think the cache is in cause because I was clearing (rm -rf and redis flush) at each page call to be sure of that. I will re-re-re-read the doc again and re-check the behaviour to be sure.

**Comment by romain-pierre** [comment]
Ok, the issue come from [here](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Translatable/Query/TreeWalker/TranslationWalker.php#L425).

I'm applying a custom quote strategy on the column names to allow usage of reserved keywords. Under PostgreSQL, my quoting strategy adds `"` characters.

The replacement method try to find `c0_.slug` but with the quoting, the expression is `c0_."slug"`. So I think there is a _real_ bug here. I think (and if it's possible), we have to apply the strategy before the replacement. If you are agree, I can try to make a PR.
