### ISSUE TITLE
Sortable  - Lack of documentation

### ISSUE THREAD

**Issue by hshahdoost** [Atlantic18/DoctrineExtensions#1802]
At the end of the documentation there is an small part about using `SortableGroup` but it doesn't mention that when we use this annotation we should also mark our position field with `SortablePosition` annotation.

**Comment by l3pp4rd** [comment]
Hi, well, annotations are explained [here](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/sortable.md#sortable-entity-example) including an example in different mapping types. though, maybe it is not mentioned that you can have more than one group

**Comment by hshahdoost** [comment]
@l3pp4rd It is not the problem, The fact is that I didn't see the document you mentioned. As you can see a link [here](http://www.laraveldoctrine.org/docs/1.3/extensions/sortable) is referring to the [master branch](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/sortable.md)  of this project which (is an older version of the same document). So the problem is the link on laraveldoctrine.org. 
It should be updated on the website
