### ISSUE TITLE
PHP < 7 compatibility

### ISSUE THREAD

**Issue by michal-borek** [Atlantic18/DoctrineExtensions#1805]
DoctrineExtensions/lib/Gedmo/Sluggable/Mapping/Driver/Annotation.php at line 151 has still PHP 7 array declaration!

**Comment by Guite** [comment]
`$sluggableFields = [];` is valid since PHP 5.4. See http://php.net/manual/en/language.types.array.php for reference.

**Comment by michal-borek** [comment]
I know, the change was in php 7 compatibility commit as far as I can see. Personally I use it on some old 5.3.3 and in rest of code you have array() instead of [] which breaks my app :) I have patched it for my project but changing it will increase supported 5.x versions and keep the code in same convention.

**Comment by l3pp4rd** [comment]
5.3.x is not compatible with current doctrine versions, use older extensions version. if that is an only issue concerning php 5.3 support, then you may submit a pull request to fix it
