### ISSUE TITLE
Support Doctrine's new field types `datetime_immutable` etc.

### ISSUE THREAD

**Issue by ThomasLandauer** [Atlantic18/DoctrineExtensions#1820]
When defining a field as `type: datetime_immutable` (new in Doctrine DBAL 2.6: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#datetime-immutable ), I'm getting this error after doing `doctrine:schema:update`:

>   [Gedmo\Exception\InvalidMappingException]
  Field - [timestamp] type is not valid and must be 'date', 'datetime' or 'time'

The field uses `timestampable`:

```yml
gedmo:
    timestampable:
        on: create
```

**Comment by ste93cry** [comment]
I also need this feature, are you willing to accept a PR to fix the issue?

**Comment by l3pp4rd** [comment]
sure, open a PR on v2.4.x branch. this was introduced recently.
