### ISSUE TITLE
Can not find getAncestors method in ClosureTreeRepository

### ISSUE THREAD

**Issue by Starojitski** [Atlantic18/DoctrineExtensions#1849]
Documentation [here](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/tree.md#repository-methods-closure-trees-only) states :

> It is possible to obtain all ancestors from a particular node in a efficient way when using the Closure Tree strategy. These are the repository methods:
>
> **getAncestors** / **getAncestorsQuery** / **getAncestorsQueryBuilder**: Returns an array of ancestors nodes. 

However i can not find these methods in the codebase

**Comment by hugochinchilla** [comment]
I'm having the same issue, the method does not exists on my repository and I'm using a closure table type of tree.

**Comment by AkenRoberts** [comment]
A while back, there was a lot of effort to release a `3.0.0` version of Doctrine Extensions. This effort unfortunately stalled and never resulted in a stable product. That work can be found in [`archive/master-2019-03-17`](https://github.com/Atlantic18/DoctrineExtensions/tree/archive/master-2019-03-17). The documentation in `gh-pages` and consequently http://atlantic18.github.io/DoctrineExtensions/ is based on this branch.

The referenced methods are available in that branch as part of the abandoned updates to Tree and many other extensions. You can find the repository-related traits [here](https://github.com/Atlantic18/DoctrineExtensions/tree/archive/master-2019-03-17/lib/Gedmo/Tree/Traits/Repository/ORM) for their implementations, which you might be able to implement in a custom repository in your project.

I can't guarantee any functionality, quality, or effectiveness in that branch, as it was before my time as a contributor and I'm not sure what directions were taken or changed, if any.

If there is anything from that code base that is useful or would be useful, I'd very much like to hear about it for possible future implementation.

I apologize for any confusion, and good luck.

**Comment by hugochinchilla** [comment]
thanks @AkenRoberts, we ended up implementing the method ourselves.
