### ISSUE TITLE
[SoftDeleteable][Bug] BC break introduced with hard_delete option

### ISSUE THREAD

**Issue by enricog84** [Atlantic18/DoctrineExtensions#1864]
In contrary to the docs the default for the **hardDelete** option is set to **false** instead of **true**.   
This leads to backwards incompatibility, because it the option is not explicitly set in the config, no hard delete is ever done.   

I am using the YAML configuration, after adding the **hard_delete: true** it did remove it properly again.

BC break was introduced with @ #1861 .
 
My guess is inside the **SoftDeleteable/Mapping/Driver/\*.php** files the line 

` $config['hardDelete'] = false;`

should be changed to 

` $config['hardDelete'] = true;`

**Comment by l3pp4rd** [comment]
yes, could you submit a PR? will need to make a release, haven't noticed it sadly

**Comment by babeou** [comment]
@enricog84 theres's a mistake  (sorry for that) but it works for me, if no annotation set on entity, hard delete is done

**Comment by enricog84** [comment]
@babeou 
Maybe it behaves different on Annotations and Yaml config? I am not that deep in the code, but may the change (in lib/Gedmo/Mapping/Annotation/SoftDeleteable.php) set a default for the annotation while it doesn't for the other types?: https://github.com/Atlantic18/DoctrineExtensions/pull/1861/files#diff-a0ec338b49effdc4185f6d7e1f5e78d8

**Comment by enricog84** [comment]
@l3pp4rd @babeou 
Created PR #1865 .
