### ISSUE TITLE
New Array syntax broken in PHP 5.3.29

### ISSUE THREAD

**Issue by pmoubed** [Atlantic18/DoctrineExtensions#1867]
based on requirement on packagist, version v2.4.33 should support php: >=5.3.2 but with line below with new array syntax is broken on php 5.3.29 

Line 159 of Gedmo\Sluggable\Mapping\Driver\Annotation:

$sluggableFields = []; // this must array() consistent with others 
foreach ($slug->fields as $field) {
       $sluggableFields[] = $fieldNamePrefix ? ($fieldNamePrefix . '.' . $field) : $field;
}

**Comment by l3pp4rd** [comment]
Hi, could you submit a pull request to fix it?

**Comment by pmoubed** [comment]
Hi,
Pull request submitted.
