### ISSUE TITLE
Gedmo Tree repository error

### ISSUE THREAD

**Issue by maslitto** [Atlantic18/DoctrineExtensions#1881]
Hi, i'm using symfony 4 and doctrine-orm-admin-bundle (3.4.2) . I'm trying to extend my repository from NestedTreeRepository as  i got autowire error. Error listing:

> Cannot autowire service "App\Repository\CatalogRepository": argument "$em" of method "Gedmo\Tree\Entity\Repository\AbstractTreeRepository::__construct()" references class "Doctrine\ORM\EntityManager" but no such service exists. Try changing the type-hint to one of its parents: interface "Doctrine\ORM\EntityManagerInterface", or interface "Doctrine\Common\Persistence\ObjectManager".

my repository:

```
namespace App\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

class CatalogRepository extends NestedTreeRepository

{
}
```

Is there any way to fix it?

**Comment by Oviglo** [comment]
+1

**Comment by qRoC** [comment]
```php
public function __construct(ManagerRegistry $registry)
    {
        $entityClass = Category::class;

        $manager = $registry->getManagerForClass($entityClass);

        parent::__construct($manager, $manager->getClassMetadata($entityClass));
    }
```

**Comment by emovere** [comment]
The solution from @qRoC should be noted here:
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/tree.md#if-you-need-a-repository-for-your-treenode-entity-simply-extend-it

**Comment by auipga** [comment]
This one works with auto-wiring too:
```php
public function __construct(EntityManagerInterface $manager)
{
    parent::__construct($manager, $manager->getClassMetadata(Category::class));
}
```

**Comment by wassafr** [comment]
qRoC's solution didn't work for me but yours did

**Comment by AkenRoberts** [comment]
`AbstractTreeRepository` has used `EntityManagerInterface` as a parameter since February 2018. Please check that you're on the most recent version of 2.4.x.

**Comment by bdujon** [comment]
on thing to add if you want your NestedTreeRepository completely compatible with autowiring for service injection inside your repo : 
you just need to add implements ServiceEntityRepositoryInterface
`class CatalogRepository extends NestedTreeRepository implements ServiceEntityRepositoryInterface`

**Comment by auipga** [comment]
Maybe a bit off-topic: **Combining regular repositories and tree repositories**:

I have a `UserTreeRepository`:
```php
class UserTreeRepository extends NestedTreeRepository
{
    public function __construct(EntityManagerInterface $manager)
    {
        parent::__construct($manager, $manager->getClassMetadata(User::class));
    }
...
```
I  also have a regular `UserRepository`:
```php
class UserRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, User::class);
    }
...
```
My User class has this annotation:
```php
/** @ORM\Entity(repositoryClass="App\Repository\UserRepository") */
```
AFAIK I can't provide multiple repos and use them both like this: (Please correct me if I'm wrong)
```php
$em->getRepository(User::class)
```
I want to use **both**. So I changed my `UserRepository` to this:
_(Well, I could use DI instead, but I didn't want to in my case)_
```php
class UserRepository extends ServiceEntityRepository
{
    public UserTreeRepository $tree;
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, User::class);
        $this->tree = new UserTreeRepository($this->getEntityManager());
    }
```
Now I can use them like this:
```php
$user     = $em->getRepository(User::class)->find(1);
$children = $em->getRepository(User::class)->tree->getChildren($user);
```
I don't know whether this follows any coding standards. Improvements welcome.

**Comment by bdujon** [comment]
I dont understand why you need to separate in 2 repository, why not keeping everything in one ?

**Comment by VictorKrasnov** [comment]
> This one works with auto-wiring too:
> 
> ```
> public function __construct(EntityManagerInterface $manager)
> {
>     parent::__construct($manager, $manager->getClassMetadata(Category::class));
> }
> ```
> 
> What is the "big" difference to @qRoC's solution?

This solution doesn't work if I try to inject class name to repository, for example:

```
# services.yaml
CategoryRepositoryInterface:
    class: CategoryRepository
        arguments:
             $entityClassName: Category
```

```
# repo
public function __construct(EntityManagerInterface $entityManager, string $entityClassName)
{
    parent::__construct($entityManager, $entityManager->getClassMetadata($entityClassName));
}
```

Error: 
Cache key "Doctrine__ORM__Mapping__ClassMetadataInfo@1496__CLASSMETADATA__" contains reserved characters "{}()/\@:".

Anyone know some more solution?
