### ISSUE TITLE
Using DoctrineExtensions with Symfony 4

### ISSUE THREAD

**Issue by Th3BiSh0p** [Atlantic18/DoctrineExtensions#1899]
I installed DoctrineExtensions through flex with Symfony 4.
The receipe should create stof_doctrine_extensions.yaml but it didn't. I created it manually but then I have a message : 
`There is no extension able to load the configuration for "stof_doctrine_extensions"`

I tried a few things but nothing worked. I don't know what to do at this point.

Thanks

**Comment by BoShurik** [comment]
You should install [StofDoctrineExtensionsBundle](https://github.com/stof/StofDoctrineExtensionsBundle)

```bash
composer req stof/doctrine-extensions-bundle
```
not 
```bash
composer req gedmo/doctrine-extensions
```

**Comment by yellow1912** [comment]
To make it clear, the document @Th3BiSh0p was following was using stof_doctrine_extensions which should use stof/doctrine-extensions-bundle not gedmo/doctrine-extensions.

**Comment by jcfrane** [comment]
I got a problem on installing stof doctrine bundle:

  Problem 1
    - The requested package symfony/monolog-bundle (locked at v3.1.2, required as ^3.2) is satisfiable by symfony/monolog-bundle[v3.1.2] but these conflict with your requirements or minimum-stability.

**Comment by yellow1912** [comment]
@jcfrane I don't think your issue has anything to do with this bundle?

**Comment by jcfrane** [comment]
@yellow1912 im sorry, yeah its not connected in anyway.
