### ISSUE TITLE
[tree] howto prevent getResult('tree') from firing additional queries for each reference column

### ISSUE THREAD

**Issue by sufius** [Atlantic18/DoctrineExtensions#1902]
This is working:

```
      return $this->getEntityManager()->createQuery('
        SELECT me
        FROM AppBundle\MyEntity me
        WHERE me.root = :rid
      ')
      ->setParameter('rid', 1234)
      ->setHint(Query::HINT_INCLUDE_META_COLUMNS, true)
      ->getResult('tree');
```

Unfortunately because "me" has a reference column to another table it is calling for each row a query to fetch that data too ((

It is not working if I'm trying to reduce the set of columns (without reference column) like this:

```
      return $this->getEntityManager()->createQuery('
        SELECT me.id AS id,
          me.title AS title,
          me.slug AS slug,
          me.description AS description,
          me.lft AS lft,
          me.rgt AS rgt,
          me.lvl AS lvl
        FROM AppBundle\MyEntity me
        WHERE me.root = :rid
      ')
      ->setParameter('rid', 1234)
      ->setHint(Query::HINT_INCLUDE_META_COLUMNS, true)
      ->getResult('tree');
```

Following error is appearing:
**Warning: get_class() expects parameter 1 to be object, array given**

How to fetch just some special columns or prevent getResult('tree') from firing additional queries? (I already tried to mark the reference column as "as Hidden", but unfortunately without luck...

**Comment by l3pp4rd** [comment]
no idea, guess no one is storing data in column metadata for querying with rows :) anyway, that metadata should be same for all the rows, do the separate query and cache it somewhere.

**Comment by sufius** [comment]
if i got your answer correct you are about this:
->setHint(Query::HINT_INCLUDE_META_COLUMNS, true)

even if you remove this hint setting it is producting additional queries. so i guess it has nothing to do with this meta-data setting.

but thank you for your fast answer...

**Comment by sufius** [comment]
After struggling for some time I've finally found a solution. Just load the reference column with the help of a join statement to prevent additional queries.

  ```
 return $this->getEntityManager()->createQuery('
        SELECT me, mr
        FROM AppBundle\MyEntity me
        LEFT JOIN me.myref mr
        WHERE me.root = :rid
      ')
      ->setParameter('rid', 1234)
      ->setHint(Query::HINT_INCLUDE_META_COLUMNS, true)
      ->getResult('tree');

```

Sir, this issue can be closed, Sir.
