### ISSUE TITLE
Entity persistance error

### ISSUE THREAD

**Issue by sanpii** [Atlantic18/DoctrineExtensions#1912]
Hello,

When I update DoctrineExtensions from `v2.4.33` to `v2.4.34` I have this error:

```
Doctrine\ORM\ORMInvalidArgumentException: Entity #1 is not managed. An entity is managed if its fetched from the database or registered as new through EntityManager#persist
```

My code looks like:

```php
$entity = $repository->findOneById(1);
$entityManager->remove($entitty);
$entityManager->flush();
$entityManager->refresh($entity);
```

The entity is loggable, soft deleteable with some versionned fields.

**Comment by rsukonovs** [comment]
And this gets more interesting:

```
$repo = $this->em->getRepository(Entity::class);
$anotherRepo = $this->em->getRepository(EntityOther::class);
$entity = $repo->find(2);
$entity2 = $anotherRepo->find(2); // this entity has association with first Entity and loads proxy object
$this->em->remove($entity);
$this->em->flush();

$entity2->setSomething('something');
$this->em->flush();
```
I get ``Doctrine\ORM\ORMInvalidArgumentException : A new entity was found through the relationship...``. Proxy is still here. I am not super aware about underlying workings of ORM, but it seems that these changes breaks normal flow in app. My first example has antipattern, but this one I am not sure.

**Comment by jayesbe** [comment]
Numerous client complaints coming in after a recent update.. just found this issue and it looks like im not alone.. good to know.

**Comment by sanpii** [comment]
Thank you.

**Comment by l3pp4rd** [comment]
yes sadly did not expect such behavior while merging a pull request. guess it is tied too deep in orm to allow such object detaching. anyway update to new release if you experience this issue
