### ISSUE TITLE
[Tree] I not find Tree trait in v.2.4.36? 

### ISSUE THREAD

**Issue by nickicool** [Atlantic18/DoctrineExtensions#1950]
Hi! I cant find the Tree trait in version 2.4.36 [https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Traits/Repository/ORM/NestedTreeRepositoryTrait.php](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Traits/Repository/ORM/NestedTreeRepositoryTrait.php).
Maybe I do something wrong, or incorrectly set bundle. For install i just used:

    composer req gedmo/doctrine-extensions

**Comment by AkenRoberts** [comment]
Hi @nickicool. The `NestedTreeRepositoryTrait` is in the `master` branch, which was slated to be the next major release of DoctrineExtensions (3.0). Unfortunately, previous maintainers have not been able to contribute as much as in the past, and as such that version was stalled. And even may be scrapped for a new 3.0 version by new contributors. We're still trying to figure that out.

You may be able to manually introduce this trait to your project, with some adjustment (it may depend on other contributions or changes in the `master` branch outside of the trait). There are no plans to introduce it into the 2.4 branch at this time.
