### ISSUE TITLE
[Loggable][sf4]: Integrity constraint violation: 1048 Column 'object_id' cannot be null while persisting new entity

### ISSUE THREAD

**Issue by smtlab** [Atlantic18/DoctrineExtensions#1956]
**config/doctrine/Tag.orm.xml**

    <doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                   https://raw.github.com/doctrine/doctrine2/master/doctrine-mapping.xsd"
        xmlns:gedmo="http://gediminasm.org/schemas/orm/doctrine-extensions-mapping"
    >
    <entity name="App\Entity\Tag" table="tag">
        <id name="id" type="integer" column="id">
            <generator strategy="AUTO"/>
        </id>
        <field name="tag" type="string" length="50" unique="true" />
        <field name="text" type="string" length="2000" nullable="true">
        	<gedmo:versioned/>
        </field>
        <gedmo:loggable log-entry-class="App\Entity\LogEntry"/>
	</entity>
</doctrine-mapping>

**config/packages/stof_doctrineextensions.yaml**

      stof_doctrine_extensions:
          default_locale: en_US
          orm:
              default:
                  loggable: true

**This works (Updating) :)**

        $tag = $em->getRepository(Tag::class)->findOneBy(['tag'=>'test']);
        $tag->setTag('test update');
        $tag->setText('test text');
        $em->flush();

**This doesn't (Persisting) :(**

        $tag = new Tag();
        $tag->setTag('test');
        $tag->setText('test text');
        $em->persist($tag);
        $em->flush();
        
        **Throws below exception**

        An exception occurred while executing 'INSERT INTO log_entry (action, logged_at, object_id, 
        object_class, version, data, username, comment, created_by_id, updated_by_id) VALUES (?, ?, ?, 
        ?, ?, ?, ?, ?, ?, ?)' with params ["create", "2018-10-01 17:22:28", null, "App\\Entity\\Tag", 1, "a:1:
        {s:4:\"text\";N;}", null, null, null, null]:

        SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'object_id' cannot be null

Its obvious loggable listener is not able to access the new object id or is trying to persist log entry before persisting the original object.
I tried debugging seems like `LoggableListener`'s `postPersist` method is never called while persisting, But works while updating, unable to track down what's missing.

**Comment by andrewtch** [comment]
Hi! Can you please post your composer.json?

**Comment by smtlab** [comment]
@andrewtch 

Here is my composer.json

```
{
	"type" : "project",
	"license" : "proprietary",
	"require" : {
		"php" : "^7.1.3",
		"ext-iconv" : "*",
		"exercise/htmlpurifier-bundle" : "^2.0",
		"friendsofsymfony/ckeditor-bundle" : "^1.1",
		"friendsofsymfony/rest-bundle" : "^2.3",
		"friendsofsymfony/user-bundle" : "^2.1",
		"gedmo/doctrine-extensions" : "^2.4",
		"hwi/oauth-bundle" : "^0.6.2",
		"intervention/image" : "^2.4",
		"jms/serializer-bundle" : "^2.3",
		"league/tactician-bundle" : "^1.1",
		"php-http/guzzle6-adapter" : "^1.1",
		"php-http/httplug-bundle" : "^1.10",
		"pixassociates/sortable-behavior-bundle" : "^1.5",
		"sensio/framework-extra-bundle" : "^5.1",
		"smalot/pdfparser" : "^0.13.2",
		"sonata-project/classification-bundle" : "^3.6",
		"sonata-project/doctrine-orm-admin-bundle" : "^3.6",
		"sonata-project/formatter-bundle" : "^3.5",
		"sonata-project/media-bundle" : "^3.12",
		"sonata-project/news-bundle" : "^3.4",
		"sonata-project/notification-bundle" : "^3.5",
		"sonata-project/page-bundle" : "@dev",
		"sonata-project/timeline-bundle" : "^3.3",
		"sonata-project/user-bundle" : "^4.1",
		"stof/doctrine-extensions-bundle" : "^1.3",
		"sylius/registry" : "*@dev",
		"sylius/resource" : "*@dev",
		"sylius/resource-bundle" : "dev-master",
		"symfony/asset" : "^4.0",
		"symfony/console" : "^4.0",
		"symfony/expression-language" : "^4.0",
		"symfony/flex" : "^1.0",
		"symfony/form" : "^4.0",
		"symfony/framework-bundle" : "^4.0",
		"symfony/lts" : "^4@dev",
		"symfony/monolog-bundle" : "^3.1",
		"symfony/orm-pack" : "*",
		"symfony/process" : "^4.0",
		"symfony/security-bundle" : "^4.0",
		"symfony/serializer-pack" : "*",
		"symfony/swiftmailer-bundle" : "^3.1",
		"symfony/twig-bundle" : "^4.0",
		"symfony/validator" : "^4.0",
		"symfony/web-link" : "^4.0",
		"symfony/webpack-encore-pack" : "^1.0",
		"symfony/yaml" : "^4.0",
		"twig/extensions" : "^1.5"
	},
	"require-dev" : {
		"behat/mink" : "dev-master",
		"behat/mink-browserkit-driver" : "^1.3",
		"behat/mink-extension" : "dev-master",
		"behat/mink-selenium2-driver" : "^1.3",
		"behat/symfony2-extension" : "^2.1",
		"doctrine/data-fixtures" : "^1.3",
		"easycorp/easy-deploy-bundle" : "^1.0",
		"friends-of-behat/context-service-extension" : "^1.2",
		"friends-of-behat/cross-container-extension" : "^1.1",
		"friends-of-behat/symfony-extension" : "^1.2",
		"symfony/browser-kit" : "^4.0",
		"symfony/css-selector" : "^4.0",
		"symfony/debug-pack" : "*",
		"symfony/dotenv" : "^4.0",
		"symfony/maker-bundle" : "^1.0",
		"symfony/phpunit-bridge" : "^4.0",
		"symfony/profiler-pack" : "*",
		"symfony/web-server-bundle" : "^4.0"
	},
	"config" : {
		"preferred-install" : {
			"*" : "dist"
		},
		"sort-packages" : true,
		"minimum-stability" : "dev",
		"prefer-stable" : true
	},
	"autoload" : {
		"psr-4" : {
			"App\\" : "src/"
		}
	},
	"autoload-dev" : {
		"psr-4" : {
			"App\\Tests\\" : "tests/"
		}
	},
	"replace" : {
		"symfony/polyfill-iconv" : "*",
		"symfony/polyfill-php71" : "*",
		"symfony/polyfill-php70" : "*",
		"symfony/polyfill-php56" : "*",
		"egeloen/ckeditor-bundle" : "*"
	},
	"conflict" : {
		"symfony/symfony" : "*"
	},
	"extra" : {
		"symfony" : {
			"id" : "01CBPRWMSW61ZYV7VJJ9D9G7V1",
			"allow-contrib" : false
		}
	},
	"name" : "App"
} 
```

**Comment by smtlab** [comment]
@Webonaute object_id cannot be nullable as it is used to keep the track of logs of associated object.

Regarding listener if you take a look at the code here https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Loggable/LoggableListener.php

You will the code is already written for managing persisting, updating and deleting. But in my case its not working. No idea why unable to track the issue

**Comment by Webonaute** [comment]
if you look at the mapped superclass
`
/**
     * @var string $objectId
     *
     * @ORM\Column(name="object_id", length=64, nullable=true)
     */
    protected $objectId;
`
the field is nullable. if you changed the behaviour in your custom entity, its normal that things can fail.
like I said, it try to insert a log on an object who doesn't have identifier yet. (identifier is set on flush)

**Comment by smtlab** [comment]
@Webonaute thank you so much, you are right. It first inserts the log entry and schedules extra updates to update missing ids after inserting the original object.

Pheww this addresses my issue.
