### ISSUE TITLE
[Tree] TreeListener does not support tree type '' AND Illegal string offset 'strategy'

### ISSUE THREAD

**Issue by borisvalo** [Atlantic18/DoctrineExtensions#1972]
I am currently struggling with random exception and warning in Gedmo Behavioral Extension for Doctrine (or Atlantic18/DoctrineExtensions) that started to appear after change of PHP version from 5.6 to 7.1. It is happening just during using Tree/Nestedtree behavior.

`[2018-10-08 10-17-16] PHP Warning: Illegal string offset 'strategy' in /../website/application/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/TreeListener.php:84 `
`[2018-10-08 10-17-16] Gedmo\Exception\InvalidArgumentException: ORM TreeListener does not support tree type: a in /../website/application/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/TreeListener.php:84`

The version of Gedmo is v2.4.31. During some research I found one question, where there was problem with metadata cache. Unfortunately it didn't helped even we changed Memcache for Redis (I thought there might some problems with length of keys in Memcache)
Even after change back to PHP 5.6 the errors and warnings haven't disappeared.

I saw few similar bugs here, but all are about APC cache.

**Comment by v-girl** [comment]
I had the same issue with PHP version 7.2, symfony 3.4.26 and gdemo 2.4.26. 
The error message suddenly occured for unknown reasons. 

`[2019-06-03 07:27:51] request.CRITICAL: Uncaught PHP Exception Gedmo\Exception\InvalidArgumentException: "ORM TreeListener does not support tree type: " at /../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/TreeListener.php line 84 {"exception":"[object] (Gedmo\\Exception\\InvalidArgumentException(code: 0): ORM TreeListener does not support tree type:  at /../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/TreeListener.php:84)"} []`
`[2019-06-03 07:27:51] request.CRITICAL: Exception thrown when handling an exception (Gedmo\Exception\InvalidArgumentException: ORM TreeListener does not support tree type:  at /../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/TreeListener.php line 84) {"exception":"[object] (Gedmo\\Exception\\InvalidArgumentException(code: 0): ORM TreeListener does not support tree type:  at /../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/TreeListener.php:84)"} []
`

Restart PHP didn't help.

My solution:
After rebooting the server all error messages have disappeared.

**Comment by AkenRoberts** [comment]
Closing since this is an older issue and it's next to impossible to replicate. @borisvalo If you'd like to follow up with more information, we'd be happy to help further. Difficult to do much with what's here at the moment.
