### ISSUE TITLE
DEPRICATED: Configuration, tree builder w/o root node is deprecated in Symfony 4.2

### ISSUE THREAD

**Issue by dougie84mo** [Atlantic18/DoctrineExtensions#1980]
Seems to be an issue with most Symfony bundles since I got this Dep. Warning 11 times on the profiler. Returns message (11 times):
**A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.**

May be only getting this warning because STOF is last in the bundle to be called/compiled by the Container Builder last?? Otherwise not sure why this comes up.

Tried this and did not work; this is what the docs say is supported starting around 4.1-2
```
$builder = new TreeBuilder('stof_doctrine_extensions');
$rootNode = $builder->getRootNode();
```

Not sure if its the appends for extending Doctrine.
```
->append($this->getVendorNode('orm'))
->append($this->getVendorNode('mongodb'))
->append($this->getClassNode())
->append($this->getUploadableNode())

```
Honestly just started trying to Contribute in the development world (ESPECIALLY SYMFONY, DOCTRINE, FOS, etc.) so this was most of my hunting (above).

This is the trace of the error so I assume I did not do the TreeBuilder constructor correctly some how.
```
{▼
  /Users/.../vendor/symfony/config/Definition/Builder/TreeBuilder.php:30 {▼
    › if (null === $name) {
    ›     @trigger_error('A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.', E_USER_DEPRECATED);
    › } else {
  }
  /Users/.../vendor/stof/doctrine-extensions-bundle/DependencyInjection/Configuration.php:17 {▼
    › {
    ›     $treeBuilder = new TreeBuilder();
    ›     $rootNode = $treeBuilder->root('stof_doctrine_extensions');
  }
}
```

Any thoughts? Should I move this elsewhere. Again Im new to this stuff

**Comment by l3pp4rd** [comment]
Hi, this is not a [stof bundle](http://github.com/stof/StofDoctrineExtensionsBundle), open the issue elsewhere. or follow the [documentation for symfony](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/symfony2.md) to setup it for your self without a bundle

**Comment by dougie84mo** [comment]
Thank you. I will close this and move it else where.
