### ISSUE TITLE
what can we expect from this project in the feature?

### ISSUE THREAD

**Issue by svycka** [Atlantic18/DoctrineExtensions#1988]
For now, I don't have any problems with this project, but I understand @l3pp4rd does not maintain it at least no more new features are accepted. I don't know if you looking for new maintainers or something who could do this. Doctrine v3 coming and I guess it's possible this module will not work with it as it is and will require some changes so do you plan to support doctrine3 or other upcoming versions or just 2.x? also PHP 7.3? and I see there are some PHP 7.2 issues with pull request will those be merged?

so the question is do we can expect some love for this project or we should slowly migrate to something else?

**Comment by l3pp4rd** [comment]
Hi @svycka it would make sense to limit these extensions to doctrine 2 support. In my opinion adjusting and refactoring it to support doctrine 3 would be too cumbersome for any maintainers, they would prefer building something on their own. So to summarize, it makes sense to support new php versions and doctrine 2. without extending the feature set of current doctrine extensions. You've bin invited as contributor and may merge the pull requests necessary to maintain the project.

**Comment by svycka** [comment]
Okay, I will do when I can upgrade to 7.3 I am still on 7.1 :)
