### ISSUE TITLE
 Integrity constraint violation: 1062 Duplicate entry on Specific Domain

### ISSUE THREAD

**Issue by sbarbosa115** [Atlantic18/DoctrineExtensions#2000]
Hi there, I had been using the translation component for a project I'm working with, the issue is we have two translations domain, EN_US, and EN_AU, the US environment is working well when I try to add a new Translateable entity, however over AU environment I'm getting this error: 

An exception occurred while executing 'INSERT INTO ext_translations (locale, object_class, field, foreign_key, content) VALUES (?, ?, ?, ?, ?)' with params ["en_AU", "AppBundle\\Entity\\Resource", "title", 21, "TEST"]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en_AU-AppBundle\Entity\Resource-title-21' for key 'lookup_unique_idx'

I'm working really hard trying to see what is going on, however, so far I haven't any solution.

**Comment by cybernet** [comment]
it may be late, but
have you made it unique=true ?

**Comment by AkenRoberts** [comment]
@sbarbosa115 As @cybernet commented, it looks like you have a unique index for that particular language+entity+field combination, and "title" already has an entry for en_AU.
