### ISSUE TITLE
[Fixing Bug] Entity/Document configuration overwritten when using multiple annotations

### ISSUE THREAD

**Issue by mohamedaymenkarmous** [Atlantic18/DoctrineExtensions#2012]
Hi,

While I'm using multiple Entity annotations (an example below), I find that Entity configuration `Gedmo\Mapping\MappedEventSubscriber::$configurations` gets different configurations independently and each configuration is overwritten by the next configuration that it will get (old configuration will not exist).

Example using ``Gedmo Loggable`` for the Document and ``Gedmo References`` for referencing ORM entities with ODM documents :

```
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @MongoDB\Document(collection="proofs")
 * @MongoDB\Document(repositoryClass="MyBundle\Document\ProofsRepository")
 * @Gedmo\Loggable(logEntryClass="MyBundle\Document\HistoryTransaction")
 */
class Proofs
{
  //...
    /**
     * @MongoDB\Id
     * @Gedmo\Versioned
     */
    private $id;

    /**
     * @Gedmo\ReferenceOne(type="entity", class="MyBundle\Entity\ProofElement", inversedBy="proofs", identifier="proof_id")
     */
    private $proof;

    /**
     * @MongoDB\Field(name="proof_id", type="integer")
     * @Gedmo\Versioned
     */
    private $proof_id;
  //...
}
```

I overrided Gedmo References Listener ``Gedmo\References\ReferencesListener`` in order to customize something and I found this problem: Inside ``Gedmo\References\ReferencesListener::postLoad()`` when I ``dump($config);`` exactly [after this line](https://github.com/l3pp4rd/DoctrineExtensions/blob/1df5277a7e6723bbd572259ed1ca23566ae63eda/lib/Gedmo/References/ReferencesListener.php#L41), I get the output below when I load `Proofs` data:

```
array:4 [
  "loggable" => true
  "logEntryClass" => "MyBundle\Document\HistoryTransaction"
  "versioned" => array:4 [
    0 => "id"
    1 => "proof_id"
  ]
  "useObjectClass" => "MyBundle\Document\Proofs"
]
```

But, when I remove Gedmo Loggable Annotations like this:

```
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @MongoDB\Document(collection="proofs")
 * @MongoDB\Document(repositoryClass="MyBundle\Document\ProofsRepository")
 */
class Proofs
{
  //...
    /**
     * @MongoDB\Id
     */
    private $id;

    /**
     * @Gedmo\ReferenceOne(type="entity", class="MyBundle\Entity\ProofElement", inversedBy="proofs", identifier="proof_id")
     */
    private $proof;

    /**
     * @MongoDB\Field(name="proof_id", type="integer")
     */
    private $proof_id;
  //...
}
```

I get this output

```
array:4 [
  "referenceOne" => array:1 [
    "proof_list" => array:6 [
      "field" => "proof"
      "type" => "entity"
      "class" => "MyBundle\Entity\ProofElement"
      "identifier" => "proof_id"
      "mappedBy" => null
      "inversedBy" => "proofs"
    ]
  ]
  "referenceMany" => []
  "referenceManyEmbed" => []
  "useObjectClass" => "MyBundle\Document\Proofs"
]
```

I started investigation from `lib/Gedmo/Loggable/Mapping/Driver/Annotation.php` ``Gedmo\Loggable\Mapping\Driver::readExtendedMetadata()`` until I came back to `lib/Gedmo/Mapping/MappedEventSubscriber.php` ``Gedmo\Mapping\MappedEventSubscriber::loadMetadataForObjectClass()`` in which ``Gedmo\Mapping\MappedEventSubscriber::$configurations`` is overwritten without merging its previous value

I tried to give you a new modification of the code in case you didn't understand what I mean

New code of the [Gedmo\Mapping\MappedEventSubscriber::loadMetadataForObjectClass()](https://github.com/l3pp4rd/DoctrineExtensions/blob/1df5277a7e6723bbd572259ed1ca23566ae63eda/lib/Gedmo/Mapping/MappedEventSubscriber.php#L195,L207) code

```
    public function loadMetadataForObjectClass(ObjectManager $objectManager, $metadata)
    {
        $factory = $this->getExtensionMetadataFactory($objectManager);
        try {
            $config = $factory->getExtensionMetadata($metadata);
        } catch (\ReflectionException $e) {
            // entity\document generator is running
            $config = false; // will not store a cached version, to remap later
        }
        if ($config) {
            $oldConfigurations=array();
            if(isset(self::$configurations) && isset(self::$configurations[$this->name]) && isset(self::$configurations[$this->name][$metadata->name]))
              $oldConfigurations=self::$configurations[$this->name][$metadata->name];
            self::$configurations[$this->name][$metadata->name] = array_merge($oldConfigurations,$config);
        }
    }
```

I tried this modification directly from my Symfony project (vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/MappedEventSubscriber.php) and I get this output:

```
array:7 [
  "referenceOne" => array:1 [
    "proof_list" => array:6 [
      "field" => "proof"
      "type" => "entity"
      "class" => "MyBundle\Entity\ProofElement"
      "identifier" => "proof_id"
      "mappedBy" => null
      "inversedBy" => "proofs"
    ]
  ]
  "referenceMany" => []
  "referenceManyEmbed" => []
  "useObjectClass" => "MyBundle\Document\Proofs"
  "loggable" => true
  "logEntryClass" => "MyBundle\Document\HistoryTransaction"
  "versioned" => array:4 [
    0 => "id"
    1 => "proof_id"
  ]
]
```

Which looks good (configurations contains Gedmo Loggable and Gedmo References configurations).

If overwriting $configurations value is intended to not break another annotations features and only keeping Gedmo Annotations while merging the configurations array, at least we should keep Gedmo configurations smartly (for example by filtring old $configurations and keeping some values in the new $configurations array) even if, in my opinion, filtring Annotations is useless because we know that this is a very rare issue.

So can anyone review this part of code and edit it on the project ?

**Comment by mohamedaymenkarmous** [comment]
I think I found the problem of this bug.

I requested for these PR #2025 #2026 and I'm going to test if applying these changes will fix this issue or not.

If is it true, I think it will be useless to modify `Gedmo\Mapping\MappedEventSubscriber::loadMetadataForObjectClass() code` (from my previous comment).

**Comment by AkenRoberts** [comment]
Thank you @mohamedaymenkarmous, and sorry for the lack of attention. I've added the missing `parent::__construct()` calls in any listeners with custom constructors.
