### ISSUE TITLE
Blameable and decoupled user entity and userinterface'd class

### ISSUE THREAD

**Issue by danaki** [Atlantic18/DoctrineExtensions#2014]
Hi, I'm using decoupled Entity and security user like it's described here https://stovepipe.systems/post/decoupling-your-security-user

The reason for that is that I want to keep domain separated following DDD principles.

Now my entity looks like:
```
class Batch {
// ....
    /**
     * @var Employee
     *
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="Employee")
     */
    private $createdBy;
//...
```

while class 'App\\Security\\User\\SecurityUser' implements actual UserInterface.

When I try to save the entity, it produces an error:
```
The class 'App\\Security\\User\\SecurityUser' was not found in the chain configured namespaces App\\Entity
```

Which is because of this line of code:
```
        if (null !== $token && $this->authorizationChecker->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            $this->blameableListener->setUserValue($token->getUser());
        }
```

`$token->getUser()` returns an object of class `App\\Security\\User\\SecurityUser` not the Entity. Is it possible to override this behavior introducing a configuration option?

**Comment by AkenRoberts** [comment]
Hi @danaki, sorry for the lack of attention here.

That code is actually part of [StofDoctrineExtensionsBundle](https://github.com/stof/StofDoctrineExtensionsBundle/blob/c68a6662280b9e842aeba290f8ea2821ec5e5cc4/EventListener/BlameListener.php#L45-L48), so we can't change that within this library.

You should be able to [override the listener class](https://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/advanced.html) and customize it to suit your setup.

**Comment by AkenRoberts** [comment]
@danaki Since there hasn't been any activity for quite a while, I will assume you have resolved your issue. Please update us or open a new issue if you feel there is a problem with Doctrine Extensions itself. Thank you!

**Comment by danaki** [comment]
Ok, I'll fill the issue in StofDoctrineExtensionsBundle because it's still actual.

**Comment by danaki** [comment]
https://github.com/stof/StofDoctrineExtensionsBundle/issues/408
