### ISSUE TITLE
[Question] What is hard_delete doing / whats the use-case?

### ISSUE THREAD

**Issue by leberknecht** [Atlantic18/DoctrineExtensions#2015]
Hi, 
So i found that the implementation is this:
```
  public function onFlush(EventArgs $args)
    {
[..]
                if (isset($config['hardDelete']) && $config['hardDelete'] && ($oldValue instanceof \DateTime || $oldValue instanceof \DateTimeInterface) && $oldValue <= $date) {
                    continue; // want to hard delete
                }
```
which looks to me like "if we try to delete a soft-deleted record, then really drop it", right? What is the use case for that? Or better: As the em wont give the soft-deleted records back from a query, how does one get here? By "forcing" the delete via DQL?

**Comment by cybernet** [comment]
+1

**Comment by AkenRoberts** [comment]
> which looks to me like "if we try to delete a soft-deleted record, then really drop it", right?

Correct. The use case depends on your application's needs. You may never care about fully deleting data, or you might want to give your users that option. Maybe there are regulations such as HIPAA that you need to be careful of, and have the ability to fully remove data in the event of someone not following procedure.

You can tell the entity manager to ignore the soft delete filter when retrieving records:

```php
<?php
$article = new Article;
$article->setTitle('My Article');

$em->persist($article);
$em->flush();

// Now if we remove it, it will set the deletedAt field to the actual date
$em->remove($article);
$em->flush();

$repo = $em->getRepository('Article');
$art = $repo->findOneBy(array('title' => 'My Article'));

// It should NOT return the article now
$this->assertNull($art);

// But if we disable the filter, the article should appear now
$em->getFilters()->disable('soft-deleteable');

$art = $repo->findOneBy(array('title' => 'My Article'));

$this->assertTrue(is_object($art));

// Enable / Disable filter filter, for specified entity (default is enabled for all)
$filter = $em->getFilters()->enable('soft-deleteable');
$filter->disableForEntity('Entity\Article');
$filter->enableForEntity('Entity\Article');

// Undelete the entity by setting the deletedAt field to null
$article->setDeletedAt(null);
```

At which point you could pass the entity to `$em->remove()` for a hard delete.

I don't remember off the top of my head if DQL queries go through the entity manager and/or listeners, so I can't say for sure about forcing deletes via DQL.

**Comment by leberknecht** [comment]
Ah! That makes sense!
