### ISSUE TITLE
[Security]Sluggable

### ISSUE THREAD

**Issue by cybernet** [Atlantic18/DoctrineExtensions#2016]
If one might be declaring only one field for Sluggable
```@Gedmo\Slug(fields={"content"})```
and it could containg unsupported characters that could affect a website, would you say this is a security problem that needs a patch ?

**Comment by AkenRoberts** [comment]
It _could_ potentially be a security issue, depending on where the slug is used/displayed. However, it's mostly an issue the same way that choosing to not escape user-submitted input is an issue; not really something this library is supposed to protect against.

Under the hood, Sluggable uses [Behat's Transliterator](https://github.com/Behat/Transliterator) to generate the slugs. It's supposed to change as many characters as it can to ASCII (basic Latin letters/numbers), and remove special symbols and other URL-unfriendly characters. I'm pretty sure 99% of security scenarios can be protected using this process.

If you think there is still an issue that this library could still protect against, certainly open to feedback and/or a pull request.

**Comment by cybernet** [comment]
Transliterator hasn't been updated in 2 years ... and it also uses some data from [perl](https://github.com/Behat/Transliterator/blob/master/src/Behat/Transliterator/SyncTool.php#L205)
i have tried to escape the input but it renders the slug null.
i ended up using `@ORM\PrePersist()` and just generate some rand characters untill i find a better solution. i'm not that good of a coder to make a patch. 
is there an email where i can send you those characters ? maybe have a look ?

**Comment by AkenRoberts** [comment]
Just post them here, either as a comment or attach a relevant file. :)

**Comment by cybernet** [comment]
🇼🇫🇹🇭🇿🇲🇹🇭🇺🇿🇹🇿🇹🇿🇹🇭

**Comment by cybernet** [comment]
any news ?

**Comment by AkenRoberts** [comment]
Sorry for the lack of attention, @cybernet.

I don't believe you need to worry about emoji themselves as a security concern. They won't do any harm by themselves, and are even supported in URLs by most modern browsers.

Do you have any other concerns about having emoji in your slugs?

**Comment by esbobkov** [comment]
How about move from Behat/Transliterator to Symfony/Strings? 

Like this https://github.com/KnpLabs/DoctrineBehaviors/pull/468/files#diff-c5f7d7b9e0f14fa580860143f56f3b7f

**Comment by cybernet** [comment]
> 
> 
> How about move from Behat/Transliterator to Symfony/Strings?
> 
> Like this https://github.com/KnpLabs/DoctrineBehaviors/pull/468/files#diff-c5f7d7b9e0f14fa580860143f56f3b7f

thanks, i'll have a look :)

**Comment by AkenRoberts** [comment]
Going to close, since there doesn't appear to be any specific security issues or concerns at this time. Please open up another issue if you find something. :)
