### ISSUE TITLE
[Sortable] Branch 2.4.x not compatible with PHP 5.3.2

### ISSUE THREAD

**Issue by gabrielfin** [Atlantic18/DoctrineExtensions#2043]
According to composer.json, the v2.4.x branch and the v2.4.36 and v2.4.37 tags are compatible with PHP >=5.3.2, but the following code uses 5.4 syntax:
```php
$updatedObjects = [];
```
here: https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Sortable/SortableListener.php#L417

**Comment by AkenRoberts** [comment]
Thank you 👍
