### ISSUE TITLE
Change to AbstractLogEntry[] to allow custom LogEntry implementations

### ISSUE THREAD

**Issue by P34CH** [Atlantic18/DoctrineExtensions#2049]
https://github.com/Atlantic18/DoctrineExtensions/blob/26b872821aab3e3e310080e732d2680293d6d7d0/lib/Gedmo/Loggable/Entity/Repository/LogEntryRepository.php#L33

In my opinion the return type annotation shoud be changed to `AbstractLogEntry[]`. This would allow to implement custom log entry classes based on the abstract log entry class.

**Comment by mathinvoker** [comment]
I agree. I am trying to add an extra field to the ext_log_entries table but I didn't come up with anything.
Should I extend all these classes (LogEntry, LoggableListener...)?

**Comment by AkenRoberts** [comment]
Good idea, @P34CH. Thank you.

@mathinvoker I'd suggest opening a new issue if you are still struggling with that. Although I cannot guarantee much support via these issues. StackOverflow or similar resource might help you more.
