### ISSUE TITLE
[Translatable] Update to Doctrine MongoDB 2.0 (easy to fix)

### ISSUE THREAD

**Issue by lcavero** [Atlantic18/DoctrineExtensions#2054]
Hi, with Doctrine MongoDB 2.0 I get the next error:

PHP Fatal error:  Uncaught Error: Class 'Doctrine\ODM\MongoDB\DocumentRepository' not found in /xxxx/vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Document/Repository/TranslationRepository.php:21

You can fix it replacing **Doctrine\ODM\MongoDB\DocumentRepository** by **Doctrine\ODM\MongoDB\Repository\DocumentRepository**.

Also, in Gedmo\Translatable\Mapping\Event\Adapter\ODM, in method **insertTranslationRecord**, line 162, you are using $collection->insert(). Insert method is no longer available, could you put insertOne/insertMany method to fix the error (I think is insertOne)? Thanks.

Can you fix it? Ty

**Comment by AkenRoberts** [comment]
Thank you @lcavero for the specific errors. These should indeed be relatively straight forward to fix, but will require a new major version of Doctrine Extensions, which still has some debate about its direction.

I'll do my best to release ODM 2.0 compatibility as soon as I can.

**Comment by emulienfou** [comment]
Hi @AkenRoberts and @lcavero I made a PR for ODM 2.0 compatibility in August.   
https://github.com/Atlantic18/DoctrineExtensions/pull/2040   
Just tested with SF5.0, seems to work fine on my project!

**Comment by DGCarramona** [comment]
Hi @emulienfou, how did you managed to use your fork with SF5.0 ? I've only succeeded by creating a fork of stof bundle to add your fork on composer.json

**Comment by emulienfou** [comment]
Hi @DGCarramona glad you ask the question. I found, not long ago that someone already do the job and fork the Stof bundle.   

So I just replace the `stof/doctrine-extensions-bundle` by this one and it works like a charm: https://packagist.org/packages/antishov/doctrine-extensions-bundle

**Comment by DGCarramona** [comment]
I think I didn't understood. How using this fork of stof allows you to use your fork of gedmo ?

**Comment by emulienfou** [comment]
Firstly you need to remove `stof/doctrine-extensions-bundle` then install the package `antishov/doctrine-extensions-bundle`.
This replacement package is compatible with sf5.
When you did that, you will need to install my fork

**Comment by lcavero** [comment]
Hi @emulienfou how can I install your fork? I just replace stof/doctrine-extensions-bundle by antishov, and now? Thanks

**Comment by emulienfou** [comment]
Hi @lcavero, not a problem, here is how I proceed to install everything: 
1. Remove stof bundle by executing: `composer remove stof/doctrine-extensions-bundle`
2. Install antishov fork: `composer require antishov/doctrine-extensions-bundle:^1.4`
3. Add custom repository in your `composer.json`:
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/emulienfou/DoctrineExtensions"
        }
    ]
}
```
4. Install my fork: `composer require gedmo/doctrine-extensions:v2.4.x-dev`

**Comment by AkenRoberts** [comment]
`master` is currently ODM 2.0 compatible (at least as far as our tests are concerned). You can use version `3.0-dev` to install it locally for testing. I'd love to hear any issues or advice to make sure it's as stable as possible before a full release.
