### ISSUE TITLE
[Sluggable] Support for PHP 7.4

### ISSUE THREAD

**Issue by binarious** [Atlantic18/DoctrineExtensions#2056]
The default transliterator used for the slug creation [throws deprecations warnings with PHP 7.4](https://github.com/Behat/Transliterator/issues/25). This should be fixed upstream or another default implementation should be used.

**Comment by AkenRoberts** [comment]
Thank you for your contribution, @binarious.

As you noted, it is an upstream issue that we have no direct control over. A new default implementation is definitely an option, although one that is _very_ far down on the priority list right now.

I'm sorry I can't be more helpful at this time.
