### ISSUE TITLE
Blameable should use a callable for setting "user value"

### ISSUE THREAD

**Issue by oojacoboo** [Atlantic18/DoctrineExtensions#2069]
Okay, so a few things here.  

1.  The term "user" is too presumptuous and should be removed for a more neutral "value" term.
2.  The `getFieldValue` method should check if the value is a callable, and call it if so.

Regarding the callable - this allows for the "user value" to be set at a later point, or updated easily.  Using a callable means that it'll execute that function to get the value when it's needed and doesn't require that it be set during initialization only.

This solves multiple use cases and is a very simple addition.

I've created a pull request: #2068

**Comment by AkenRoberts** [comment]
I've copied this issue text to the PR. Let's keep all related discussion to one place. 👍
