### ISSUE TITLE
[Loggable] - Since Sf 4.4 - Username is always null in log entries

### ISSUE THREAD

**Issue by pmartineau-stino** [Atlantic18/DoctrineExtensions#2078]
Hi,

Since migrating to Symfony 4.4.+, username is always null in log entries. 
I fixed it with adding this line to `DoctrineExtensionSubscriber::onKernelRequest()`:

`$this->loggableListener->setUsername($this->tokenStorage->getToken()->getUser()->getUsername());`

I hope it will help someone. 
Maybe the `doc/symfony4.md` should be updated too?

**Comment by AkenRoberts** [comment]
Extensions didn't change anything that 4.4 would've broken. Perhaps your kernel listener wasn't registered or something to that effect.

This is documented in the [Extension Listener Services](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/symfony4.md#doctrine-extension-listener-services) part of the Symfony 4 docs.
