### ISSUE TITLE
[Sluggable] Property type ignored for association unique_base

### ISSUE THREAD

**Issue by chetanism** [Atlantic18/DoctrineExtensions#2080]
Hi,
My apologies for not being able to put the exact problem clearly. I can however put some details on how I faced the problem, and what worked as a fix for me.

1. I am using `Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType` as primary keys in my application
2. I have two entities: `Account` and `Team` where a team belongs to an account and an account may have multiple teams.
3. I needed to create team slugs that would be unique under their account scope.
4. I used `Sluggable` in my `Team` entity as `@Gedmo\Slug(fields={"name"}, unique=true, unique_base="parentAccount", updatable=false)`

On running the application I found that Sluggable is not creating unique slugs which causes to throw a unique constraint violation error. 

While debugging the application I found that [this line](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Sluggable/Mapping/Event/Adapter/ORM.php#L55) in the ORM adapter class ignores the  type of the mapped property while setting the parameter value in the query, which caused the string value of the UUID to be picked up by default instead of the binary value.

A [similar statements](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Sluggable/Mapping/Event/Adapter/ORM.php#L67) few line below handles the type correctly.

[Here is the commit](https://github.com/chetanism/DoctrineExtensions/commit/e1cd60cd01cf8b6ffcc459f5b59453d6b84dfdf3) that seemed to fix the issue for me. If the change looks good, I can raise a PR to fix the issue.

Thanks.

**Comment by AkenRoberts** [comment]
Absolutely, feel free to submit a PR targeting the `master` branch. If possible, try to add a test that fails with the current setup but passes with your changes so we know it's covered.
