### ISSUE TITLE
Using Blameable with doctrine-fixtures-bundle

### ISSUE THREAD

**Issue by Mouerr** [Atlantic18/DoctrineExtensions#2083]
Hi, 
Am currently using Timestampable and Blameable in my entities and all working well, but when i execute my fixtures, all entities created with the correct created_at and updated_at but created_by and updated_by stays null. i think because no user is authenticated when executing the fixtures cmd.
Is there a solution to get the job done?

**Comment by AkenRoberts** [comment]
> i think because no user is authenticated when executing the fixtures cmd

Bingo. Assuming you're using the [StofDoctrineExtensionsBundle](https://github.com/stof/StofDoctrineExtensionsBundle), it only adds the user to Blameable if it's an HTTP request and there is an authenticated user.

You can [use the bundle as an example](https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/EventListener/BlameListener.php) for how to inject the BlameableListener and specify the current user to blame. You can do this within a command itself if you only need to worry about one, or perhaps by listening to a [console event](https://symfony.com/doc/current/components/console/events.html). Got a few different options there, for whatever makes sense to your console app.

**Comment by Mouerr** [comment]
Thanks for your assistance, i will listen to console event.
