### ISSUE TITLE
Error in official example of Tree "closure" strategy

### ISSUE THREAD

**Issue by emovere** [Atlantic18/DoctrineExtensions#2086]
**This example from the official ReadMe:**
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/tree.md#orm-entity-example-annotations-1

**outputs this error:**
```
The association App\Entity\Category#parent refers to the inverse side field App\Entity\Category#children which does not exist.
```

**Whats the fix?
Add a Children property like this without any getter and setter?**
```
    /**
     * @ORM\OneToMany(targetEntity="Category", mappedBy="parent")
     */
    private $children;

```

**Comment by AkenRoberts** [comment]
Thank you. :) If there are still any issues, please let me know.
