### ISSUE TITLE
SoftDeleteableFilter::addFilterCriteria return type missing

### ISSUE THREAD

**Issue by theyough** [Atlantic18/DoctrineExtensions#2088]
### Environment version
`php: 7.4.1`
`symfony: 4.4.2`
`stof/doctrine-extensions-bundle: 1.3.0`

### Description
When i try to use the ODM SoftDeleteable Filter i got this error:

```
Compile Error: Declaration of Gedmo\SoftDeleteable\Filter\ODM\SoftDeleteableFilter::addFilterCriteria(Doctrine\ODM\MongoDB\Mapping\ClassMetadata $targetEntity) must be compatible with Doctrine\ODM\MongoDB\Query\Filter\BsonFilter::addFilterCriteria(Doctrine\ODM\MongoDB\Mapping\ClassMetadata $class): array
```

**Comment by AkenRoberts** [comment]
Extensions 2.4.x isn't compatible with Doctrine MongoDB ODM 2.0. This is just one of many incompatibilities that I'm working on addressing in `master` for an Extensions 3.0 release. It is a known issue, and thank you for mentioning it!
