### ISSUE TITLE
DoctrineExtensions 3.0?

### ISSUE THREAD

**Issue by Alfro** [Atlantic18/DoctrineExtensions#2091]
Hi!

What are the plans for a 3.0 release? Will it be compatible with Doctrine MongoDB ODM 2.x?

I have been surfing around the project and it seems there are plans for it and work being done in master.

We are using the Tree and Sortable extensions and are looking to upgrade to ODM 2.x

**Comment by AkenRoberts** [comment]
Indeed work is being done on `master` to move to ODM 2.0, along with a few other modernization efforts. I don't have a specific deadline or release date in mind, because I don't want to make any promises I can't keep.

I'd love some assistance in testing 3.0 once it's closer to a beta. Keep an eye around here as that gets closer. (I'm seeing now that an email list or something might be useful, and will look into that as well.)

**Comment by Alfro** [comment]
Hey there,

Less than two months ago I did a PR against feature/mongodb-odm-2.0 #2096

The only thing missing detail to move to ODM 2.0 may be fixing the tests. We temporarily forked and merged to master to test compatibility and we have detected no errors so far.

As soon as there is a working version in master, we will test it with our platform. :)

**Comment by AkenRoberts** [comment]
Cheers @Alfro for your addition.

I have [the ODM 2.0 branch](https://github.com/Atlantic18/DoctrineExtensions/tree/feature/mongodb-odm-2.0) passing all tests now. Hoping you can take a look and help confirm any potential issues or gotchas.

I'll try to document what was changed a bit further later this evening.

**Comment by AkenRoberts** [comment]
Notably, I think there's a weird in-between state of the original `Mongo` extension, and the new one with the BSON types. I know there are other deprecated classes being used still (e.g. `MongoId`). Some are likely not covered by tests, though.

I'm not sure if it's worth completely ripping the band aid off now and eliminating the usages of all of those, getting rid of the old Doctrine adapter package, etc. Any thoughts there would be great.

**Comment by borodiliz** [comment]
@AkenRoberts I've just tested one of my projects with `dev-master 49c8315` and no problems detected so far. I'm using `Translatable`(ORM) and `Loggable` (ODM)

Only those minor changed needed:

```diff
---

diff --git a/config/packages/doctrine.yaml b/config/packages/doctrine.yaml
index cc04c61..e53c84a 100644
--- a/config/packages/doctrine.yaml
+++ b/config/packages/doctrine.yaml
@@ -39,7 +39,7 @@ doctrine:
                 alias: Gedmo
                 prefix: Gedmo\Translatable\Entity
                 # make sure vendor library location is correct
-                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity/MappedSuperclass"
+                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity/MappedSuperclass"
         hydrators:
             UniqueColHydrator: \App\Hydrators\UniqueColHydrator
             UniqueGroupColHydrator: \App\Hydrators\UniqueGroupColHydrator
diff --git a/config/packages/doctrine_mongodb.yaml b/config/packages/doctrine_mongodb.yaml
index ed5d38e..e184bc5 100644
--- a/config/packages/doctrine_mongodb.yaml
+++ b/config/packages/doctrine_mongodb.yaml
@@ -22,4 +22,4 @@ doctrine_mongodb:
                     alias: GedmoDocument
                     prefix: Gedmo\Loggable\Document
                     # make sure vendor library location is correct
-                    dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Document"
+                    dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Document"
-- 
```
Thanks for your time!

**Comment by Alfro** [comment]
Hi @AkenRoberts!

Thanks for your hard work! We will be sure to test the 3.0 branch and let you know if we come across anything.

I think we can close this issue, since the original question has been answered and master seems to already have a working support for ODM 2.0 and a 3.0 version on its way eventually.

**Comment by AkenRoberts** [comment]
Thank you for testing and your feedback so far. Happy to hear more any time.
