### ISSUE TITLE
PHP 7.4 issues

### ISSUE THREAD

**Issue by dpauli** [Atlantic18/DoctrineExtensions#2092]
There are several PHP 7.4 issues, that should be fixed before this package is PHP 7.4 usable:
- `implode` needs to have the first parameter the `$glue`:
-- https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/ReferenceIntegrity/Mapping/Driver/Annotation.php#L67
-- https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/ReferenceIntegrity/Mapping/Driver/Yaml.php#L63

**Comment by AkenRoberts** [comment]
Thank you, @dpauli. If you'd like to PR any of these changes to the `master` branch, that's where we're targeting PHP 7.2+. Otherwise I'll get them in when I can! Cheers.
