### ISSUE TITLE
[QUESTION] How to allow custom doctrine type with SoftDelete / Timestampable?

### ISSUE THREAD

**Issue by AndreasA** [Atlantic18/DoctrineExtensions#2105]
Hi,

I want to use a custom doctrine type for SoftDelete / Timestampable. It would still convert to and form DateTime, so that would not be an issue.

The main reason is that I want to add support for microseconds to some of my DateTime fields (especially the SoftDelete / Timestampable) fields.

I checked and both would be able to handle them. However, it is quite tricky to add those types to the listeners. For SoftDelete I could probably add it to the public static property `\Gedmo\SoftDeleteable\Mapping\Validator::$validTypes`. However that is not very elegant (especially in combination with using the Symfony bundle) and for Timestampable it is a protected property.

The solution would be to override the the corresponding driver but that means to change the namespace in the listener class which also means to override all other classes that are inside that namespace to be sure everything works correctly and also to override all three drivers if necessary,

**Comment by AkenRoberts** [comment]
Hi @AndreasA. Yes this is an unfortunate issue, handling custom types/values. Right now Extensions is pretty hard-coded for the types it supports.

Give #1946 a follow for progress on this issue. I'm going to look into looping DBAL into the extension so we don't need to manage this separately. It's requested often enough that I'm going to try getting it into 3.0.
