### ISSUE TITLE
SoftDeleteable produces wrong SQL

### ISSUE THREAD

**Issue by TheFox** [Atlantic18/DoctrineExtensions#2106]
I'm using SoftDeleteable in Entity A. If I join Entity A on Entity B which generates

```sql
SELECT ...
FROM objects_badges o0_
LEFT JOIN obj o1_ ON o0_.obj_id = o1_.id AND ((o1_.deleted_at IS NULL OR o1_.deleted_at > CURRENT_TIMESTAMP))
```

This returns Bs even if the corresponding A is already soft-deleted. If I switch to a WHERE instead

```sql
SELECT ...
FROM objects_badges o0_
LEFT JOIN obj o1_ ON o0_.obj_id = o1_.id
WHERE ((o1_.deleted_at IS NULL OR o1_.deleted_at > CURRENT_TIMESTAMP))
```

this works perfect.

**Comment by AkenRoberts** [comment]
This is expected behavior. The constraint is always added with respect to the entity that is soft deleted.

I think in your example, using an `INNER JOIN` should properly utilize the `Object` soft delete constraint while still keeping it on the join.

**Comment by TheFox** [comment]
I see. That works. Thank you, @AkenRoberts.
