### ISSUE TITLE
SoftDeleteableEntity trait getDeletedAt() method doesn't return null

### ISSUE THREAD

**Issue by benjamintoussaint** [Atlantic18/DoctrineExtensions#2110]
Hi,

How come the `SoftDeleteableEntity` trait `getDeletedAt()` method doesn't return `null`?

```php
/**
 * Returns deletedAt.
 *
 * @return \DateTime
 */
public function getDeletedAt()
{
    return $this->deletedAt;
}
```

It should be either `null` or a `\DateTime()`, or am I missing something here?

Thank you!

cf. https://github.com/Atlantic18/DoctrineExtensions/blob/0b7bdbefd3d166def27928dcd62ab67c11c8f172/lib/Gedmo/SoftDeleteable/Traits/SoftDeleteableEntity.php#L40

**Comment by benjamintoussaint** [comment]
I guess we are encouraged to use `isDeleted()` method prior to using `getDeletedAt()`.

**Comment by AkenRoberts** [comment]
Good observation. Contrary to the docblock, it will return `null` if `$deletedAt` is not set to a DateTime value.

Updating the docblock for now sounds like a good idea. Then the next major release can focus on adding proper type declarations.
