### ISSUE TITLE
[Sortable] Issue with position when item was added

### ISSUE THREAD

**Issue by Suhov-Igor** [Atlantic18/DoctrineExtensions#2113]
After new item was added position of other elements didn't updated at all. I found the reason of this.
Here all related methods that are called during adding of item and important for reprodusing of bug:
- processInsert - here all relocation rules were created
- postFlush - here all relocation rules were removed. This method was called before updating positions only for add item action. For update and delete item actions it called after all manipulation and all works good.
- postPersist - here persistRelocations method was called for updating positions of other items, but without rules it did nothing

Summarise, for some reason postFlush method was called before postPersist and broke ubdating of posittions.

**Comment by AkenRoberts** [comment]
It would be helpful if you provided more information about the code you're using. Anything to help create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Suhov-Igor** [comment]
Hello. 
My project based on symfony 3.4, php 7.2, gedmo/doctrine-extensions v2.4.39.

In my entities I use @Gedmo\SortablePosition() annotation for  property position.
```    /**
     * @var integer
     * @Assert\Range(
     *      min = 0,
     *      minMessage = "Min value should be {{ limit }}"
     * )
     *
     * @Gedmo\SortablePosition()
     *
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $position;
```
If I set position for new entity object then position of another objects didn't update.
But if I update position of existing objects or remove some objects then all work good.
I looked for a problem and found that reason of the problem in \Gedmo\Sortable\SortableListener and in order of his methods were called.

Also I add, update or delete only one object in the same time and didn't work with set of objects.

**Comment by AkenRoberts** [comment]
I'm sorry, but there's just not enough information to determine where the issue may be.

If you are able to create the minimal, reproducible example as linked earlier, I can try to take a look again. Anything else would just be speculation or 1-on-1 debugging help, which I have insufficient time for. I wish I could be of more help.
