### ISSUE TITLE
Compatibility with doctrine/mongodb-odm

### ISSUE THREAD

**Issue by CvekCoding** [Atlantic18/DoctrineExtensions#2118]
https://github.com/Atlantic18/DoctrineExtensions/blob/fbc95cd0d22560000e82eb6838011b366425d16c/lib/Gedmo/SoftDeleteable/Filter/ODM/SoftDeleteableFilter.php#L22

Here we must return `array` to comply to function signature.

**Comment by AkenRoberts** [comment]
Completed already [in the `master` branch](https://github.com/Atlantic18/DoctrineExtensions/blob/2b38b16e334c6d94e828fed09c183d5e181c79d9/src/SoftDeleteable/Filter/ODM/SoftDeleteableFilter.php#L20). Please give the `3.0-dev` version a shot if you'd like to test MongoDB ODM 2.0 compatibility.

**Comment by CvekCoding** [comment]
@AkenRoberts great, thanks. I'll try it.
