### ISSUE TITLE
Support doctrine/common 3

### ISSUE THREAD

**Issue by jaikdean** [Atlantic18/DoctrineExtensions#2130]
The [release notes](https://github.com/doctrine/common/releases/tag/3.0.0) for `doctrine/common` 3.0.0 suggest it's easy to support both 2.x and 3.0.

**Comment by sixpeteunder** [comment]
Has any work been done on this? Or is there a form in which doctrine/common 3.0 is supported?

**Comment by jaikdean** [comment]
@sixpeteunder See #2150

**Comment by sixpeteunder** [comment]
Thanks @jaikdean. I left a comment on there.

**Comment by svycka** [comment]
we have to drop php <=7.1 versions if we want `doctrine/common:3.0.0`

**Comment by AkenRoberts** [comment]
Thank you for bringing this up and doing some initial recon. 👍 

There are no plans to do any of this on the 2.4.x branch. `master` is targeting a 3.0 release and has already done some initial work here, such as updating some dependencies, bumping the minimum PHP version to 7.2, etc.

I haven't added support for doctrine/common 3.0 yet, though. I'll take care of that now. :)

**Comment by AkenRoberts** [comment]
⬆️ Completed in #2150.
