### ISSUE TITLE
Attempted to load class "DocumentRepository" from namespace "Doctrine\ODM\MongoDB".

### ISSUE THREAD

**Issue by nkanzari** [Atlantic18/DoctrineExtensions#2134]
Using PHP7.4 on Centos7 with Symfony 4.4. Moving from ODM V1.2 to V2 and I'm getting the following error in LogEntryRepository.php line 18 when running composer update:

```
Attempted to load class "DocumentRepository" from namespace "Doctrine\ODM\MongoDB".                                                                     
Did you forget a "use" statement for "Doctrine\ODM\MongoDB\Repository\DocumentRepository"?
```

The DocumentRepository class moved under namespace "Doctrine\ODM\MongoDB\Repository" as explained in the error.

**Comment by AkenRoberts** [comment]
ODM 2.0 support has been added to `master` for an eventual 3.0 release. If you'd like to try it, change your composer.json version requirement to `3.0-dev`, and please share any issues you find!
