### ISSUE TITLE
Please tag version 3 - it's blocking new projects from installing this library :)

### ISSUE THREAD

**Issue by weaverryan** [Atlantic18/DoctrineExtensions#2168]
Hi!

My apologies for the intrusion 🙂 . I was wondering if you have a timeline for releasing doctrine extensions 3? We're noticing users having increased problems installing doctrine extensions, because new projects tend to have `doctrine/common` 2 and `doctrine/persistence` 2 installed. So when they try to install doctrine-extensions, it fails. This is fixable by downgrading `doctrine/common` and persistence, but it's not obvious. Once you release doctrine-extensions 3, I can get Stof to merge https://github.com/stof/StofDoctrineExtensionsBundle/pull/415 and tag... and the world will be saved! Well, ok, the world will be a *teeny* bit better :).

Thanks!

**Comment by sixpeteunder** [comment]
I too, am very appreciative of the work done by @AkenRoberts and co. to modernize the library. Next, I agree with @weaverryan on this. I've been holding off on migrating some projects from Eloquent because I'm still waiting for a 3.0 stable release. Could we have a roadmap for this?

**Comment by AkenRoberts** [comment]
Tagged: https://github.com/Atlantic18/DoctrineExtensions/releases/tag/v3.0.0 🥳

**Comment by weaverryan** [comment]
Thank you!

> I too, am very appreciative of the work done by @AkenRoberts and co. to modernize the library

💯
