### ISSUE TITLE
Bug after composer install 

### ISSUE THREAD

**Issue by Noido** [Atlantic18/DoctrineExtensions#2177]
Hi i just run composer install and got this error 

 Installing gedmo/doctrine-extensions (v3.0.0): Loading from cache

Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
46 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Specified non-existing directory "C:\xampp74\htdocs\testproject\src/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity" as Doctrine mapping source.

When i check in 
C:\xampp74\htdocs\testproject\vendor\gedmo\doctrine-extensions  i don t see any lib folder

Can you help me ?

Regards

**Comment by AkenRoberts** [comment]
The src directoy has been rearranged in 3.0. Is this an existing project, or are you installing fresh?

**Comment by joanv38** [comment]
Hi, no answer on this thread so i'm gonna add detail. I got the same problem on existing project in symfony 5.1.
You will got this message:
Specified non-existing directory ".../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity" as Doctrine mapping  source.  
by doing the following step:
- ./composer.phar require gedmo/doctrine-extensions
- "gedmo/doctrine-extensions": "^3.0" then composer update or deleting all the vendor then composer install.

I didn't had time to find a solution yet but if I find something i'm will post here.

**Comment by gallien-lbr** [comment]
Hi joanv38,
It seems this bug is linked to a small change in gedmo directory structure, try to change : 
from
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
to
` dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/src/Translatable/Entity"`

let us know if it is solves your issue,

**Comment by AkenRoberts** [comment]
Thank you for the assist @gallien-lbr 👍🏼 

Correct, if you're updating your Doctrine Extensions library to 3.0, you'll either need to update your Doctrine configs if you've installed manually, or update one of the bundles that helps configure Symfony.

**Comment by zoomtronic** [comment]
Thanks, after a composer update i had this error and @gallien-lbr you made my day ! :)
