### ISSUE TITLE
Allow PHP 8

### ISSUE THREAD

**Issue by ilianiv** [Atlantic18/DoctrineExtensions#2186]
Hi there!

Please allow PHP 8 in compser.json requirements if there's no compatibility issues.

Thanks!

**Comment by VeryStrongFingers** [comment]
There's a PR open for PHP 8 https://github.com/Atlantic18/DoctrineExtensions/pull/2182

**Comment by kluevandrew** [comment]
Any updates on this?

**Comment by AkenRoberts** [comment]
Thank you, and apologies for the delay. PHP 8 compatibility is now in 3.x (3.0.3 specifically). Should be in Packagist shortly. ❤️
