### ISSUE TITLE
PHP 8 Deprecated:  Required parameter $object follows optional parameter

### ISSUE THREAD

**Issue by insekticid** [Atlantic18/DoctrineExtensions#2190]
https://github.com/Atlantic18/DoctrineExtensions/blob/be551985759946a45d052777c2906aa52db64532/src/Uploadable/UploadableListener.php#L470

PHP Deprecated:  Required parameter $object follows optional parameter $filenameGeneratorClass in /var/www/html/vendor/gedmo/doctrine-extensions/src/Uploadable/UploadableListener.php on line 470
Symfony 5.2.1 (env: dev, debug: true)

**Comment by AkenRoberts** [comment]
Fixed in 3.0.3 ✅

**Comment by insekticid** [comment]
there is no 3.0.3 version on packagist
https://packagist.org/packages/gedmo/doctrine-extensions

**Comment by AkenRoberts** [comment]
Yeah, I'm sorry 😢 3.0.1 was an accidental tag of the 2.4.x branch. I don't have any admin rights on this repository so I can't delete tags or set up auto-updating on Packagist. I have to just manually renew it when possible, and apparently I've used my one update for ~24 hours or however long it is.

3.0.3 will be available on Packagist hopefully today. I'm really sorry for the hiccup.
