### ISSUE TITLE
[Loggable] Can't insert new entries with ramsey uuid as primary key

### ISSUE THREAD

**Issue by Tanktiger** [Atlantic18/DoctrineExtensions#2195]
Hi,

i get the following error when i want to create new entry a new log entry.

` SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xEBZ\x96t\x02\x0B...' for column `uuid_test_migration_v2`.`ext_log_entries`.`data` at row 1`

My Software stack is: symfony 4.4 with doctrine 2.7.5 and doctrine extensions in version 2.4.42.
I'm currently switching our software from INT Primary Key to UUID Primary Key. I'm using ramsey/uuid.

This ist the query which will be generated by the doctrine extensions:

`INSERT INTO ext_log_entries (action, logged_at, object_id, object_class, version, data, username) VALUES ('create', '2021-01-25 15:28:25', '95cc77a2-5f19-11eb-a7d8-0242ac120005', 'App\\Entity\\Member', 1, 0x613A373A7B733A31303A2273616C75746174696F6E223B733A343A2248657272223B733A353A227469746C65223B733A333A2244522E223B733A393A2266697273746E616D65223B733A343A224A6F686E223B733A383A226C6173746E616D65223B733A333A22446F65223B733A353A22656D61696C223B733A32363A226A6F686E34333536343339333435406164766F6361646F2E6465223B733A31343A22637573746F6D65726E756D626572223B733A383A226530633366636332223B733A353A2267726F7570223B613A313A7B733A323A226964223B433A32363A2252616D7365795C557569645C526663343132325C557569645631223A31363A7B11EB5A9674020B0AB1F90242AC1200027D7D7D, 'anon.');`

` An exception occurred while executing 'INSERT INTO ext_log_entries (action, logged_at, object_id, object_class, version, data, username) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["create", "2021-01-25 15:28:25", "95cc77a2-5f19-11eb-a7d8-0242ac120005", "App\\Entity\\Member", 1, "\x61\x3a\x37\x3a\x7b\x73\x3a\x31\x30\x3a\x22\x73\x61\x6c\x75\x74\x61\x74\x69\x6f\x6e\x22\x3b\x73\x3a\x34\x3a\x22\x48\x65\x72\x72\x22\x3b\x73\x3a\x35\x3a\x22\x74\x69\x74\x6c\x65\x22\x3b\x73\x3a\x33\x3a\x22\x44\x52\x2e\x22\x3b\x73\x3a\x39\x3a\x22\x66\x69\x72\x73\x74\x6e\x61\x6d\x65\x22\x3b\x73\x3a\x34\x3a\x22\x4a\x6f\x68\x6e\x22\x3b\x73\x3a\x38\x3a\x22\x6c\x61\x73\x74\x6e\x61\x6d\x65\x22\x3b\x73\x3a\x33\x3a\x22\x44\x6f\x65\x22\x3b\x73\x3a\x35\x3a\x22\x65\x6d\x61\x69\x6c\x22\x3b\x73\x3a\x32\x36\x3a\x22\x6a\x6f\x68\x6e\x34\x33\x35\x36\x34\x33\x39\x33\x34\x35\x40\x61\x64\x76\x6f\x63\x61\x64\x6f\x2e\x64\x65\x22\x3b\x73\x3a\x31\x34\x3a\x22\x63\x75\x73\x74\x6f\x6d\x65\x72\x6e\x75\x6d\x62\x65\x72\x22\x3b\x73\x3a\x38\x3a\x22\x65\x30\x63\x33\x66\x63\x63\x32\x22\x3b\x73\x3a\x35\x3a\x22\x67\x72\x6f\x75\x70\x22\x3b\x61\x3a\x31\x3a\x7b\x73\x3a\x32\x3a\x22\x69\x64\x22\x3b\x43\x3a\x32\x36\x3a\x22\x52\x61\x6d\x73\x65\x79\x5c\x55\x75\x69\x64\x5c\x52\x66\x63\x34\x31\x32\x32\x5c\x55\x75\x69\x64\x56\x31\x22\x3a\x31\x36\x3a\x7b\x11\xeb\x5a\x96\x74\x02\x0b\x0a\xb1\xf9\x02\x42\xac\x12\x00\x02\x7d\x7d\x7d", "anon."]`

And this is the serialized value for data: (taken from symfony debug toolbar)
`b"""
    a:7:{s:10:"salutation";s:4:"Herr";s:5:"title";s:3:"DR.";s:9:"firstname";s:4:"John";s:8:"lastname";s:3:"Doe";s:5:"email";s:26:"john4356439345@test.de";s:14:"customernumber";s:8:"e0c3fcc2";s:5:"group";a:1:{s:2:"id";C:26:"Ramsey\Uuid\Rfc4122\UuidV1":16:{\x11ëZ–t\x02\v
    ±ù\x02B¬\x12\x00\x02}}}
    """`

Why does it not use the string representation of the UUID?

**Comment by Tanktiger** [comment]
I've found a solution. It's not perfect but it works. I've hooked into the prePersist Event for the LogEntry and loop through the data. If a value is instance of UuidInterface i will get the string.

```
protected function prePersistLogEntry($logEntry, $object)
{
    $logEntry->setData($this->convertObjectsInData($logEntry->getData()));
}
```

```
private function convertObjectsInData(array $data): array
{
    foreach ($data as $key => $value) {
        if (is_array($value)) {
            $data[$key] = $this->convertObjectsInData($value);
        } else {
            if ($value instanceof UuidInterface) {
                $data[$key] = $value->toString();
            }
        }

    }
    return $data;
}
```

**Comment by AkenRoberts** [comment]
Thanks for identifying this. The Extensions in general have some holes in how different data types are handled, specifically custom ones. Came up in #2189 recently as well. Going to use that ticket as a tracker for potentially getting this improved in 3.0.
