### ISSUE TITLE
A new top level Root removes the root for the children during cascading saves 

### ISSUE THREAD

**Issue by ssmusoke** [Atlantic18/DoctrineExtensions#342]
using Gedmo 2.3.0-DEV and Doctrine 2.2.1.

I am using the above example for fruits as a starting point. I want to add a new root above Food so I execute the following:

$repo = $this->em->getRepository('Category');

$food1 = $repo->findOneByTitle('Food');

$root = new Category(); $root->setTitle("Root"); $food1->setParent($root);

$em->persist($food1); $em->persist($root);
$em->flush();

The root is saved okay, however the following happens:

a) The levels are updated okay

b) The left and right values for the existing categories are not updated

c) The new root value for the existing categories becomes 0

d) Food gets the correct parent_id from the new root added

I am trying to save all the categories as a single transaction with cascades. This only occurs when the root node is not saved before its added to the food category. When I save the root first, then add it to the food category and save it, the tree is updated correctly.

A test case for this can be found at https://gist.github.com/2707681 - which is adopted from the existing testTheTree() function, I can add more tests for deeper levels once the first one works 

Thanks in advance

**Comment by AkenRoberts** [comment]
As of now, the root should be given a foreign key when defined as an association.
