### ISSUE TITLE
more detailed info about the advance use of the translation listener

### ISSUE THREAD

**Issue by metalvarez** [Atlantic18/DoctrineExtensions#391]
hi im having a problem when updating records with the same field value in multiple languages, in example lets say i want to translate the company entity, and my default locale is 'es' so i save the record for The Cola Company with the title The Cola Company, description in spanish and then i want to translate that record usin the uri locale, that works only if i change the title field , so i'm wondering if that can be solve by setting the translation fall back to true, and if so how can i instantiate the translation listener ?.

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
