### ISSUE TITLE
PSR for Slugifier/Urlizer Interface

### ISSUE THREAD

**Issue by dantleech** [Atlantic18/DoctrineExtensions#649]
Hi l3pp4rd,

Just to let you know, we are making a proposal for the creation of a standard slugifier/urlizer interface at fig-standards: https://github.com/php-fig/fig-standards/pull/100

There is also a mailing list post: https://groups.google.com/forum/?fromgroups=#!topic/php-fig/J-6s9Wlyk-A

It would be cool if this proposal goes through and we can apply to the urlizer in DocutrineExtensions :)

Cheers

Dan

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
