### ISSUE TITLE
[tree] support adjacency list strategy?

### ISSUE THREAD

**Issue by bronze1man** [Atlantic18/DoctrineExtensions#742]
Sometimes the tree is not so big,or we not need recursion find all children.
# advantage
- Simple to implement for user of DoctrineExtensions,just add a parent field to implement.
- Fast to insert and update.
- Fast to get direct children ,get direct parent or build html tree ....
- Space save
- No duplicate
# disadvantage
- It is slow to recursion find all children.
- It is slow to check relation between two node.
- It is slow to check tree valid.

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
