### ISSUE TITLE
Translatable Emtpy Value not saving

### ISSUE THREAD

**Issue by marclindemann** [Atlantic18/DoctrineExtensions#788]
In TranslatableListener.php line 599

if (((is_null($content) && !$isInsert) || is_bool($content) || is_int($content) || (is_string($content) && strlen($content) > 0) || !empty($content)) && ($isInsert || !$transWrapper->getIdentifier() || isset($changeSet[$field]))) {
}

When i delete value of a field (text) it is not saving because of (is_string($content) && strlen($content) > 0)

i think this is an issue. Why you check here strlen > 0?

$entitity->setHinweis("");

-> not saving.

**Comment by duepi** [comment]
@l3pp4rd Any news on this ? I'm experiencing this in Version 2.4.12. thanks in advance

**Comment by FireLizard** [comment]
Hi, 
is there a way (maybe by configuration) to remove the translation instead of allow an empty string to get the default fallback?
