### ISSUE TITLE
[SortableGroup/SortablePosition] Bug while changing few items at the same time

### ISSUE THREAD

**Issue by Koonstaantiin** [Atlantic18/DoctrineExtensions#824]
Hello!
I noticed bug while changing few items.

How to repeat:
1. Create a simple Entity with the next fields: 

``` php
/**
 * @ORM\Column(type="integer")
 * @ORM\Id
 * @ORM\GeneratedValue
 */
protected $id;

/**
 * @ORM\Column(type="string", length=255)
 */
protected $name;

/**
 * @Gedmo\SortableGroup
 * @ORM\Column(type="integer")
 */
protected $group;

/**
 * @Gedmo\SortablePosition
 * @ORM\Column(type="integer")
 */
protected $position;
```
1. Add data (id/name/group/position):
   1    1-1    1    1
   2    1-2    1    2
   3    1-3    1    3
   4    1-4    1    4
   5    2-1    2    1
   6    2-2    2    2
2. Go to the List Action
3. Open at the same time for editing (in new tabs) the elements with id №1, 3, 4
4. Change the group from 1 to 2
5. Save
6. Do the same for the items №3 and №4
7. As a result we have elements with wrong (same) positions

Option №2:
6. Save
7. Open the item №3
8. Refresh page (F5)
9. Change the group from 1 to 2
10. Save
11. Do the same for the item №4

As a result of the option №2 elements saving OKey.

P.S.: sorry for my English)

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
