### ISSUE TITLE
TreePathHash  could be neccessary if you want to set a unique constraint on the database table

### ISSUE THREAD

**Issue by abmar** [Atlantic18/DoctrineExtensions#825]
using odm, I use TreePathHash as suggested for unique constraint, but this doesnt prevent creating duplicate node. the duplicate node is inserted though its TreePath and TreePathHash arent set, unique constraint should be set on PathSource fields I guess, only way to prevent inserting a new duplicate incompletely set node.

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
