### ISSUE TITLE
Setting unique_base to a property of type JoinColumn throws an ORMInvalidArgumentException

### ISSUE THREAD

**Issue by andersaloof** [Atlantic18/DoctrineExtensions#827]
I have a setup of two entities, Model (M) and Variant (V). There is a one-to-many relationship between the two entities, a model can have many variants, and a variant belongs to a single model.

In my Variant entity I'm trying to set the unique_base of my slug to be the model property, making sure variant slugs belonging to the same model being unique, but still being able to have the same slug for variants with the same title, but on different models.

Snippet of Model.php

``` php
  /**
   * @ORM\OneToMany(targetEntity="VW\HomeBundle\Entity\Variant", mappedBy="model")
   */
  private $variants;
```

Snippet of Variant.php 

``` php
  /**
   * @ORM\ManyToOne(targetEntity="VW\HomeBundle\Entity\Model", inversedBy="variants")
   * @ORM\JoinColumn(name="model_id", referencedColumnName="id", nullable=false)
   * @Gedmo\SortableGroup
   */
  private $model;

  /**
   * @ORM\Column(type="string", length=255, nullable=false)
   * @Gedmo\Slug(updatable=false, fields={"title"}, unique_base="model")
   */
  private $slug;
```

However, this leads to an `ORMInvalidArgumentException: Binding entities to query parameters only allowed for entities that have an identifier.` Seems to me the building of the query in ORM.php ends up attaching the value of Model->toString() as a parameter, which it should not?

After som testing, I found that changing line 37 of ORM.php to the following fixed the issue for me:

``` php
if ($ubase = $wrapped->getPropertyValue($config['unique_base']) && !array_key_exists($config['unique_base'], $wrapped->getMetadata()->getAssociationMappings())) {
```

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
