### ISSUE TITLE
Translation problem with apc query_cache turned on

### ISSUE THREAD

**Issue by sparrowek** [Atlantic18/DoctrineExtensions#849]
I have a code like below:
1. Setting locale globally (e.g. from user's preference page) so that every entity is loaded in chosen language
$listener = $serviceLocator->get('TranslatableListener'); 
$listener->setTranslatableLocale($locale);
1. Querying for some entity in the default language (overriding locale set in the step 1)
   $query = "..."
   $query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\Translatable\Query\TreeWalker\TranslationWalker');
   $query->setHint(TranslatableListener::HINT_TRANSLATABLE_LOCALE, $this->serviceLocator->get('TranslatableListener')->getDefaultLocale());
2. Loading all translations for this entity
   $translations = $repository->findTranslations($entity);

The reason for this is as follows:
I want to set a locale in a global manner (step 1). Later at some point it turns out I want to load an entity with all translations because it is shown on a form with all the translations filled in at once (step 3). To prevent the globally set locale from loading my entity in it (and thus losing the translation for the default locale - i.e. the one that is stored in the entity itself not the ext_translations table) I have to force it temporarily to load in the default one (step 2).

It works all very well when query_cache is set to array but when changing it to apc I got an extra query in the log which loads the translation in the globally chosen locale so my step 2 is not working anymore

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
