### ISSUE TITLE
[Tree] Allow tree root to be a separate entity

### ISSUE THREAD

**Issue by pascalek** [Atlantic18/DoctrineExtensions#850]
This would be a nice feature if we could define TreeRoot as for instance, ManyToOne relationship. Consider such a use case:
Entity\Navigation
Entity\Page (nested set).
Now each Entity\Navigation has it's own nested set of Entity\Page. 
Currently two solutions are possible: fake root node for each Entity\Navigation or InheritanceMapping, eliminating Entity\Navigation.

**Comment by etoileweb** [comment]
Hi all, Unable to get oneToMany, ManyToOne and ManyToMany associated entities on a Tree entity. How to do this? Thanks

**Comment by l3pp4rd** [comment]
@etoileweb this has nothing to do with it, relations should be working as expected

**Comment by l3pp4rd** [comment]
implemented in master
