### ISSUE TITLE
Query::HINT_FORCE_PARTIAL_LOAD and ReferenceOne does not work

### ISSUE THREAD

**Issue by andreasschmidt** [Atlantic18/DoctrineExtensions#899]
As the title says, I'm trying to load some MongoDB documents for partial objects (don't want to load all referenced entities in my ORM entity for the list). 
When I'm trying to set HINT_FORCE_PARTIAL_LOAD to true, an exception is thrown:
"Impossible to access an attribute ("name") on a null variable ("") in"
The null variable is the variable that should be filled by the doctrine extension (i.e. an document from MongoDB). Removing the query hint will result in a correct list, but with a lot of additional queries for the references (for each row!)
Is this a bug or a missing feature?

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!
