### ISSUE TITLE
[Common] Coding standards

### ISSUE THREAD

**Issue by djlambert** [Atlantic18/DoctrineExtensions#930]
@l3pp4rd are there any particular coding standards defined/preferred for PRs and this project as a whole?

**Comment by AkenRoberts** [comment]
Closing due to age and lack of activity. If you are interested in this issue or are still experiencing any problems described here, please add a comment!

**Comment by djlambert** [comment]
Wow that's from a while ago! Sorry, I should have closed it after you answered :)
