### ISSUE TITLE
[Sortable] Updating SortableGroup and SortablePosition duplicates the position

### ISSUE THREAD

**Issue by brunoroux** [Atlantic18/DoctrineExtensions#997]
I have an ItemPosition Entity which has 2 properties 

- Category (references a category Entity) as SortableGroup
- Position as SortablePosition

CategoryA has about 30 items. Same for Category B.

When I change ItemPosition with Category : "Category B" and Position "4" to
"Category A" and Position "7"

I get some duplicated position

Expected behavior : 

```sql
update item_position set position = position - 1 where category = 'Category B' and position > 4

update item_position set position = position + 1 where category = 'Category A' and position >= 7
````

Got : 

```sql
update item_position set position = position - 1 where position >= 8 and position < 33   and category = 'Category B'

update item_position set position = position - 1 where position >= 5 and position < 8 and category = 'Category A' 
````

This means I get 2 items with position 4 in Category A.

I've tried to write a phpunit test to reproduce this but was unable to. I'll give it another try later today.

It may be important to mention, this may be related to some APC cache issue as I was only able to reproduce this on my prod environment where doctrine cache is enabled.

**Comment by Rbn3D** [comment]
Any updates on this?

**Comment by brunoroux** [comment]
Sorry I totally forgot about this issue. Thanks for the reminder.
I'll look into it in the next few days
